src/plugin/shadow-plugin-tgen/shd-tgen-action.c
src/plugin/shadow-plugin-tgen/shd-tgen-action.h
src/plugin/shadow-plugin-tgen/shd-tgen-driver.c
src/plugin/shadow-plugin-tgen/shd-tgen-graph.c

I tried my best to implement functions in a way I had seen were originally there. Notably, the addition of some getters/setters under shd-tgen-action.c

Added synchronize functionality

---

src/plugin/shadow-plugin-tgen/shd-tgen-action.c
src/plugin/shadow-plugin-tgen/shd-tgen-action.h
src/plugin/shadow-plugin-tgen/shd-tgen-driver.c
src/plugin/shadow-plugin-tgen/shd-tgen-graph.c
src/plugin/shadow-plugin-tgen/shd-tgen-graph.h

Choose elements can now optionally have weights on the edges coming from them. If present, these weights will determine the probability of a certain action being taken. Otherwise, the prior random choice option will be made. For a given edge, weights must either be completely present or completely absent.

Implemented Weighted Edges

---

tools/plot-shadow.py

Client names don't start with "client".

Fix tgen regex: client names

---

src/main/core/shd-main.c

DT_RPATH is, strictly speaking, deprecated by DT_RUNPATH, but still supported.
Different compilers/linkers will use different tags, so just look for both.
Fixes (partially) Ubuntu 17.04 build.

search for rpath in DT_RPATH or DT_RUNPATH

---

src/external/elf-loader/extract-system-config.py

This patch adds support for bulding Shadow on Debian 9 (stretch). On
Debian 9 the debug symbols of ld.so have to be found within the
`/usr/lib/debug/.build-id/...` directory tree. The checksum that is used
to find the debug symbols in the build-id tree can be found using the
`readelf -n file` command.
I have not tested this patch on Debian i386, but found the path to 
the i386 `ld-2.24.so` file by looking at https://packages.debian.org/stretch/i386/libc6/filelist

Add support for Debian 9.

---

src/main/routing/shd-topology.c

Addresses issue #358.
Testing this on a very large complete topology and the same topology after removing one edge, it no longer hangs. It also returns the correct answer. It just takes the usual ~15 minutes to load the darn thing. Verification of completeness is on the order of 30 seconds.
The idea is to count edges at every vertex. I think this works ... as long as you never have more than one edge between a pair of vertices.

Check topology completeness by counting edges at all vertices.

---

src/external/elf-loader/CMakeLists.txt
src/external/elf-loader/extract-system-config.py
src/external/elf-loader/glibc.c
src/external/elf-loader/stage2.c
src/external/elf-loader/test/CMakeLists.txt
src/external/elf-loader/vdl-tls.c
src/external/elf-loader/x86_64/stage0.S
src/test/tcp/shd-test-tcp.c

The most important of the commits in the long run is 2598799232f0e0e143169b3597d2cc1b20b23a77 because the underlying feature still needs implementing (the stub code it adds works for now though).
The other major commit is e5d9b95fa635efc46288e7640b07501a55fcc6c2 which I think does a pretty good job at making future changes to this ABI easy to fix.
fixes #350 
Tested on Ubuntu 16.04, Ubuntu 17.10, and a Solus VM.

support glibc 2.25/2.26, Ubuntu 17.10, and Solus

---

src/external/elf-loader/vdl-map.c

In d9abe9709b75b92acf5fdf45c494a1027eb26474 I tried to make collisions in a hashmap less frequent by using something more unique than the filename. It looks like I forgot to actually make use of this name though.

reduce collisions in readonly-cache map

---

src/external/elf-loader/vdl-tls.c

This fixes the failing tests on Centos7 with -O3. See the commit message for a full writeup on what exactly this is really fixing, and how it still technically isn't the "right thing". The tests were failing when compiled with -O3 because they started aligning their TLS allocations to 0x10 bytes instead of 0x04, which made it use just enough extra memory to interfere with the parts of glibc's static TLS that are actually used every time.

mark the main executable as using static TLS

---

src/external/elf-loader/CMakeLists.txt

We can't use mmx or sse registers in ldso, because we don't push them to the
stack when doing a PLT lookup. They're fine in the dynamic loader (libvdl)
though, because those are just relatively normal function calls. It's possible
SSE instructions are enough of a performance advantage to make it worth it to
move those registers onto the stack when doing the PLT lookup, but it's a non-
trivial operation, because PUSH doesn't work on those registers. Knowing which
is better would require some benchmarking, which might be worth looking into
eventually, since PLT lookups are fairly frequent.
fixes #366

disable mmx and sse in elf-loader

---

src/main/routing/shd-topology.c

Consider an undirected graph. Consider a vertex with an edge that begins and
ends at itself. That edge counts as two outgoing edges from that vertex.
The function that determines whether or not a topology is complete counts
outgoing edges from each vertex and makes sure it is at least as large as the
number of vertexes. These "self-loop" edges cause the number of edges to be
inflated by one. Thus, tiny topologies where the number of vertexes is close
to one were sometimes determined to be complete when they actually weren't.
This commit subtracts one from the outgoing edge count for vertexes in an
undirected graph if a self-loop is present.
Fixes #389

Fix topology completeness function

---

src/external/elf-loader/test/CMakeLists.txt
src/external/elf-loader/test/registers.sh

The first commit adds a new test for any registers we don't take care of in elf-loader, to prevent any future repeats of #366/#388.
The second commit removes test26 again, until #371 is fixed.
edit: change wording so PR doesn't close any bugs

updates to elf-loader tests

---

setup
src/external/elf-loader/CMakeLists.txt
src/external/elf-loader/internal-tests.cc
src/external/elf-loader/stage1.c
src/external/elf-loader/stage2.c
src/external/elf-loader/vdl-alloc.c
src/external/elf-loader/vdl-alloc.h
src/external/elf-loader/vdl-dl.c
src/external/elf-loader/vdl-hashmap.c
src/external/elf-loader/vdl-linkmap.c
src/external/elf-loader/vdl-linkmap.h
src/external/elf-loader/vdl-list.c
src/external/elf-loader/vdl-list.h
src/external/elf-loader/vdl-sort.c
src/external/elf-loader/vdl-tls.c
src/external/elf-loader/vdl-unmap.c
src/external/elf-loader/vdl.h

These commits
- fix some bugs in elf-loader for supporting valgrind
- adds a setup script option for building elf-loader with support for valgrind on elf-loader (Shadow doesn't need this option for valgrind support, unless you want to look at elf-loader's allocations too)
- fixes some memory leaks in elf-loader
This makes valgrind mostly work. It can be a bit rough around the edges in some places, especially as it relates to threads and shutting down, but is good enough for basic profiling.

elf-loader valgrind support

---

src/main/core/shd-master.c
src/main/core/shd-slave.c
src/main/core/shd-slave.h
src/main/core/support/shd-configuration.c
src/main/core/support/shd-configuration.h
src/main/host/shd-host.c
src/main/host/shd-host.h
src/main/host/shd-process.c
src/main/host/shd-process.h
src/test/dynlink/manual-test/plugin.c
src/test/dynlink/manual-test/test.c
src/test/dynlink/shd-test-dynlink-plugin.c
src/test/dynlink/shd-test-dynlink.c

I am researching using Shadow to simulate blockchain networks and wanted to try and see if I could get it to run a Rust executable.  It turns out that the Rust compiler doesn't allow the creation of a C callable dynamic linked library with the "main" symbol exported.  To get around this, I modified Shadow to add a "startsymbol" attribute to the plugin tags in the config.  If it isn't specified, it defaults to "main" so the existing behavior is preserved.  I also modified a few tests to verify it works.  I think this may also be useful for other situations also.

add support for specifying the plugin start symbol in the config

---

src/external/elf-loader/gdb.c
src/external/elf-loader/stage1.c
src/external/elf-loader/stage2.c
src/external/elf-loader/test/CMakeLists.txt
src/external/elf-loader/test/output/test29.ref
src/external/elf-loader/test/test29.c
src/external/elf-loader/vdl-dl.c
src/external/elf-loader/vdl-dl.h
src/external/elf-loader/vdl-file.h
src/external/elf-loader/vdl-hashmap.c
src/external/elf-loader/vdl-linkmap.c
src/external/elf-loader/vdl-linkmap.h
src/external/elf-loader/vdl-list.c
src/external/elf-loader/vdl-list.h
src/external/elf-loader/vdl-lookup.c
src/external/elf-loader/vdl-map.c
src/external/elf-loader/vdl-tls.c
src/external/elf-loader/vdl.h

This partially fixes the problems in #381 by using the second option there. That is, with 
1aef9b0 in particular, elf-loader doesn't add dynamically loaded objects to the linkmap, preventing gdb from finding them. For shadow, this means that the performance of running in gdb or attaching gdb to a running experiment will be considerably faster, with the drawback that no debug symbols will be loaded for plugins and their dependencies. While there isn't a full solution in place (that would require patching gdb), there are some helper functions to address plugin debug symbols:
- `vdl_linkmap_abi_update()` will add all objects to the linkmap and notify gdb, at what is probably only slightly faster than what it was before. This is useful for smaller experiments, or experiments where you're …

gdb performance improvements

---

src/main/host/shd-process-undefined.h
src/main/host/shd-process.c
src/main/host/shd-process.h
src/preload/shd-preload-defs.h

The first commit makes a few minor bug fixes to my previous implementation of pthread_getattr_np.
The second commit adds all extern functions found in my system's /usr/include/pthread.h which weren't already implemented in Shadow, in the form of using a macro to generate a function definition for informing the user it isn't implemented. This should make identifying when these functions are used by plugins easier.

unsupported pthread functions

---

src/external/elf-loader/extract-system-config.py

I'm moving to using Shadow on my workstation, which is running Debian testing. I don't know if it makes sense to include this patch into Shadow itself as the ld version will probably change before Debian testing becomes the next stable.
Maybe it would make more sense to start matching on a glob here instead of matching on specific versions for the different distributions?

Add support for Debian testing

---

src/external/elf-loader/extract-system-config.py
src/external/elf-loader/vdl-tls.c

The first commit 17817c1  switches to using regex to find ld.so debug files, which fixes #408 (I opted for regex over globs to be a bit stricter in what we match).
The second commit b40578a fixes what should be a minor performance problem (some code we inherited used memcpy when it could have just used assignment), but on closer inspection might be a non-trivial boost since it occurs in some of the most frequently used elf-loader code (outside of dynamic loading), is code that is often called from within a global lock, and this should allow for more significant compiler optimizations. I would have to do some measurements to say for sure though, and I don't think it will be *that* significant.
I was going to add a commit to fix a very minor memory leak as well, but since it involves …

minor elf-loader changes

---

src/test/CMakeLists.txt
src/test/leakcheck.sh

Some distros, e.g. Ubuntu, don't put crucial executables like bash in /usr/bin.

use /usr/bin/env in scripts

---

src/external/elf-loader/vdl-list.c
src/external/elf-loader/vdl-list.h
src/external/elf-loader/vdl-lookup.c

This adds an operation which is linear in the number of files symbols are resolved from by a file, but my experiments with shadow-tor show this number never gets very large (<10 once the experiment is up and running).

fix minor memory leak in elf-loader garbage collector

---

src/external/elf-loader/extract-system-config.py
src/external/elf-loader/vdl-dl.c
src/external/elf-loader/vdl-hashmap.c
src/external/elf-loader/vdl-list.c
src/external/elf-loader/vdl-tls.c
src/main/core/scheduler/shd-scheduler-policy-host-steal.c
src/main/core/scheduler/shd-scheduler-policy.h
src/main/core/scheduler/shd-scheduler.c
src/main/host/shd-process.c

While working on getting shadow running on the new machine in CrySP, I've encountered various bugs. The most significant of these is that a typo was preventing the work-stealing scheduler from ever being used (when I was originally implementing/measuring it, my local shadow copy implemented it over the hostsingle policy). This also means the TLS swapping code hasn't been used with recent changes. I've done some pretty thorough testing on an Ubuntu 16.04 machine, as well as some testing on Ubuntu 17.10 and a Solus VM, so hopefully it doesn't introduce any new bugs, but you might want to test it before merging too.

various bug fixes

---

src/external/CMakeLists.txt
src/external/elf-loader/vdl-log.c
src/external/elf-loader/vdl-log.h
src/main/host/shd-process.c

This makes some minor improvements to a few points of logging:
- elf-loader gets a lock on its logging function so that the output isn't a jumbled mess, and moves some of the logging into a macro so compiler optimizations can be more aggressive and branch prediction more accurate
- rpth gets a fix to its debug option in the configure script, so that non-debug builds don't include the debug log macros
- shadow gets the log message in _process_updateErrnoLocation moved from message to info, because
```
$ tail shadow.log -n 10000 | grep -vc "_process_updateErrnoLocation"
1876
```
This is a noticeable improvement on performance for tiny experiments (~30%), but probably insignificant for medium to large experiments (outside of file sizes).

logging improvements

---

src/external/elf-loader/stage1.c
src/external/elf-loader/vdl-dl.c
src/external/elf-loader/vdl-gc.c
src/external/elf-loader/vdl-map.c
src/external/elf-loader/vdl-map.h
src/external/elf-loader/vdl.h

glibc or gcc has started inserting code that tests if an optional library is available by calling dlopen on it. We've been treating failing to find a requested library as a relatively untested failure case, which manifested as segfaults when doing this a lot in parallel.
This adds two commits to address this new use: abd3e16 fixes the underlying correctness bug by adding a futex to garbage collection, while c199c32 avoids needing to garbage collect at all when this particular case happens (since it will now apparently be very frequent).
Fixes #423

handle soft dl(m)open failures gracefully

---

src/main/host/shd-process.c

I don't have a consistent test case to say for sure, but I *think* this fixes #421

avoid unloading plugins at process stop

---

src/plugin/shadow-plugin-tgen/CMakeLists.txt
src/plugin/shadow-plugin-tgen/shd-tgen-action.c
src/plugin/shadow-plugin-tgen/shd-tgen-config.c
src/plugin/shadow-plugin-tgen/shd-tgen-config.h
src/plugin/shadow-plugin-tgen/shd-tgen-driver.c
src/plugin/shadow-plugin-tgen/shd-tgen-main.c
src/plugin/shadow-plugin-tgen/shd-tgen-server.c
src/plugin/shadow-plugin-tgen/shd-tgen-transfer.c
src/plugin/shadow-plugin-tgen/shd-tgen-transport.c
src/plugin/shadow-plugin-tgen/shd-tgen.h

These commits add some instance-specific configuration options that are useful in some non-Shadow contexts -- most notably, in NetMirage.
The first commit allows tgen to bind to a specific IP, set via the `TGENIP` environment variable.
The second commit allows tgen to use a specific hostname, set via the `TGENHOSTNAME` environment variable, and also creates new files `shd-tgen-config.c/h`, with the intention that they will be used for these and all future (non-graphml) configurations of tgen. The idea being, if at some point we switch environment variables to command line options, or move parameters from the config file to the invocation, there's an obvious place to do it.
I can change the names of any of these files or environment variables to something else, of course.

Configure tgen's runtime behavior

---

src/main/routing/shd-topology.c

This fixes a segfault in some very small networks, where nothing is put in this cache so it's never created.

check if pathCache exists before logging it

---

src/main/host/shd-network-interface.c
src/main/utility/shd-pcap-writer.c
src/main/utility/shd-pcap-writer.h

This doesn't fix Wireshark assuming the sequence numbers are bytes (instead of packet counts), but it at least makes the numbers correct.
For reference, IIRC Shadow uses full ints for window size, but this code casts to 16 bits because the pcap format assumes these are actual TCP packets. There may be a way to fake window scaling into this code, but it would be a little tricky and not actually reflective of the exact window size anyway.

fix endianness issues when creating pcaps

---

src/main/host/descriptor/shd-tcp-retransmit-tally.cc

The method has a reference to its class as return type, but does not actually
have a return statement. This has resulted in null-dereferences and segfaults
on Kali-Linux. This fix appears to resolve #699. The number of failed tests
has gone from 18 to 20 to only 1 and the functional tests exits successfully.

Add return statement to operator overload

---

src/main/host/descriptor/shd-tcp-retransmit-tally.cc
src/main/host/descriptor/shd-tcp-retransmit-tally.h
src/main/host/descriptor/shd-tcp.c

Before this commit, the TCP retransmit tally was being constructed as follows--
1. We mallocate sizeof(RetransmitTally)
2. We pass a pointer of the allocated memory to the init function
3. The init function zeroes the memory, constructs a new
RetransmitTally on the stack, and then copy-assigns the
stack-allocated RT to the zero'ed one of the heap.
I believe this behavior was causing issues for certain compiler
(probably due to undefined behavior, or maybe because the
copy-assignment operator wasn't implemented correctly).
The new init code takes a **RetransmitTally and will allocate and
initialize one directly using operator new.
Patch was tested and does not cause any additional test cases to fail.

Fix to TCP RetransmitTally initialization

---

.github/workflows/lint_python.yml

Like #696 but running on GitHub's builtin https://github.com/shadow/shadow/actions
Let's use flake8 to find bug before our users do...
https://flake8.pycqa.org/en/latest/user/error-codes.html
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script halting/crashing on the …

Add automated testing with GitHub Actions:

---

src/external/elf-loader/test/run-valgrind.py

`e` is an undefined name in this context so a NameError will always be raised instead of the actual exception.
Discovered by #704

Undefined name: 'e' --> Exception

---

src/test/shd-test-common.c
src/test/shd-test-common.h
src/test/shutdown/shd-test-shutdown.c
src/test/sockbuf/shd-test-sockbuf.c

This fixes the bug where the shutdown test fails if run multiple
times, and generally prevents the possibility of tests failing
in the case that a hard-coded port number happens to already
be in use.

Use dynamic port assignment for server ports in tests.

---

src/external/elf-loader/dl.h
src/main/core/shd-main.c

Linux's `dlinfo` is annotated with `nonnull`, but the custom
vdl loader has an extension RTLD_DI_STATIC_TLS_SIZE, for which
a null handle is allowed. So, suppress the warning just for
those call sites by using a non-null (but likely invalid) address
RTLD_DI_STATIC_TLS_SIZE_DOESNT_REQUIRE_HANDLE.
This is one step toward unblocking compiling with -Werror (GH-711)

suppress NULL argument warning for dlinfo with RTLD_DI_STATIC_TLS_SIZE

---

src/preload/shd-preload-defs.h

Resolves a warning when compiling with clang (GH-711).
As far as I can tell this was a real bug, and getpid callers
would've just been getting some arbitrary value from the stack.
It looks like current tests would have passed as long as it
was a *consistent* arbitrary value.
Considered adding a regression test that does something
with the returned pid, but it's not clear
how shadow does or ought to handle a process that does much in the
way of process manipulation. Other functions that do process
manipulation (e.g. kill) aren't overridden at all.

return pid from getpid and getppid

---

docs/1.1-Shadow.md

In particular noticed this was needed on Fedora 31.
Also split dependency lists across lines and sort.

Add yum-utils dependency for Fedora

---

cmake/ShadowTools.cmake
src/external/elf-loader/test/CMakeLists.txt

* Adds a macro add_ldflags analagous to add_cflags.
* Uses that macro to fix a "unused-command-line-argument" warning in
clang, where link flags were being passed to compile steps.
Progress on GH-711.

Pass link flags only to link steps.

---

.clang-format

This specifies the formatting preferences for the clang-format tool,
which should pick up this configuration automatically.  I started with
clang-format's defaults and made a few tweaks in accordance with the
preferences observed in the existing code.
I don't plan or recommend mass reformatting, but this is useful
for keeping modified code tidy and formatted consistently.
A mass reformat might make sense down the line once we've had time
to get comfortable with the options, and don't have any large
pending changes (since it'd make merging a huge headache).

Add a .clang-format configuration

---

.bumpversion.cfg
CMakeLists.txt

This commit was created with:
```
bumpversion --tag --commit minor
```
Will also push the corresponding tag after this is merged.

Bump version: 1.13.2 → 1.14.0

---

.github/workflows/build_shadow.yml

CI has been failing because one of the packages it's trying to fetch is no longer available on the server, so it gets a 404.
This change updates the package cache before trying to install dependencies, which seems to fix it.
That does introduce an unfortunate possibility of things breaking out from under us when dependencies introduce breaking changes, but that seems like a lesser problem than packages completely going away out from under us.
If and when we get Shadow working under Docker again we can create a custom image with our dependencies already installed and run everything on that.

Fix CI's package management

---

.github/workflows/build_shadow.yml
src/external/elf-loader/CMakeLists.txt

Just came across the --werror --debug build getting broken in res/phantom. While that particular breakage was fairly innocuous, in general it's a good idea to test the debug build too.

Build and test debug mode too

---

src/test/file/CMakeLists.txt
src/test/file/shd-test-file.c

Enables individual file tests to be turned on and off independently, so that we can enable them incrementally in the phantom branch.
Migrates to glib's test framework so that we can filter which tests run from the command-line. This also makes the test code more succinct and give better failure reporting.
Modifies subtests to be independent of each-other; i.e. not depend on earlier tests to have created or modified a test file.

File glibtest

---

setup
src/test/epoll/CMakeLists.txt

Timeouts should help prevent a misbehaving test from running forever, and helps prevent
large unexpected regressions such as #756.
Verbose output is helpful for debugging, especially in CI without having to rerun again locally.

Add test timeouts and verbose output

---

docs/3.1-Shadow-Config.md

Remove references to "clusters". A cluster is now a "node in the topology".
Don't refer to hosts as nodes, since this could cause them to be confused with topology nodes.
Use "node" instead of "vertice" and "edge" instead of "link", since those are the concrete terms used in the topology.
Progress on #776

Clarify 'node', 'cluster', 'edge' terminology

---

.github/workflows/git.yml

"fixup!" and "squash!" commits are generally created using the `--fixup`
and `--squash` flags to `git commit`, and are intended to be squashed
into another commit before merging, generally using the `--autosquash`
flag with `git rebase`. They are a useful alternative to
amending/rebasing commits immediately, especially for a pull request
that's in the middle of review.
Without a check like this one though, it's easy to forget to `git rebase
--autosquash` them away before merging. e.g.
3787852.

Block fixup commits

---

.github/workflows/build_shadow.yml
setup

Some other minor cleanup while in here:
* Bump upload-artifact action version
* Have setup script return failure when it aborts

Save shadow logs on CI failure

---

src/main/host/process.c

Previously the fallback ternary was duplicated in several places, and
missing from another.

Move fallback to default start symbol into helper

---

.github/workflows/build_shadow.yml
setup

We unfortunately have some difficult to debug, nondeterministic failures (e.g. #798). Eventually it'd be good to fix these, but I don't think it makes sense to block other work on it at the moment. Right now the only recourse is to manually click the "rerun all workflows" button, which reruns *all* the tests in *all* configurations, including the slow shadow-plugin-tor-ci.
This PR adds an option to ./setup to rerun tests that failed in the last run, and modifies the CI script to try rerunning failing tests once before failing the CI workflow.

Rerun failed

---

src/main/core/logger/shadow_logger.c
src/support/logger/CMakeLists.txt
src/support/logger/logger.c
src/support/logger/logger.h
src/test/bind/CMakeLists.txt
src/test/bind/test_bind.c

In the default logger:
* Log elapsed time
* Log the source file basename instead of the whole path
* Log using g_print (as shadow logger does) ~directly to stderr~ instead of to glib's logger
* In debug builds, abort the program on errors.
As I was testing, dealing with glib's logger underneath was a bit of a headache. While it has some nice features, the defaults aren't want we want. Easier to just bypass it for now.
Ported bind test to use our logger macros instead of glib's to help test and to get the additional fields (code location, time, etc).

Logger improvements

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

We recently added new issue labels, and now our issue creation templates assign labels that no longer exist. This fixes the label assignment to use the new labels and makes the issue type description consistent with the label types.

Update issue template with new issue labels

---

.github/workflows/build_shadow.yml
.github/workflows/lint_python.yml

Re-enables CI tests for ubuntu:20.04, debian:10-slim, fedora:32, and centos:8. The 'findutils' package is for our cmake rust unit tests which require the 'find' tool. This PR also stops running linting tests with Python 2.7.
The tests do not currently complete on ubuntu:16.04 (shadow/shadow#864) or when using clang (shadow/shadow#865).

Re-enable some CI tests for other distros

---

.github/workflows/build_shadow.yml
CMakeLists.txt
src/main/CMakeLists.txt
src/test/CMakeLists.txt

CMake >= 3.2 is available by default on all supported platforms except for CentOS 7, which requires the `cmake3` package from EPEL and for `cmake` to be linked to `cmake` using a method such as https://stackoverflow.com/a/48842999.
> I'm a bit worried about requiring CMake v3.2 because it might not be available in all of our supported distros. I see that you have a way to make it work in CentOS 7, but I don't know if it's easy to get that working all older distros.
All of the other supported distros support CMake 3.2 (for example Ubuntu 16.04 is 3.5, Fedora 32 is 3.17, CentOS 8 is 3.11, and Debian 10 is 3.13). CentOS 7 is the oldest distro that we support, which uses CMake 2.8.
> It would require an extra step that we would need to ask users to perform during setup.
I agree this isn't …

Upgrade to CMake 3.2

---

CMakeLists.txt
setup
src/main/CMakeLists.txt
src/test/CMakeLists.txt

Upgrading to CMake 3 broke the Rust code coverage reporting, so this PR corrects that.
Closes #879.

Fix Rust coverage

---

.github/workflows/run_tests.yml
codecov.yml

~As our coverage was being run in `shadow/src`, codecov didn't know how to match the files in the repository with the files in the coverage report. This PR tells codecov how to link them.~
Set the Codecov upload action to not fail the CI test if the upload fails.
Also set the dev branch as the main branch, but I don't think this will activate until we add it to the master branch as well.

Don't fail CI tests on Codecov upload failure

---

src/test/Cargo.toml
src/test/socket/CMakeLists.txt
src/test/socket/bind/CMakeLists.txt
src/test/socket/bind/bind.shadow.config.xml
src/test/socket/bind/test_bind.rs

These tests do not include the implicit bind tests of `src/test/bind/test_bind.c` since they do not test the `bind()` call. Instead they should later be implemented in a different test directory.

Added bind() tests

---

src/test/sleep/test_sleep.rs

The test has failed twice on me now for going over the 10 ms threshold, so may as well bump this up slightly.

Increased tolerance on sleep test

---

.github/workflows/lint.yml

Added a check to make sure the C bindings for the Rust code in `src/main/bindings.h` are up to date and were created with the correct configuration file.

Check generated C bindings in CI environment

---

docs/1.1-Shadow.md

All cases are not covered, for example, `yum install cargo` is not handled on centos7 but works on centos8. I think it is sufficient to understand what the user has to install.

Update installing dependencies in doc

---

src/main/utility/interval_map.rs
src/main/utility/mod.rs

This is intended to help keep track of plugins' memory mappings. Nothing
uses it yet, but since it's fairly general it probably makes sense to
split off and merge separately.

Adds IntervalMap: map from a range to a value.

---

src/main/core/scheduler/scheduler.c

This seems like a bug to me, but the existing behaviour should be fine as the workers just won't be used.

Fix default scheduler policy

---

src/main/utility/proc_maps.rs

Some fixes made after starting to use the proc maps parser:
* Make the Mapping fields public
* Parse the undocumented '(deleted)' specifier

Proc maps parser updates

---

.dockerignore
ci/container_scripts/install_deps.sh
ci/run.sh
docs/ci.md

Use the '-i' option to `ci/run.sh` to build the images. You may only want to build the images on the first invocation, or if the Shadow code significantly changes.
@sporksmith Is this what you had in mind for incremental builds?

Incremental Docker builds

---

src/main/host/syscall_types.rs
src/main/host/thread.rs

This will make it easier to later have Rust-native Thread implementations rather than wrapping the C interface.
Wraps some additional Thread functionality, and provides default-implementation in the Thread trait, e.g. to provide type-safe wrappers for specific syscalls.

Split Rust Thread interface (trait) from implementation

---

docs/1.1-Shadow.md

Note: I don't know if there is a reason that matters for having it be its own apt-get command. I suspect there isn't one.
I neglected to install libc-dbg because I didn't want the python stuff, but didn't see the libc-dbg line just before it.

Move libc-dbg to preceeding apt-get command

---

CMakeLists.txt
setup
src/main/CMakeLists.txt
src/shim/CMakeLists.txt

Previously when running shadow from the 'build' directory (for example with './setup.py test'), shadow would use the installed shim rather than the most-recently built shim in 'build/src/shim'. This can lead to confusion if the shim was updated, but the tests are using the old installed shim. This also means that shadow must be installed before it can be tested.
This commit modifies how the rpath is generated and causes shadow to use a different rpath after it is installed.
Before:
```
$ ./setup build --clean --debug --test --library /tmp
$ ./setup install
$ readelf -d build/src/main/shadow | grep 'R.*PATH'
<snip> (RUNPATH)            Library runpath: [/home/steve/.shadow/lib:/home/steve/.shadow/lib:/tmp:]
$ readelf -d ~/.shadow/bin/shadow | grep 'R.*PATH'
<snip> (RUNPATH) …
```

When running from 'build/', don't use the installed shim

---

src/main/cbindings/wrapper.rs
src/main/core/scheduler/scheduler_policy_host_steal.c
src/main/host/host.c
src/main/host/host.h
src/main/host/process.c
src/main/host/process.h
src/main/host/syscall/unistd.c
src/main/host/thread.c
src/main/host/thread.h
src/main/host/thread_preload.c
src/main/host/thread_protected.h
src/main/host/thread_ptrace.c
src/main/host/thread_ptrace.h
src/shim/shim_logger.c
src/support/logger/logger.c
src/support/logger/logger.h
src/test/phold/CMakeLists.txt

When using the work stealing scheduling policy, it is possible
that hosts are migrated between worker threads depending on the
plugin workloads. When migrating a host to a new worker thread,
the previous worker thread that was running it will need to detach
its ptrace attachments so that the new thread can attach and
continue tracing the plugin.
This commit adds a hook that detaches all ptrace attachments at
the end of each round of execution; in the following round, it
becomes possible again that the host could be stolen by another
worker. Also, before resuming a a ptrace session, the worker
checks and does a ptrace attach first if needed.
refs shadow/shadow#909

Support multiple worker threads with work stealing

---

src/main/host/thread_preload.c
src/shim/preload_syscalls.c
src/shim/shim.c
src/support/logger/logger.c
src/test/bind/CMakeLists.txt
src/test/bind/test_bind.c
src/test/random/CMakeLists.txt
src/test/random/test_random.c
src/test/test_common.c
src/test/test_common.h
src/test/unistd/CMakeLists.txt
src/test/unistd/test_unistd.c

* Don't read from /dev/random in native tests
* Add recursion guard to default logger, fixing potential deadlock when global constructors call getrandom (or other wrapped functions) before the shim global constructor has run.
* Enable getrandom wrapper and threadpreload test.
* Change threadpreload to use fork instead of vfork now that it no longer uses execve right away.
* Add a test helper `running_in_shadow()`

Fix getrandom-related issues

---

ci/container_scripts/build_and_install.sh
ci/container_scripts/install_extra_deps.sh

Until #941 is resolved, this PR uses `nightly-2020-08-20` for coverage tests.

Using older Rust nightly version for coverage tests

---

.github/workflows/run_tests.yml
ci/container_scripts/build_and_install.sh
ci/container_scripts/install_deps.sh
ci/container_scripts/install_extra_deps.sh

Ubuntu 20.10 is apparently planning on making LLVM 11 the default in September, just after the official LLVM 11 release date. So we should be able to simplify these changes when this happens.
https://discourse.ubuntu.com/t/groovy-gorilla-release-schedule/15531

Changed coverage CI tests to use clang 11

---

src/main/bindings/c/bindings.h
src/main/host/memory_manager.rs
src/main/host/process.c
src/main/host/process.h
src/main/host/syscall/epoll.c
src/main/host/syscall/fcntl.c
src/main/host/syscall/file.c
src/main/host/syscall/fileat.c
src/main/host/syscall/ioctl.c
src/main/host/syscall/mman.c
src/main/host/syscall/process.c
src/main/host/syscall/protected.h
src/main/host/syscall/random.c
src/main/host/syscall/socket.c
src/main/host/syscall/time.c
src/main/host/syscall/timerfd.c
src/main/host/syscall/uio.c
src/main/host/syscall/unistd.c
src/main/host/syscall_handler.c

Progress on #826 
Move MemoryManager from SyscallHandler to Process so that it can be shared amongst threads.
Also:
* Instead of setting a flag in MemoryManager to re-initialize itself after an exec, just destroy the whole thing. The SysCallHandler will re-create it lazily on the next syscall.
* Unlink shared memory file as soon as we're done opening it, reducing the risk of leaving stale files around after a crash.

Move MemoryManager to Process

---

src/main/host/process.c
src/main/host/thread_preload.c
src/main/host/thread_ptrace.c
src/main/utility/utility.c
src/main/utility/utility.h

Uses a SIGKILL rather than SIGTERM since we don't want shadow to block waiting for the process, and we do not yet allow the process to shutdown properly.
This PR creates a new file `*.exitcode`, which should contain the exit status of the process.

Save process exit codes

---

src/shim/binary_spinning_sem.cc

IIUC the loop was exiting immediately when it *didn't* hold the lock,
and then ending up blocking the `sem_wait`, and looping unnecessarily
when it *did* hold the lock.
It looks like the condition was inadvertently inverted in https://github.com/shadow/shadow/commit/91367d13955381d8b5e2c5e0f1e2c074ec9969a2
Notably, phold-shadow-preload performance got substantially worse @
91367d13955381d8b5e2c5e0f1e2c074ec9969a2, and this change seems to
recover that performance loss. (With phold-shadow-preload enabled
locally, and run on centos-7 using a recompiled libc).

Invert spinlock loop condition

---

src/shim/preload_syscalls.c
src/shim/shim.c
src/shim/shim.h
src/test/clone/test_clone.c

Previously, we couldn't guarantee that some global constructor might not
call some of our wrapped syscalls before the shim was initialized by its
global constructor.
Our syscall wrapper now ensures that the shim is initialized, using a
pthread_once construct. We still use a global constructor to ensure that
the shim is initialized before calling main.

Ensure that shim is initialized before first wrapped syscall is made.

---

src/test/socket/bind/test_bind.rs
src/test/socket/connect/test_connect.rs
src/test/socket/getsockname/test_getsockname.rs

Should improve the reliability of socket API integration tests on different kernels.

Use valid sockaddr when testing invalid file descriptors

---

src/test/socket/socketpair/CMakeLists.txt
src/test/socket/socketpair/test_socketpair.rs

When I enabled the shadow tests for `socketpair()`, I forgot to check that Shadow actually supported remapping the `socketpair()` system call rather than just calling the native system call. This PR disables the tests in shadow.

Disabled socketpair() tests in shadow

---

src/main/host/thread_ptrace.c
src/test/phold/test_phold.c

When running phold-threaded-shadow-ptrace with more hosts (e.g. 20
instead of the default 10), we'd get errors in threadptrace_doDetach. It
turns out that a host can end up calling detach on a plugin that's
already detached.
Since threadptrace_doDetach was assuming it was starting from an
attached state, things didn't go well.
We now simply silently return if already detached.

Fix ThreadPtrace migration

---

src/main/host/thread_ptrace.c

With 30s of simulation time:
@ dev:
```
./setup build --werror --test && ./setup install && ./setup test -j1 phold
...
Test project /home/jnewsome/projects/shadow/build
Start 27: phold-shadow-ptrace
1/2 Test #27: phold-shadow-ptrace ..............   Passed   11.67 sec
Start 28: phold-threaded-shadow-ptrace
2/2 Test #28: phold-threaded-shadow-ptrace .....   Passed    6.98 sec
```
@ this PR:
```
./setup build --werror --test && ./setup install && ./setup test -j1 phold
...
Test project /home/jnewsome/projects/shadow/build
Start 27: phold-shadow-ptrace
1/2 Test #27: phold-shadow-ptrace ..............   Passed    9.05 sec
Start 28: phold-threaded-shadow-ptrace
2/2 Test #28: phold-threaded-shadow-ptrace .....   Passed    5.53 sec
```

In ThreadPtrace, avoid blocking while waiting for traced thread

---

.github/dependabot.yml

Attempting to add a Dependabot config file for keeping our Rust dependencies up to date.
https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

Added a dependabot config

---

.github/dependabot.yml

I did some testing in another repository, and the dependabot config must be in the main branch.
See also: shadow/shadow#988

[main branch] Added a dependabot config for the dev branch

---

src/main/core/main.c

We don't technically need this at the moment now that we've switched to SIGKILL for child processes, but since the current behaviour might be unexpected in the future, probably best to add this now before I forget about it.

Clear the signal mask at startup

---

.github/workflows/build_shadow.yml
setup
src/external/elf-loader/extract-system-config.py
src/external/elf-loader/get-valgrind-cflags.py
src/external/elf-loader/test/junit_xml_output/__init__.py
src/external/elf-loader/test/run-valgrind.py
src/external/elf-loader/test/testjunit.py

Part of shadow/shadow#422 for the main branch.
When installing Shadow on Ubuntu 18.04 following the [guide](https://github.com/shadow/shadow/tree/master/docs/1.1-Shadow.md) which recommends Python 3, the Python scripts fail due to the `#!/usr/bin/env python` shebang if Python 2 is not installed. This PR forces the scripts to run under Python 3.

Changed script shebangs and CI workflows to use python3

---

.github/workflows/lint.yml
src/main/bindings/c/bindings.h

This fixes the bindings check in our CI. The previous version we'd pinned to has been [yanked](https://crates.io/crates/cbindgen/0.14.6) from crates.io. (Not sure why, but presumably because of some serious bug)

Update cbindgen to 0.15.0

---

ci/container_scripts/test.sh
setup

When debugging locally it's generally easier to look at build/Testing/Temporary/LastTest.log,
instead of trying to scroll through direct terminal output.
--output-on-failure is more useful in the ci, where it would otherwise
be an extra step to download LastTest.log from a GitHub artifact or copy
out of a local Docker container.

Move --output-on-failure from setup to ci

---

src/test/futex/CMakeLists.txt
src/test/futex/test_futex.c

Added some more granular tests for ease of debugging.
Also added tests for FUTEX_WAIT_BITSET and FUTEX_WAKE_BITSET. These aren't implemented in Shadow yet, but it looks like these are used in `sem_wait` and `sem_post`. I'd started to work on these to support handling the resulting futex syscalls in ptrace/preload "hybrid mode", but for now ended up handling it a different way for now (by setting a flag to let Shadow know that the plugin is executing in the shim).

Expand futex tests

---

src/main/shmem/shmem_allocator.c

Explicitly destroying them doesn't have a clear benefit, and introduces
a danger of accidentally using them (e.g. in another global destructor)
after they've been destroyed.
In particular I stumbled across this while developing ptrace/preload
hybrid mode, where other syscalls can continue to be made and handled in
other global destructors.
For more on this topic see
https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables

Don't destroy global shmem objects

---

src/shim/preload_libraries.c
src/shim/preload_syscalls.c
src/test/tcp/CMakeLists.txt

These changes are enough to make the tcp-shadow-preload tests work.

Support TCP tests in preload mode

---

src/test/epoll/CMakeLists.txt

The epoll preload tests were set to only run under the "ilibc" configuration, but the patched libc wasn't actually being used (`LD_LIBRARY_PATH` wasn't set in the shadow config file). The epoll preload tests seem to work on all CI platforms without the patched libc, so the "ilibc" requirement has been removed.

Enable epoll preload tests on all platforms

---

docs/1.1-Shadow.md
docs/1.2-Shadow-with-Docker.md

Removed the "pre-built" images section from the Docker instructions since it has a very old version of Shadow. Also added a warning that the "build your own" Docker instructions don't work.
Added a recommendation to use Ubuntu 18.04 since Shadow doesn't build in Fedora 32 or Ubuntu 20.04.
And a couple other small changes.

Minor documentation improvements (main branch)

---

src/main/host/syscall/fcntl.c
src/main/host/syscall/fcntl.h
src/main/host/syscall_handler.c

Redirect `fcntl64` to the `fcntl` handler.

Syscall handler for fcntl64

---

src/main/host/descriptor/udp.c

The UDP socket stats were not being set correctly when receiving packets, so fixed that in one commit. Also, the stats were being set twice, once in the socket code (`socket_addToOutputBuffer()` and `socket_removeFromOutputBuffer()`), and then in the UDP code. There's no reason to set it twice, so the UDP socket stat updating was removed in another commit.

Fix bug in UDP socket stats

---

src/main/bindings/rust/wrapper.rs
src/main/host/process.c
src/main/host/thread.c
src/main/host/thread.h
src/test/clone/CMakeLists.txt
src/test/clone/test_clone.c
src/test/pthreads/CMakeLists.txt
src/test/pthreads/test_pthreads.c

Implements clear-and-wake on `set_child_tid`, per set_tid_address(2)
This also appears to be sufficient for `pthread_join` to work, so re-enabled corresponding tests.
This does *not* yet implement robust lists as per `get_robust_list(2)`. One could imagine alternatively implementing `pthread_join` using that mechanism, but it appears that our supported platforms do not.
Progress on #826

Pthread join

---

docs/2-Getting-Started-Tutorial.md
docs/5-Developer-Guide.md
src/tools/convert.py
src/tools/convert_multi_app.py
src/tools/generate_example_config.py
src/tools/parse-shadow.py
src/tools/plot-shadow.py
src/tools/strip_log_for_compare.py

Update last shadow part of the https://github.com/shadow/shadow/issues/422
There are still some python2 references in the Docker and Vagrant doc. What should I do with there old docs ?
https://github.com/shadow/shadow/blob/master/docs/1.2-Shadow-with-Docker.md
https://github.com/shadow/shadow/blob/master/docs/1.3-Shadow-with-Vagrant.md

Replace all references to python 2 in the documentation with python 3 

---

src/main/host/thread_preload.c
src/shim/shim.c

Changes thread_preload.c to use `vfork()` instead of `fork()` during
process creation. This change has a significant impact on experiment
performance with many (> 1000) processes to manage.
Initialization runtime is reduced by a large factor.
`prctl(PR_SET_PDEATHSIG, SIGKILL)` and `getppid()` have been moved to
the shim in `_shim_load()`.
n.b. I believe this change does not affect ptrace mode. The `prctl` call
may be duplicated, but shouldn't hurt for now.

Prefer vfork to fork

---

src/main/core/main.c
src/main/host/thread.c
src/main/host/thread_protected.h

Adds CPU pinning to the development branch.
On calls to `thread_run` and`thread_resume`, the plugin's CPU affinity is set to the worker's
current affinity when affinity mode is enabled.

Adds CPU pinning to the development branch.

---

src/main/host/descriptor/mod.rs

Small change to fix a warning that occurs in new Rust versions.

Minor fix for Rust compiler warning

---

src/test/phold/CMakeLists.txt

This PR reduces *worst case* runtime of the phold tests.
Here is some unscientific results:
Debug mode, CPU pinning off:
Release mode, CPU pinning off:
Debug mode, CPU pinning on:
Release mode, CPU pinning on:
- pinning off is beneficial when you are not running with multiple workers. without pinning, a plugin can “steal” an extra CPU that’s available on the machine
- when debugging is on, there is a lot more work being done on my machine and it’s probably overloaded running all 4 tests in parallel, so in that case pinning helps
- it seems like overall we will win when testing by enabling pinning, because the major decrease in debug mode runtime is worth the minor increase in release mode runtime

Pin CPUs in phold test for efficiency

---

src/test/CMakeLists.txt
src/test/bind/CMakeLists.txt
src/test/bind/bind-shadow.yaml

This will (i) make it easier to define new tests concisely, (ii) make all of the test cases actually fail when they should, and (iii) make the tests more consistent.

Define macros for consistent & concise test defs

---

src/main/host/descriptor/pipe.rs
src/main/utility/byte_queue.rs

Fixes two different bugs, one where the byte queue length was being calculated incorrectly causing `write()` on a pipe to block, and another where the readable/writable status flags were not being unset.
Closes shadow/shadow#1120.

Fix Rust pipe descriptor

---

.github/workflows/run_tests.yml

Coverage tests are currently [failing in the CI](https://github.com/shadow/shadow/issues/1152), so this PR disables them until we figure out how to fix them.

Disabled coverage tests in CI

---

.github/workflows/ci_maintenance.yaml
.github/workflows/run_tests.yml
ci/container_scripts/build_and_install.sh
ci/container_scripts/install_extra_deps.sh

This PR sets a hard-coded Rust nightly version for building the coverage data, re-enables the coverage tests, and adds a CI workflow to create a new issue every 4 months reminding us to update the versions of tools that we use in the CI (currently Rust nightly, bindgen, and cbindgen).

Re-enable the coverage tests

---

setup

Still use a minimum of 4 jobs, but use more if we have more CPU cores.
This could potentially make race conditions in the tests more common since some non-Shadow tests still bind to the same ports, but those are bugs in the tests that we can fix.

Use number of system CPU cores for number of test jobs

---

src/test/file/CMakeLists.txt
src/test/memory/CMakeLists.txt
src/test/poll/CMakeLists.txt
src/test/poll/poll.yaml
src/test/poll/test_poll.rs

Hopefully this fixes the test errors we've had in the CI.
This PR also sets different seeds for the 'file' and 'memory' tests since they use `mkstemp`.

Use a unique file name in poll tests

---

codecov.yml

Disabling the codecov status checks, which often show as failing tests whenever the code coverage decreases.
In the future we may want to re-enable these, but with a threshold of 0 so that it still shows as passing and we get the [coverage annotations](https://about.codecov.io/blog/announcing-line-by-line-coverage-via-github-checks/). We may also want to update the Shadow code to use `GCOV_EXCL_LINE` and similar flags to prevent gcov from complaining about unused error conditions.

Disable the codecov status checks

---

src/main/host/process.c
src/main/host/syscall/file.c
src/main/host/syscall/mman.c
src/main/host/syscall_handler.c

Add option to disable the MemoryManager, and fix some bugs in the fallback memory-access paths.
* Fix buffer size requested in getdents and getdents64
* Add missing memory-flush after writing the `clear_child_tid` pointer

Add option to disable the MemoryManager

---

src/main/bindings/c/bindings.h
src/main/host/descriptor/mod.rs
src/main/host/descriptor/pipe.rs
src/main/host/syscall/unistd.rs
src/main/host/syscall_handler.c
src/main/utility/byte_queue.rs

Rearranged the Rust syscall helper code, added Rust wrappers for the `pread64` and `pwrite64` syscalls, added the `Debug` trait to some Rust types, and set the `CLOSED` (and remove the `ACTIVE`) flag when the pipe is closed.

Improve rust syscalls/descriptors

---

src/main/host/descriptor/descriptor.c
src/main/host/descriptor/descriptor.h
src/main/host/syscall/ioctl.c
src/main/host/syscall/socket.c

Fixes two socket bugs and implements `FIONBIO` for `ioctl()` to set a socket as non-blocking, which is required for Nginx.
Closes shadow/shadow#344.
Nginx can be used with the following (still missing some syscalls and socket options, but it works):
```
$ shadow --disable-memory-manager shadow-nginx.yaml
```
nginx.conf:
```
error_log stderr;
daemon off;
master_process off;
worker_processes 0;
pid nginx.pid;
events {
worker_connections 1024;
}
http {
include             /etc/nginx/mime.types;
default_type        application/octet-stream;
sendfile off;
tcp_nodelay off;
access_log off;
server {
listen 80;
location / {
root /var/www/html;
index index.nginx-debian.html;
}
}
}
```
shadow-nginx.yaml:
```
options:
stoptime: 10
topology:
- graphml: |
<graphml …
```

Small ioctl and sendto bug fixes, and implement FIONBIO for Nginx

---

src/main/bindings/rust/wrapper.rs
src/main/host/descriptor/descriptor_table.c
src/main/host/descriptor/descriptor_table.h
src/main/host/descriptor/mod.rs
src/main/host/process.c
src/main/host/process.h
src/main/host/syscall/unistd.rs

Instead of dropping the CompatDescriptor internally when the descriptor is deregistered, the descriptor table now returns an owned reference to the CompatDescriptor so that we can drop it ourselves. This lets us add a nicer `close()` method to the CompatDescriptor.

Improvements to the CompatDescriptor

---

src/main/core/support/options.c

Hybrid mode is a poor default since it's currently slower, and
development on it is on hold.
ptrace seems like the most reasonable default right now, since it's
faster than hybrid mode and supports threads.

Use ptrace mode by default

---

src/main/host/descriptor/mod.rs
src/main/host/descriptor/pipe.rs
src/main/host/syscall/mod.rs
src/main/host/syscall/unistd.rs

Ideally the memory manager would provide this interface, and these new enums would be passed all the way from there. But until we write the Process and Thread objects in Rust, these wrappers will be good enough.
The PosixFile `read()` and `write()` methods now accept an `Option` for the buffer. Different Linux file types handle NULL buffers differently, so pass this information along to the file object.
I'm open to changing the names for the enums, but I can't think of any better names.

Added Rust wrappers around process_get*Ptr() functions

---

src/main/host/process.c
src/main/host/process.h
src/main/host/syscall/unistd.c
src/main/host/thread_preload.c
src/main/host/thread_ptrace.c

Now that thread_ptrace is getting a pre-death event and can detach
there, Process can reliably cleanup the native process. This
consolidates a fair bit of scattered waitpid's and attempts to propagate
/ figure out the process exit code.

Consolidate cleanup of plugin process in Process

---

.github/workflows/run_tor.yml

If we want to be able to use the 'workflow_dispatch' event from the dev branch, we need the workflow to exist in the main branch as well. Once we merge this, we can merge main into dev. Then we can replace the workflow in dev with the real workflow.

Added placeholder 'run_tor.yml' workflow

---

ci/container_scripts/test.sh

Shadow should be stable enough now that we don't need to filter out flaky tests, and if there are any, we probably want to know about them.

Removed the second test run with '--rerun-failed' in CI script

---

src/main/core/worker.c

Without this, thread log messages that are logged near the end of a sim get lost in the log buffer.

Bugfix: flush buffered log messages from workers on shutdown

---

src/main/host/thread.c

This fixes a bug affecting performance when using the work stealing scheduler with cpu pinning.

work stealing sched: Fix swapped parameter order setting cpu affinity

---

src/main/host/process.c
src/main/host/thread_ptrace.c

In particular this fixes the deadlock at end of shutdown that happens in
tor simulations in the max-concurrency branch (not yet merged) when
using more workers than the max-concurrency. I don't think it's directly
related to that, but I haven't been able to reproduce it in any other
scenario.

thread_ptrace: Make shutdown more robust

---

CMakeLists.txt
setup
src/main/core/scheduler/scheduler.c
src/main/core/scheduler/scheduler_policy_host_single.c
src/main/core/scheduler/scheduler_policy_host_steal.c
src/main/host/host.c
src/main/host/host.h
src/main/host/process.c
src/main/routing/topology.c

Shadow includes internal performance timers to help us track execution
time of various subroutines. The timer-related functions have shown
up on performance profiles as causing significant overhead. These timers
are now disabled by default.
We add a new --use-perf-timers option to the setup script, and a new
USE_PERF_TIMERS option to cmake that allows us to toggle the performance
timers back on if desired.
Closes #1141
(cherry-picked from commit e9004c2ce06a8bf5a8876188b2ef644e5463c4b4)

Do not use subroutine execution timers by default

---

src/main/Cargo.lock
src/main/Cargo.toml
src/main/utility/proc_maps.rs

The `once_cell` library is more flexible, and seems to be the recommended library now. It also has a tracking issue for merging into the standard library (some parts already have been and it exists in rust nightly), so I think it's a good idea to switch. ~(Also I'm using once_cell in some other code at the moment, and it would be nice to use just a single package.)~

Switch from lazy_static to once_cell

---

.github/workflows/run_tests.yml
ci/run.sh
docs/1.1-Shadow.md
docs/ci.md

We could also support both Fedora 32 and 33, but I think it's simpler to just switch to supporting 33.

Support Fedora 33 instead of 32

---

src/main/core/scheduler/scheduler.c
src/main/core/scheduler/scheduler_policy_host_steal.c
src/main/core/worker.c
src/main/core/worker.h

We stop waking threads up in between rounds in order to compute
the minimum next event time. Instead we keep track of the min time
during the execution of the round.
Closes #1249

Remove inter-round collect info step in scheduler

---

.github/workflows/coverage.yml
.github/workflows/docker.yml
.github/workflows/git.yml
.github/workflows/lint.yml
.github/workflows/run_tests.yml
.github/workflows/run_tor.yml

This disables the 'persist-credentials' feature of the checkout action. I don't think this is really important for our workflows, but seems like a good defence-in-depth thing to do.
This also changes all of our checkout action uses to 'v2'.

Small changes to GitHub workflows

---

src/main/host/descriptor/descriptor.c
src/main/host/descriptor/file.c
src/main/host/descriptor/file.h
src/main/host/process.c
src/main/host/syscall/file.c
src/main/host/syscall/fileat.c
src/main/host/syscall/timerfd.c
src/main/host/syscall/unistd.c
src/main/host/syscall/unistd.rs
src/test/file/test_file.c

Fixes a few descriptor bugs and implements `dup()` for regular files, which is required for Python. (Python uses `dup()` on stdin, stdout, and stderr to check if they are valid descriptors. See [`create_stdio()` in CPython](https://github.com/python/cpython/blob/442ad74fc2928b095760eb89aba93c28eab17f9b/Python/pylifecycle.c#L2108).)
Shadow is still missing syscalls to use things like the built-in http server (I see futex errors, missing socket options, and IPv6 issues). Python also make heavy use of `select()`, so things like [`time.sleep()`](https://github.com/python/cpython/blob/b2a91e0c9ee18b50cc86b21211c2258520a9f5d0/Modules/timemodule.c#L360) don't work in Shadow.
```
options:
stoptime: 10
topology:
- graphml: |
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" …
```

Fix descriptor bugs and support dup() on regular files for Python

---

src/main/core/support/options.c
src/main/core/support/options.h
src/main/host/descriptor/tcp.c

There is only a single congestion control method implemented in the dev branch (reno), so we should remove this option until we support others. Part of #1220.

Removed the TCP congestion control option

---

src/main/host/process.c

closes #1265
Couple of questions:
- rather than manually splitting & parsing, I've used g_shell_parse_argv() here (see https://developer.gnome.org/glib/stable/glib-Shell-related-Utilities.html#g-shell-parse-argv). this will also handle special cases like quoted arguments containing spaces (not not expansions and other special cases, see the referenced docs). do you have any concern?
- should I add a test case? I don't see any test cases for process.c, I'm not sure if you want them or not.

better parameters handling - handles quotes as well

---

src/main/host/descriptor/channel.c
src/main/host/syscall/unistd.c
src/test/pipe/test_pipe.rs

For pipes size zero reads & writes are no-ops

---

src/main/.cargo/config.toml
src/main/CMakeLists.txt
src/test/.cargo/config.toml
src/test/CMakeLists.txt

Our CMake build process sets environment variables and options when running Cargo to build our Rust code. When other tools run Cargo (for example `cargo check`, `cargo doc`), they use the same target directory. Since the environment variables and options are different, Cargo invalidates the cached build files, and when using something like Rust Analyzer, we lose incremental builds altogether.
Instead, only CMake should use a target directory within Shadow's `build/` directory.
Also requires us to update the workflow in https://github.com/shadow/docs.

Don't use Cargo config.toml to set build target directory

---

docs/1.2-Shadow-with-Docker.md

Fixed a markdown typo in `docs/1.2-Shadow-with-Docker.md`.
3 back-ticks were on the wrong line, making it seem as if they were a part of the command.
Signed-off-by: Mathis Van Eetvelde <mathis.vaneetvelde@protonmail.com>

fixed markdown typo in docs

---

src/main/host/thread_preload.c
src/main/host/thread_ptrace.c
src/main/utility/utility.c
src/main/utility/utility.h

In between vfork and exec we share an address space with the parent
process. This can lead to surprising, difficult to debug behavior.
We should restrict ourselves to only making syscalls; e.g. functions in
`man` section 2. Higher level functions could try to allocate,
manipulate locks, etc, which is problematic.
Fixes #1243

Avoid library calls after vfork

---

src/main/routing/topology.c

The error state would get overwritten, even if there was previously an error.

Fix error detection in topology parsing

---

src/main/core/main.c
src/main/core/worker.c
src/main/host/process.c
src/main/host/shimipc.c

This does not change the behaviour of Shadow. It only changes some variable names (for example `_disable_shim_syscall_handler` to `_use_shim_syscall_handler`), and changes the GLib option's behaviour to match.
In the future our experimental option names (for example, currently `--disable-shim-syscall-handler`) will follow this format (`--use-shim-syscall-handler`), but this just changes the variable names for now.

Rename some variables used for experimental options

---

README.md
docs/CONTRIBUTING.md
docs/pull-requests.md

Update pull request guidelines
We've changed which GH merge strategies are allowed. This updates the
contributor guidelines to reflect that.
Also fix broken link to "version-control.md"
Fixes #862

Contributing updates

---

src/test/CMakeLists.txt

There's currently a warning when the log level is set to 'trace' in a
release build. This change gets rid of spurious warnings when running
our tests for release builds.

Tests: log at level 'info' instead of 'debug' in release builds

---

docs/3.1-Shadow-Config.md
src/main/core/support/configuration.rs
src/test/config/convert/shadow.expected.yaml
src/test/config/convert/shadow.original.xml
src/tools/convert_legacy_config.py

You can only specify the host bandwidth in the topology and the host now, instead of the topology, host_defaults, host options, and command line.
Instead of:
```yaml
host_defaults:
bandwidth_down: 10 Kbit
hosts:
myhost:
options:
bandwidth_down: 20 Kbit
processes:
- ...
```
It's now:
```yaml
hosts:
myhost:
bandwidth_down: 20 Kbit
processes:
- ...
```

Moved bandwidth options from host_defaults to the host object

---

docs/3.1-Shadow-Config.md
src/main/core/support/configuration.rs
src/test/CMakeLists.txt

Update default config options

---

docs/3.1-Shadow-Config.md
src/main/core/support/configuration.rs
src/main/host/thread_ptrace.c

* Disable forkproxy / O(n)-waitpid-workaround by default
* Fix a shutdown bug in thread_ptrace that this exposed
Closes #1261

Disable forkproxy by default

---

src/main/core/support/configuration.rs
src/main/routing/topology.c
src/test/tor/minimal/tor-minimal.yaml

Unknown topology attributes now cause the topology parsing to fail.

Don't ignore unknown topology attributes

---

src/main/bindings/c/bindings.h
src/main/host/memory_manager.rs
src/main/host/process.c
src/main/host/process.h
src/main/host/syscall/fileat.c
src/main/host/syscall_types.rs
src/test/file/test_file.c

* TypedPluginPtr: make slice method generic over RangeBounds
* MemoryManager.read_ptr: let caller slice instead of taking offset
* MemoryManager: generalize read_ptr -> readv_ptr
* Split MemoryReader.copy to read_some and read_exact
* MemoryReader: split as_ref into ref_some and ref_exact
* Reimplement process_getReadableString using new Reader API
* Add process_readString
* fileat syscalls: fix memory access bugs
* Add test for fstatat
Fixes #1332

Fix fstatat

---

.github/workflows/coverage.yml
ci/container_scripts/build_and_install.sh
ci/container_scripts/install_extra_deps.sh

The coverage CI tests now use the LLVM apt repo to get the required llvm/clang packages rather than trying to use a distro that includes the required versions.
Replaces: #1330

Update rust nightly and clang versions in converage test

---

src/main/host/memory_manager.rs
src/main/host/thread.rs
src/main/lib.rs

The `unsafe_op_in_unsafe_fn` Rust lint [has been stabilized](https://github.com/rust-lang/rust/pull/79208) and I think we should use it. The lint is currently off by default, but they plan to make it a warning and possibly an error in the future.
Edit: Blocked on #1330.

Enable the 'unsafe_op_in_unsafe_fn' lint

---

src/test/clone/CMakeLists.txt
src/test/clone/test_clone.c

Fixes the `clone-linux` failures I've been able to reproduce locally, and includes some other cleanup to avoid other potential failures.

Deflake clone-linux

---

.github/workflows/run_tor.yml

> when changing the tor versions, make sure to also update the required CI tests in the GitHub repository settings

Added comment to tor CI workflow

---

CMakeLists.txt
src/main/core/scheduler/scheduler.c
src/main/host/descriptor/tcp_retransmit_tally.cc
src/main/host/thread_preload.c
src/main/host/thread_ptrace.c
src/main/routing/topology.c
src/shim/shim_event.c
src/test/file/test_file.c
src/test/phold/test_phold.c

This causes a warning if the C code has unused functions, which makes it more similar to how the Rust compiler works. This warning can also help find forgotten functions when refactoring.

Enable 'unused-function' warning for C code

---

docs/3.1-Shadow-Config.md
src/main/bindings/c/bindings.h
src/main/core/scheduler/scheduler.c
src/main/core/support/configuration.rs
src/main/core/worker.c
src/test/determinism/CMakeLists.txt
src/test/phold/CMakeLists.txt
src/test/tor/minimal/CMakeLists.txt

* The Experimental option `max-concurrency` is now the General option `parallelism`.
* The default scheduler policy is now Host.
* The General option `workers` is now the Experimental option `worker-threads`, and no longer has the `-w` shortcut. Users should use `parallelism` instead. If not set explicitly, the number of worker threads will be set to the number of hosts in the simulation.

Update scheduler options

---

.github/workflows/ci_maintenance.yml
.github/workflows/coverage.yml
.github/workflows/docker.yml
.github/workflows/git.yml
.github/workflows/lint.yml
.github/workflows/run_tests.yml
.github/workflows/run_tor.yml

GitHub recently added a mechanism for restricting the permissions of
what Workflow actions can do. Since none of our workflows need any
kind of write access to GitHub, it makes sense to only give them read
permission.
We could potentially tighten this further to only give read access to
some parts of Shadow, but since we currently don't keep any secrets in
GitHub, it doesn't seem worth trying to maintain more fine-grained
permissions.

Deny write access to all GitHub workflows

---

.github/workflows/lint.yml
docs/README.md
docs/developer_guide.md
docs/install_dependencies.md

Mostly small changes, and the APT and DNF/YUM install instructions were re-ordered since the APT instructions are much simpler and shorter.
This also changes the installation docs to install cargo from rustup rather than from the distribution packages. On Debian stable the version of rustc is almost a year and a half old, and Ubuntu [doesn't recommend](https://wiki.ubuntu.com/FoundationsTeam/RustUpdates) using rustc and cargo from the distribution. Shadow currently uses features that aren't available in these versions, and I don't think there's a good reason to hold ourselves back to an older rust version.

More small documentation changes, and install cargo/rustc from rustup

---

src/main/bindings/c/bindings.h
src/main/bindings/c/cbindgen-opaque.toml
src/main/bindings/c/cbindgen.toml
src/main/bindings/rust/CMakeLists.txt
src/main/bindings/rust/wrapper.rs
src/main/core/logger/shadow_logger.rs
src/main/core/worker.c
src/main/core/worker.h
src/main/core/worker.rs
src/main/host/context.rs
src/main/host/host.rs
src/main/host/memory_manager/memory_copier.rs
src/main/host/memory_manager/memory_mapper.rs
src/main/host/memory_manager/mod.rs
src/main/host/mod.rs
src/main/host/process.c
src/main/host/process.h
src/main/host/process.rs
src/main/host/syscall/mman.c
src/main/host/syscall/unistd.rs
src/main/host/thread.c
src/main/host/thread.h
src/main/host/thread.rs
src/main/host/thread_preload.c
src/main/host/thread_protected.h
src/main/host/thread_ptrace.c

Adds a `context` module, which provides several *Context* structs,
intended to bundle together current relevant objects in the hierarchy.
These are meant to replace `worker_getActiveThread`, etc. Passing around
the current context explicitly instead of putting them in globals both
allows us to avoid interior mutability (and its associated runtime cost
and fallibility), and lets us keep a hierarchical object structure (e.g.
allow holding a mutable Process and a mutable Thread belonging to that
process simultaneously).
Most code (e.g. syscall handlers) can take a `ThreadContext` argument
and use that to manipulate anything on the Host. The *current* `Thread`
and `Process` should typically be accessed directly. e.g. since a
mutable reference to the current `Thread` exists at …

Pass references explicitly instead of getting from global Worker

---

src/main/core/support/simulation_time.rs
src/main/core/worker.rs

Log messages printed after `worker_runEvent()` would contain simulation times of `5124095:34:33.709551615`:
```
00:00:00.295908 [worker-1] 5124095:34:33.709551615 [INFO] [client2:11.0.0.2] [host.c:284] [host_shutdown] host 'client2' has been shut down
```

Fix simulation time in log messages

---

src/test/clone/CMakeLists.txt
src/test/clone/clone-nomm.yaml
src/test/clone/test_clone.c

Allowing `main` to exit was causing the whole process to exit (via
exit_group) instead of just exiting the thread-group-leader.
This resulted in no-longer exercising the edge case where the
MemoryCopier tries to use the task id of a dead thread (the thread group
leader).
Also extended this test to more explicitly test this, by having another
thread validate that Shadow was able to clear the ctid after one of the
other threads exited (both after the thread group leader exited).

test_clone: Fix and extend clone_child_exits_after_leader

---

src/main/bindings/c/bindings.h
src/main/bindings/rust/wrapper.rs
src/main/core/worker.rs

We no longer store pointers to the "current" objects in the global
Worker, only some information *about* those objects.

Remove getActiveThread, getActiveProcess, getActiveWorker

---

ci/container_scripts/install_deps.sh
docs/install_dependencies.md

An [issue](https://bugs.centos.org/view.php?id=18212) with the CentOS 8 CMake package is causing CMake to fail with the following error when building Shadow:
```
cmake: symbol lookup error: cmake: undefined symbol: archive_write_add_filter_zstd
```
The fix for now is to manually install libarchive.
This bug is causing our CentOS 8 CI tests to fail.

Fix and document build errors on CentOS 8

---

README.md
docs/README.md
docs/install_shadow.md
docs/log_format.md

I noticed I missed something in the log format docs, added some notes on uninstalling Shadow, and changed the README "quick setup" to not install the debug version since it's very slow.

Updates to log format, readme, and installation docs

---

docs/parsing_statistics.md
src/tools/plot-shadow.py

The existing example comparing didn't show any difference between traffic queuing disciplines, so the new example uses different socket recv buffer sizes which show a noticeable difference. A small change was made to the plotting scripts to hide boundary effects when calculating a moving average.

Updated example in 'parsing_statistics' doc

---

docs/developer_guide.md
docs/migrating_from_1x.md
docs/nsf_sponsorship.md
docs/shadow_config_options.md
docs/using_recompiled_libc.md

"Plugin" no longer makes sense for Shadow 2.0. Initially we talked about using "managed process" anywhere we would otherwise say "plugin". On further discussion, "virtual" process is a little better when talking about the more abstract concept of a process in the simulation vs the native process used to help implement it.

Plugin -> Managed Process

---

docs/maintainer_playbook.md

I realized the docs in my previous PR #1420 didn't update the tag after the `git commit --amend`.

Fix docs to properly update the git tag after bumpversion

---

src/main/Cargo.lock
src/test/Cargo.lock

Closes #1444, #1445, and #1446.
Updates several Rust dependencies.

Update rust dependencies

---

ci/container_scripts/install_deps.sh
ci/container_scripts/test.sh
docs/shadow_config_spec.md
src/main/bindings/c/bindings.h
src/main/core/support/configuration.rs
src/main/host/shimipc.c
src/main/host/shimipc.h
src/main/host/syscall/signal.c
src/main/host/syscall/signal.h
src/main/host/syscall_handler.c
src/main/host/thread_preload.c
src/shim/preload_syscall.c
src/shim/preload_syscall.h
src/shim/shim.c
src/shim/shim_syscall.c
src/shim/shim_syscall.h
src/test/clone/CMakeLists.txt
src/test/file/CMakeLists.txt
src/test/file/file.yaml
src/test/futex/CMakeLists.txt
src/test/memory/CMakeLists.txt
src/test/memory/mmap.yaml
src/test/memory/unaligned.yaml
src/test/phold/CMakeLists.txt
src/test/phold/phold.yaml
src/test/poll/CMakeLists.txt
src/test/poll/poll.yaml
src/test/signal/CMakeLists.txt
src/test/threads/CMakeLists.txt

Installs a seccomp filter from the shim in preload-mode, which catches any syscalls that would otherwise be missed. The filter allows syscalls that originate from the shim itself. Other syscalls cause a SIGSYS; in the SIGSYS handler we can process the syscall as appropriate (e.g. emulate it via Shadow). Can disable with `--use-seccomp=false`
Semi-fixes https://github.com/shadow/shadow/issues/1168. This is a somewhat different approach than described there, but if this approach works out, then we probably don't need the one described in #1168.
Recompiled libc no longer needed to interpose remaining syscalls, fixing https://github.com/shadow/shadow/issues/892

thread_preload: use seccomp to interpose all syscalls

---

.github/pr_labeler_conf.yml

Values that start with a `*` or `!` are not strings in yaml.

Fixed github labeler config

---

.github/pr_labeler_conf.yml

I noticed in #1471 that the `Component: Testing` label was incorrectly assigned. I think this corrects the logic.

Update labeler rule for testing label

---

README.md
src/main/core/support/configuration.rs
src/main/host/descriptor/epoll.c
src/main/host/descriptor/tcp.c
src/test/determinism/CMakeLists.txt
src/test/determinism/determinism2_compare.cmake

This primarily includes a fix for a confirmed non-deterministic behavior I found in the epoll getEvents function (in c6039d3cace428349aae167c635cb4cfed9e120d).
I also updated a couple of other places in the code where we iterate a hash table (which is non-deterministic) - these were unconfirmed issues but I suspected they _might_ cause problems. (Probably best if we stop using glib hash table iterators in general, and instead prefer an iterator that guarantees a total ordering; rust probably makes this easier.)
Closes #1294

Some determinism fixes

---

src/main/host/descriptor/tcp.c

Closes #1413.
This bug is unrelated to the issue that prevents newer versions of tor from running properly in Shadow.
After running a 1% network for 60 simulated minutes, there were no packets leaked.

Unref partial packet during tcp free

---

src/main/host/syscall/signal.c
src/main/host/syscall/signal.h
src/main/host/syscall_handler.c

The older signal APIs took different structs than the new ones (e.g.
`sigaction` vs `rt_sigaction`). These syscall are all obsolete since
Linux 2.2 so it's probably not worth trying to maintain them.

Remove (broken) support for old signal APIs

---

src/lib/shim/CMakeLists.txt
src/lib/shim/binary_spinning_sem.cc
src/lib/shim/binary_spinning_sem.h
src/lib/shim/shadow_sem.c
src/lib/shim/shadow_sem.h
src/lib/shim/shim.c
src/main/host/thread_preload.c

This adds a reimplementation of libc's semaphore interface. Using it instead of libc's semaphore in our binary_spinning_semaphore results in the underlying `syscall` calls going through the shim's overridden `syscall` function, which is whitelisted in the seccomp filter when seccomp is in use. i.e. this allows us to avoid unnecessary seccomp traps in the shim <-> shadow IPC (without the previous workaround of whitelisting *all* futex operations).
We also use our implementation of libc's semaphore to override libc's semaphore in the shim.
Progress on #1454

Custom semaphore implementation

---

src/main/bindings/c/bindings.h
src/main/host/descriptor/descriptor_table.rs
src/main/host/process.c
src/test/Cargo.toml
src/test/socket/bind/CMakeLists.txt
src/test/socket/bind/bind_in_new_process.yaml
src/test/socket/bind/test_bind_in_new_process.rs

Previously the socket table would be freed, but the sockets would remain bound/associated in the network interface. Now we disassociate them when the process is stopped.
Closes #1490.

Disassociate sockets from interface when stopping process

---

src/main/host/process.c
src/test/socket/bind/bind_in_new_process.yaml

The previous code did not correctly handle when a process ends on its own and doesn't use the `stop_time` option. The test was also updated to test this scenario.

Fixed socket disassociation when a process ends without 'stop_time'

---

.dockerignore
.gitignore
src/lib/shim/CMakeLists.txt
src/lib/shim/preload_syscall.c
src/lib/shim/preload_syscall.h
src/lib/shim/shadow_spinlock.c
src/lib/shim/shadow_spinlock.h
src/lib/shim/shim.c
src/lib/shim/shim.h
src/lib/shim/shim_event.h
src/lib/shim/shim_logger.c
src/lib/shim/shim_tls.c
src/lib/shim/shim_tls.h
src/main/host/thread_preload.c
src/test/clone/CMakeLists.txt
src/test/determinism/CMakeLists.txt
src/test/determinism/test_determinism.c
src/test/socket/sendto_recvfrom/CMakeLists.txt
src/test/threads/CMakeLists.txt

thread_preload now implements `ThreadMethods`::clone. This is implemented by sending a message to the shim to set aside an ipc block for the thread, and then having the shim implement the clone syscall.
In the shim, when executing the clone syscall, the child thread *jumps* back to where the managed program made the original syscall. This is implemented by saving the instruction pointer (RIP) in the SIGSYS syscall handler.
This also adds a wrapper for thread local storage in the shim. In CentOS 7 this was needed to work around some of the implementation details of the native thread local storage. This indirection is no longer necessary at the moment now that we've dropped CentOS 7 support and all supported platforms have compatible thread local storage implementations. However in the …

interpose-method=preload thread support

---

.github/workflows/run_tests.yml
ci/container_scripts/install_deps.sh
ci/container_scripts/install_extra_deps.sh
ci/run.sh
docs/install_dependencies.md
docs/supported_platforms.md

CentOS 8 is only supported for another 5 months.

Change support from CentOS 8 to CentOS Stream 8

---

src/lib/logger/logger.c
src/lib/tsc/tsc.c
src/lib/tsc/tsc_test.c

The default logger filter's logic was backwards, s.t. it'd only log *less* severe messages. Changed it not to filter at all, since outside of tests we always override the default anyway.
Tried to make the tsc test a bit more robust, and added some extra logging; trying to debug #1519 .

Tsc tweaks

---

docs/getting_started_tor.md
src/lib/CMakeLists.txt
src/lib/openssl_preload/CMakeLists.txt
src/lib/openssl_preload/shadow_openssl_rng.c
src/test/tor/minimal/tor-minimal.yaml

Adapted from shadow-plugin-tor. I only took the RNG overrides, since those seemed generic enough to plausibly work with other programs besides tor.
Not sure whether we'll want the "nop crypto" overrides as well, but if so it should probably be able to be used independently of the RNG overrides; e.g. by putting them in a separate library.
Progress on #666 
Before this PR, the heartbeat data diverges at around 8 sim minutes. (Only showing the first few lines of the diff for brevity)
```
$ (cd build/src/test/tor/minimal/ && for i in 1 2; do rm -rf data-$i && /home/jnewsome/projects/shadow/dev/build/src/main/shadow          --data-directory=data-$i          --interpose-method=preload          --log-level=info          --use-cpu-pinning true --parallelism 2 --template-directory …
```

Openssl drbg

---

src/test/tor/minimal/conf/tor.common.torrc

Closes #1503. We've decided to disable circuit build timeout learning since it's already disabled in tornettools for clients (using `UseEntryGuards 0`), and since our minimal test case uses a network where the latency between every host is exactly 50 ms. When all the latencies are the same, the circuit build time distribution is not a pareto distribution and the circuit timeout learning does not work correctly. It also causes us to run into the issue https://gitlab.torproject.org/tpo/core/tor/-/issues/40434.

Disable circuit build timeout learning in tor-minimal test

---

src/lib/shim/preload_libraries.c

Noticed this while debugging a test failure.

Set errno with appropriate value in _getaddrinfo_service 

---

src/main/bindings/c/bindings.h
src/main/host/thread_preload.c
src/main/utility/childpid_watcher.rs

pidfd_open was only added in Linux 5.3. There are still some platforms
supported by Shadow that may not have a new enough kernel to use it.
Fixes https://github.com/shadow/shadow/issues/1532

ChildPidWatcher: remove dependence on pidfd_open

---

src/main/host/syscall/epoll.c
src/main/host/syscall/epoll.h
src/main/host/syscall_handler.c

The `epoll_pwait` syscall with a NULL signal mask is equivalent to calling `epoll_wait`. Golang uses `epoll_pwait` rather than `epoll_wait` in its runtime scheduler.

Support 'epoll_pwait' syscall when given a NULL sigmask

---

src/test/tor/minimal/tor-minimal.yaml

Now that we always include the openssl preload for all managed processes (see #1530), we don't need this line anymore.

Removed ld_preload env from tor minimal test

---

src/lib/shim/shim.c
src/lib/tsc/tsc.c
src/lib/tsc/tsc.h
src/lib/tsc/tsc_test.c
src/main/bindings/rust/wrapper.rs
src/main/host/host.c
src/main/host/host.h
src/main/host/thread_preload.c
src/main/host/thread_ptrace.c

* Add case handling Xeon processors with base clock frequency of 25 MHz (fixing #1519 ).
* Don't try to use clock rate from brand string as TSC rate, since it isn't guaranteed to be the same rate.
* Consolidate setting TSC rate in host initialization, along-side initialization of emulated CPU.
* Fall back to emulated CPU clock rate if we can't determine TSC rate, with a warning that using TSC to measure wallclock time will be inaccurate within the simulation.
* Clean up some related environment variable parsing in the shim.

Improve TSC emulation

---

src/lib/shim/shim.c
src/lib/shim/shim.h
src/lib/shim/shim_event.c
src/test/clone/CMakeLists.txt

In `shim_disableInterposition` and `shim_enableInterposition`, use
`_shim_set_allow_native_syscalls` to truly enable/disable interposition
in ptrace-only mode as well as ptrace+preload mode.
Since the shim logger's syscalls will no longer be interposed, in
`_shim_parent_init_ptrace` open the shim log file *with* interposition
disabled.
`_shim_parent_init_ptrace` no longer needs to implement its own logic
for calling `_shim_set_allow_native_syscalls`, so we can get rid of that
and the boolean return values from `shim_disableInterposition` and
`shim_enableInterposition`.
Fixes #1545. I think was happening was that while logging was being
initialized with interposition enabled, and hence getting a Shadow file
descriptor, any calls to the logger in between the calls to …

shim: Simplify and fix enabling/disabling interposition

---

src/lib/logger/logger.c
src/lib/logger/logger.h
src/lib/shim/preload_syscall.c
src/lib/shim/shim.c
src/lib/shim/shim_syscall.c
src/main/core/manager.c

* Log at level WARNING until shim logger is set up, fixing #1070.
* Propagate configured log level to shim logger, fixing #890.
* Fix bug where shim logger was getting sim time instead of real time.
* Fix bug where shim logger was always getting 0 for sim time in ptrace mode.
* Make default logger thread safe and signal safe

Shim logger bug fixes

---

src/main/bindings/rust/wrapper.rs
src/main/host/descriptor/timer.c
src/main/host/descriptor/timer.h
src/main/host/process.c
src/main/host/process.h
src/main/host/syscall/epoll.c
src/main/host/syscall/futex.c
src/main/host/syscall/poll.c
src/main/host/syscall/protected.c
src/main/host/syscall/protected.h
src/main/host/syscall/socket.c
src/main/host/syscall/time.c
src/main/host/syscall/uio.c
src/main/host/syscall/unistd.c
src/main/host/syscall_condition.c
src/main/host/syscall_condition.h
src/main/host/syscall_condition.rs
src/main/host/syscall_handler.c
src/main/host/thread.c
src/main/host/thread.h

This is primarily to make timeout handling easier to expose in Rust.
* Remove SyscallHandler::timer, since in practice it was redundant with SyscallCondition::timeout.
* Deduplicate code to read and validate a timespec

Simplify syscall condition and timeouts

---

src/main/routing/network_graph.rs

Forgot to parse the jitter from network graph edges. We don't currently use it, but we previously did parse it to make sure it had the correct format.

Parse jitter from network graph

---

src/main/Cargo.lock
src/main/Cargo.toml
src/main/core/support/units.rs

Upgraded clap from 3.0.0-beta.2 to 3.0.0-beta.4

---

src/test/determinism/CMakeLists.txt
src/test/epoll/CMakeLists.txt
src/test/sockbuf/CMakeLists.txt
src/test/socket/accept/CMakeLists.txt
src/test/socket/sendto_recvfrom/CMakeLists.txt
src/test/socket/shutdown/CMakeLists.txt

This reduces the size of `build/Testing/Temporary/LastTest.log` from 556 MiB to 203 MiB when shadow is built in debug mode, and should fix #1572. These tests generated the most log lines (> 50,000) in `LastTest.log`.

Set a few tests to log at debug level instead of trace

---

ci/run.sh

ci/run.sh was generating invalid tag names from the quay.io/centos/centos:stream8 base container. It now replaces the `/` characters.

Replace forward-slashes in docker image tags

---

docs/shadow_config_spec.md

I included some extra documentation, and added a GML graph to the example to make it obvious what the `network_node_id` refers to.

Config spec documentation changes

---

src/main/host/affinity.c

See <https://github.com/shadow/shadow/issues/1606>

fixes CPU ordering function to use CPU load table instead of erroneously using core load table

---

docs/shadow_config_spec.md
src/main/host/host.c

The documentation previously stated that the pcap directory was relative to the host directory, but this wasn't true. This PR fixes the code to follow the documentation. We could remove this directory option and make it an on/off option with a fixed path, but I don't think it hurts to leave the directory as an option if someone wants to use it.

Make the pcap directory relative to the host directory

---

docs/shadow_config_spec.md
src/main/core/support/configuration.rs

Preload-based interposition is now fairly stable, and is significantly
faster than ptrace. It is now the most sensible default.
Closes #1647

Make preload the default interposition mechanism

---

src/main/core/main.rs

Some errors such as parsing the configuration file occur before the logger is initialized.

Improve error messages before logger is initialized

---

src/main/core/main.rs

In particular this avoids a panic when using the HEAPPROFILE env
variable to enable gperftools heap profiling
https://gperftools.github.io/gperftools/heapprofile.html.
I suspect it has something to do with "Due to a hack we make to work
around a possible gcc bug, your profiles may end up named strangely if
the first character of your HEAPPROFILE variable has ascii value greater
than 127". It looks like the referenced hack is mangling the env var in
memory to something non-unicode.

Don't panic on non-unicode env vars

---

src/main/bindings/c/bindings.h
src/main/host/descriptor/descriptor_table.rs
src/main/host/process.c

In general, the calling function would want to close the descriptor after it's removed rather than immediately dropping/freeing it, so returning the descriptor allows the calling function to do that. But right now, we know that 'descriptortable_set()' is only called for fds 0, 1, and 2, and that they won't have previously been used, so we can assume that one isn't returned.

Return replaced descriptor from 'descriptortable_set()'

---

src/main/bindings/c/bindings.h
src/main/host/descriptor/mod.rs
src/main/host/descriptor/pipe.rs
src/main/host/syscall/fcntl.rs
src/main/host/syscall/mod.rs
src/main/host/syscall/unistd.rs

The `FileFlags` are called 'status flags' in Linux so it was renamed to `FileStatus`. We needed to rename the existing `FileStatus` flags which represent the readable/writable/closed/etc status of the file, so it is now `FileState`. Other related names such as `StatusEventSource` have also been renamed to match.

Renamed 'FileStatus' to 'FileState' and 'FileFlags' to 'FileStatus'

---

src/main/Cargo.lock
src/main/Cargo.toml

Closes #1663. A proposed fix is to set the help heading on each argument, but we have a lot of arguments so we'll leave that as a last resort if we need to update to a newer clap in the future.

Downgrade clap version to fix mismatched heading bug

---

src/main/host/descriptor/mod.rs
src/main/host/syscall/fcntl.rs

The access mode flags should be treated as distinct values, not as flags, and Linux also uses the `O_PATH` flag which we didn't previously handle.

Improve access mode flag handling

---

src/main/host/descriptor/file.c
src/main/host/syscall/unistd.c
src/test/file/test_file.c

pread and pwrite were internally using read and write when called with an offset of 0. This is incorrect since it updates the current position in the file.
This bug surfaces when opening a sqlite database.
Fixes the bug and adds tests.

Fix pread and pwrite with offset 0

---

.github/workflows/coverage.yml

https://github.com/codecov/codecov-action
> On February 1, 2022, [v1] will be fully sunset and no longer function
>
> Due to the deprecation of the underlying bash uploader, the Codecov GitHub Action has released v2 which will use the new uploader. You can learn more about our deprecation plan and the new uploader on our blog.

Upgrade codecov uploader to v2

---

src/main/Cargo.lock
src/test/Cargo.lock

This includes an update for crossbeam-deque which has had a [security advisory](https://github.com/crossbeam-rs/crossbeam/security/advisories/GHSA-pqqp-xmhj-wgcw) for a couple of months (not an issue for us in practice, but cargo-deny warns about it).

Upgrade Cargo packages

---

src/lib/libc_preload/gen_syscall_wrappers_c.py
src/lib/libc_preload/syscall_wrappers.c
src/main/host/syscall/eventfd.c

The libc preload library was creating a C function `eventfd()` which called the `SYS_eventfd` syscall, but `eventfd()` should be calling `SYS_eventfd2`.

Fix eventfd syscall wrapper

---

src/main/host/descriptor/mod.rs
src/main/host/descriptor/pipe.rs
src/main/host/descriptor/shared_buf.rs
src/main/host/syscall/unistd.rs

This is mostly just moving the `SharedBuf` type to its own module/file. An accessor function was also added for its `num_writers` field.

Move SharedBuf to a new module/file

---

src/main/utility/random.rs

This extra sampling is unneeded when using `seed_from_u64()`:
https://docs.rs/rand_xoshiro/latest/rand_xoshiro/struct.Xoshiro256PlusPlus.html?search=#impl-SeedableRng
> pub fn seed_from_u64(seed: u64) -> Xoshiro256PlusPlus
>   Seed a `Xoshiro256PlusPlus` from a `u64` using `SplitMix64`.
From a small test, it seems to be working as expected:
```rust
let mut rng = Xoshiro256PlusPlus::seed_from_u64(0);
for x in 0..5 {
println!("{:b}", rng.next_u64());
}
```
```text
101001100010111010111010110000101001001000010110010001111011111
110000111011010011011110011110111000011100000001101010100000111
101110000001111110111111001000111101100100110100111101111111100
1011101110101111111000110000111011101111100101111000011010
111111011001010000001001110101110101111010010100101111011101010
```

Remove unnecessary 'Random' initialization

---

.github/workflows/run_tests.yml
CMakeLists.txt

Workaround for #1741 until clang 13.0.1 is available on supported distributions.

Show build-time error if using clang 13.0.0, and exclude centos stream 8 + clang from the CI tests

---

src/test/CMakeLists.txt
src/test/exit/CMakeLists.txt
src/test/socket/bind/CMakeLists.txt
src/test/socket/sendto_recvfrom/test_sendto_recvfrom.rs
src/test/tor/minimal/CMakeLists.txt

We need to ignore the return values of managed processes in some tests, and one of the sendto/recvfrom tests was passing when it shouldn't have been.

Fix test regexes which caused incorrect tests to pass

---

docs/getting_started_basic.md

Adds a note to the docs about #1794. We should maybe consider removing this example, but I think we should have this in the docs in the meantime.

Add note to docs about cURL spinloop

---

src/main/host/memory_manager/memory_mapper.rs

```text
warning: field is never read: `memory_copier`
--> host/memory_manager/memory_mapper.rs:67:5
|
67 |     memory_copier: MemoryCopier,
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
```

Fix rust unread struct field warning

---

src/main/core/support/configuration.rs

Signed-off-by: Muhammad Falak R Wani <falakreyaz@gmail.com>

Prefer `IntoIterator::into_iter` instead of deprecated `IntoIter::new`

---

src/main/Cargo.lock
src/test/Cargo.lock

Ran `cargo update` in `src/main` and `src/test` to update dependencies not listed in the `Cargo.toml` (updated dependencies of dependencies).

Update versions in Cargo lock file

---

.github/dependabot.yml

Dependabot can open up to 5 PRs at once. When the main branch changes, it will rebase all 5 dependabot PRs, which causes hours worth of workflow runs in the CI. This is painful when you try to merge these dependabot PRs since every merged PR causes workflow runs for all remaining dependabot PRs, even though you can only merge one at a time.
This PR disable's dependabot's auto-rebase. Instead dependabot will need to be told manually to rebase PRs.

Disable 'rebase-strategy' dependabot option

---

src/main/host/descriptor/tcp.c
src/test/socket/listen/test_listen.rs

Allows TCPS_LISTEN to be a valid listening state; enables socket double-listen test in Shadow.

Allows TCPS_LISTEN to be a valid listening state

---

src/lib/shim/shim.c
src/lib/shim/shim.h
src/lib/shim/shim_rdtsc.c
src/lib/shim/shim_seccomp.c
src/lib/shim/shim_syscall.c
src/lib/shim/shim_tls.c
src/main/host/syscall/signal.c
src/main/host/syscall/signal.h
src/main/host/syscall_handler.c

Configure the shim's signal handlers (which are only used in preload mode) to use an alternate stack via `sigaltstack`. Experimentally this appears to fix the stack corruption observed in https://github.com/shadow/shadow/issues/1549.
In preload mode, also prevent managed calls to `sigaltstack` from overwriting our configuration. Eventually this should be implemented more faithfully, but this should be good enough at least until we're to the point of being able to invoke signal handlers configured by the managed process.
This is "milestone 1" of https://github.com/shadow/shadow/discussions/1851

Use an alternate stack for signal handling

---

src/lib/shim/shim.c
src/lib/shim/shim.h
src/lib/shim/shim_tls.c

This ensures we'll fail in a more consistent and debuggable way if the
allocated stack is too small.
This lets us be less conservative with the allocated stack size, so we
reduce it from 40KiB to 20KiB.

Add guard page to signal stack

---

src/lib/shim/shim.c
src/lib/shim/shim.h
src/lib/shim/shim_api_addrinfo.c
src/lib/shim/shim_event.c
src/lib/shim/shim_event.h
src/lib/shim/shim_shmem.h
src/lib/shim/shim_sys.c
src/lib/shim/shim_sys.h
src/lib/shim/shim_syscall.c
src/main/bindings/rust/CMakeLists.txt
src/main/host/process.c
src/main/host/syscall/shadow.c
src/main/host/thread.c
src/main/host/thread.h
src/main/host/thread_preload.c
src/main/host/thread_protected.h
src/main/host/thread_ptrace.c
src/main/host/thread_ptrace.h

* Adds per-process shared memory, which we need to hold per-process signal state.
* Moves per-thread shared memory from ThreadPtrace to Thread, since we will need it for per-thread signal state.
* Moves the simtime from per-thread state to per-process state.
* Migrates thread_preload to use the simtime in shared memory instead of explicitly sending it in IPC messages.

Add per-process shared memory and clean up

---

src/main/host/syscall_condition.c

Preparing to have syscallcondition fire (interrupting a blocked syscall) when the thread receives a signal.
* Change current terminology from "signal" to "wakeup", to distinguish from signals.
* Create a helper function to check whether a condition is ready, and stop memoizing whether a timeout happened. This is in preparation to add a third "ready" condition - when there is an unblocked signal pending.

Syscallcondition refactor for signals

---

src/lib/shim/shim_api_addrinfo.c
src/test/resolver/test_getaddrinfo.c

Fixes https://github.com/shadow/shadow/issues/1869

_getaddrinfo_service: Make behavior on bad service name consistent

---

.github/workflows/run_tests.yml
ci/run.sh
docs/ci.md
docs/supported_platforms.md

Replaces #1734. Also update the EOL dates for Ubuntu to show the standard EOL dates rather than the enterprise / paid support EOL dates.

Add Fedora 35 to supported releases and CI tests

---

src/lib/syscall-logger/src/lib.rs
src/main/bindings/c/bindings.h
src/main/host/syscall/format.rs
src/main/host/syscall_handler.c
src/main/host/thread.rs

Example:
```
00:00:01.000 [tid 1000] write(1, "Testing test_make_detached...BBBBBBBBBBB"..., 29) = 29
00:00:01.000 [tid 1000] mmap(...) = 140737192390656
00:00:01.000 [tid 1000] mprotect(...) = 0
00:00:01.000 [tid 1000] clone(...) = 1001
00:00:01.000 [tid 1001] shadow_get_shm_blk(...) = 0
00:00:01.000 [tid 1001] set_robust_list(...) = -38 (ENOSYS: Function not implemented)
00:00:01.000 [tid 1001] madvise(...) = <native>
00:00:01.001 [tid 1000] nanosleep(...) = 0
```

Log the thread id during strace logging

---

src/main/host/syscall/signal.c

The warning was pretty noisy; e.g. libc calls sigaction for every realtime signal at startup, with the action of most set to `SIG_DFL`.
We still detect and warn later if a realtime signal is actually sent.

Allow setting a sigaction for realtime signals

---

src/lib/shim/shadow_signals.h
src/lib/shim/shim.c
src/lib/shim/shim_shmem.c
src/lib/shim/shim_shmem.h
src/lib/shim/shim_syscall.c
src/main/host/syscall/signal.c
src/test/signal/test_signals.rs

The golang runtime uses sigaltstack, and detects when its handlers aren't running on the configured stack.
Helps with some of the errors in #1549 .

Implement sigaltstack

---

src/main/host/syscall/format.rs

When the buffer address is invalid, print the address rather than an empty string.
Old:
```
sendto(3, "", 0, (empty), 0x0, 0) = 0
```
New:
```
sendto(3, 0x1, 0, (empty), 0x0, 0) = 0
```

If strace string logging pointer is invalid, print address

---

ci/container_scripts/install_deps.sh
docs/install_dependencies.md

This doesn't seem to be an issue anymore.

Remove centos stream 8 libarchive workaround

---

docs/README.md
docs/SUMMARY.md
docs/coding.md
docs/developer_guide.md

- moved the "Building the C-Rust bindings" doc section from the "Debugging and profiling" page to a new "Coding" page
- moved the "Contributing" and "Maintainer playbook" pages into the "Developer Guide" section

Docs bindings

---

src/main/Cargo.lock
src/main/Cargo.toml
src/main/core/main.rs
src/main/shmem/cleanup.rs

~Fixes a race condition by making the unit tests run single-threaded, and makes sure that there are no pre-existing shm files.~
Fixes a race condition by making the unit tests use temporary directories.

Fix shm cleanup tests

---

src/tools/convert_legacy_topology.py

This bug causes our Fedora 35 CI tests to fail, which uses the recently released [networkx 2.7](https://github.com/networkx/networkx/releases/tag/networkx-2.7).
Workaround for https://github.com/networkx/networkx/issues/5367

Added workaround for networkx bug

---

src/lib/shim/CMakeLists.txt
src/lib/shim/shim_syscall.c
src/test/golang/CMakeLists.txt

Fixes #1931 and #1549.
Also reduces the failure rate of the goroutines test
(https://github.com/shadow/shadow/issues/1932) from ~80% to ~10%.

Explicitly initialize shim's new thread state after clone

---

src/main/host/syscall/handler/fcntl.rs
src/main/host/syscall/handler/ioctl.rs
src/main/host/syscall/handler/mod.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/handler/unistd.rs

`get_descriptor()` and `get_descriptor_mut()` - these tied the lifetime of the descriptor refs to the lifetime of the syscall handler ref, but we don't need this restriction.
`empty_sockaddr()`, `write_sockaddr()`, and `read_sockaddr()` - these are standalone helpers that should be independent of a syscall handler object.
Also simplified a few socket plugin memory helpers (only needed the process memory, not the process itself).

Rearranged a few syscall helper functions

---

src/lib/libc_preload/gen_syscall_wrappers_c.py
src/lib/libc_preload/syscall_wrappers.c
src/test/regression/CMakeLists.txt
src/test/regression/flush_after_exit.yaml
src/test/regression/test_flush_after_exit.c

`exit` has a non-trivial wrapper that calls `atexit` hooks, flushes open `FILE*` objects, etc.

Don't override the exit function

---

src/main/bindings/rust/wrapper.rs
src/main/host/host.c
src/main/host/host.h
src/main/host/process.c
src/main/host/syscall/protected.h
src/main/host/syscall/signal.c
src/main/host/syscall/time.c
src/main/host/syscall_handler.c
src/main/host/thread_preload.c

Hold the HostShimSharedMemLock in a wider scope on the Shadow side. This is in preparation to add and use more protected state, which will be accessed outside of the SyscallHandler.
This should be roughly the same amount of locking and unlocking as before in practice.
Progress on #1792

ShimSharedMem locking refactor

---

docs/shadow_config_spec.md
src/lib/shim/shim_shmem.c
src/lib/shim/shim_shmem.h
src/lib/shim/shim_sys.c
src/main/bindings/c/bindings.h
src/main/bindings/rust/wrapper.rs
src/main/core/support/configuration.rs
src/main/host/host.c
src/main/host/process.c
src/main/host/syscall/protected.h
src/main/host/syscall/shadow.c
src/main/host/syscall/shadow.h
src/main/host/syscall/time.c
src/main/host/syscall/time.h
src/main/host/syscall_handler.c
src/main/host/syscall_numbers.h
src/main/host/thread_preload.c
src/main/host/thread_ptrace.c
src/test/Cargo.toml
src/test/regression/CMakeLists.txt
src/test/regression/busy_wait.yaml
src/test/regression/test_busy_wait.rs

* Add regression test that loops until time moves forward.
* Add options to allow moving time forward after some number of consecutive unblocked syscalls.
* Implement `sched_yield` as a no-op and on the shim side to help make busy loops that use it fast.
* Fix a previously-latent bug in thread_preload, where it overwrote the thread's "current event" when executing a syscall in the managed thread on behalf of Shadow.

Add feature to escape busy loops

---

src/lib/shim/shim_api_addrinfo.c
src/test/resolver/CMakeLists.txt
src/test/resolver/test_getaddrinfo.c

This causes iperf3 to segfault in [`netannounce()`](https://github.com/esnet/iperf/blob/dfcea9f6a09ead01089a3c9d20c7032f2c0af2c1/src/net.c#L251). (iperf3 still doesn't run correctly under shadow, but this fixes the segfault.)

Fix a case where getaddrinfo() incorrectly returns 0

---

src/main/host/descriptor/socket/abstract_unix_ns.rs
src/main/host/descriptor/socket/unix.rs

Previously the socket's bound address would be set to the unnamed address, not the address returned from 'autobind()'.

Fix a bug when binding to an unnamed unix socket address

---

.github/workflows/lint.yml

This works around https://github.com/actions/checkout/issues/760

lint-bindings: tell git that working directory is safe

---

src/main/host/descriptor/mod.rs
src/main/host/descriptor/pipe.rs
src/main/host/descriptor/shared_buf.rs
src/main/host/descriptor/socket/unix.rs

Previously the `SharedBuf` used the `FileState::READABLE` state to indicate that the buffer was readable or that it had no writers (and a similar behaviour for the `FileState::WRITABLE` state). This is the behaviour expected by pipes (ex: a pipe should always be readable when there are no writers), but is not the behaviour expected by unix sockets (ex: a unix socket should *not* always be readable when there are no connected sockets). With the new state type `BufferState`, there are two new state flags `NO_READERS` and `NO_WRITERS`. So the object (a pipe or unix socket) using the buffer can listen for the `READABLE`, `WRITABLE`, `NO_READERS`, and `NO_WRITERS` state flags individually (or not at all). For example, unix sockets would ignore these two new flags.

Changed `SharedBuf` to use a new `BufferState` rather than `FileState`

---

src/lib/shim/shim_shmem.c
src/lib/shim/shim_shmem.h
src/lib/shim/shim_sys.c
src/main/bindings/c/bindings.h
src/main/bindings/rust/CMakeLists.txt
src/main/bindings/rust/wrapper.rs
src/main/core/scheduler/scheduler.c
src/main/core/scheduler/scheduler.h
src/main/core/scheduler/scheduler_policy.h
src/main/core/scheduler/scheduler_policy_host_single.c
src/main/core/scheduler/scheduler_policy_thread_single.c
src/main/core/worker.c
src/main/core/worker.h
src/main/core/worker.rs
src/main/host/host.c
src/main/host/process.c
src/main/host/syscall_handler.c
src/main/host/thread_preload.c
src/test/golang/test_intercept_golang_time.go
src/test/regression/busy_wait.yaml
src/test/regression/exit_after_signal_sched.yaml
src/test/regression/signal_resched.yaml

* Add a scheduler API `scheduler_nextHostEventTime` to peek at the time of the next scheduled event for a given Host. I only implemented this for the couple schedulers we use in practice - the others panic if this API is called. I could implement this API for the other schedulers, but it doesn't seem worth it since we don't currently use them, and plan to remove them.
* Allow time to be moved forward during the execution of an event. Use this to account for unblocked syscall latency without having to schedule a new event, or without even having to context switch from the shim to Shadow, as long as the maximum runahead time isn't exceeded. The max runahead time is the first of: the time of the next event scheduled for the current host, and the end of the current scheduler round.
* Update …

Increment time locally when able

---

src/main/utility/event_queue.rs

The listener is removed when the handle is dropped, so if the handle returned from an expression isn't used then it's likely an error.

Added 'must_use' attr to event 'Handle' object

---

src/main/host/descriptor/socket/mod.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/syscall/handler/socket.rs

More work on reorganizing the unix sockets. This PR begins moving some unix socket data from the `UnixSocketCommon` into the specific states. This also reorganizes some of the socketpair() related code, and removes the broken connect() implementation for connection-oriented unix sockets.

Continued reorganization of the unix socket code

---

src/main/host/descriptor/socket/mod.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/syscall/handler/socket.rs
src/main/utility/enum_passthrough.rs

I don't know of a nicer way to do this, since I don't see a way to allow *specific* deprecated types/fns globally.
Fixing the deprecation issues is in #2093.

Add "#[allow(deprecated)]" wherever we use deprecated nix socket address types/fns

---

src/test/socket/connect/test_connect.rs
src/test/socket_utils.rs

These are currently only enabled on Linux since they do not work with either inet or unix sockets in Shadow.
1. Does accept() on the server socket cause the connect() on the client socket to unblock?
2. Does close() on the server socket cause the connect() on the client socket to unblock?

Add tests for blocking connect() calls

---

src/test/socket/accept/test_accept.rs

These tests are currently disabled in Shadow.

Update socket accept() tests to support unix sockets

---

docs/shadow_config_spec.md
src/main/core/support/configuration.rs

Update defaults for syscall latency modeling    
These defaults significantly improve simulation performance of our test snowflake simulation. On my machine it brings the simulation time down from 55s to 33s. See https://github.com/shadow/shadow/issues/2046#issuecomment-1105765653 through https://github.com/shadow/shadow/issues/2046#issuecomment-1105821624                                
This decrease in max-unapplied-cpu-latency does appear to make tor *simulated* performance worse, but not tor *simulation* performance.  i.e. it doesn't make the simulation take longer, but it results in higher transfer latencies and lower goodput. This could use further investigation, especially before defaulting latency modeling on as a whole, but doesn't seem necessarily incorrect. See …

Update syscall latency modeling default parameters

---

src/main/bindings/c/bindings.h
src/main/bindings/c/cbindgen-opaque.toml
src/main/bindings/c/cbindgen.toml
src/main/bindings/rust/wrapper.rs
src/main/core/logger/shadow_logger.rs
src/main/core/support/emulated_time.rs
src/main/core/support/mod.rs
src/main/core/support/simulation_time.rs
src/main/core/worker.rs
src/main/host/process.c
src/main/host/process.h
src/main/host/syscall/format.rs
src/main/host/syscall/futex.c
src/main/host/syscall/handler/sysinfo.rs
src/main/host/syscall/time.c
src/main/utility/status_bar.rs

Replaced `process_readTimeSpec` with helpers in Rust for converting to and from `libc::timespec`, and exposed those back to C. Also added conversions for `libc::timeval`, which we'll need for the itimer syscalls.
While writing the unit tests I decided that having the Rust SimulationTime support a wider range of values than the C SimulationTime is too likely to cause confusion. I changed it to wrap a C SimulationTime, and likewise for the Rust EmulationTime.
I think it's probably worth using SimulationTime broadly in Rust code after all rather than using Duration. e.g. here it was useful because we can implement the `From` trait between `SimulationTime` and `libc::timeval` and `libc::timespec`. We can't do the same for `Duration` since we don't own the type.

Clean up and extend time types

---

src/main/host/descriptor/mod.rs
src/main/host/process.rs

The old name didn't seem right, so hopefully the new name fits better.

Rename 'OwnedLegacyDescriptor' to 'CountedLegacyDescriptorRef'

---

src/Cargo.lock

Should close the currently open dependabot PRs, and upgrades the dependencies of dependencies that dependabot doesn't handle.

Upgrade rust dependencies (cargo update)

---

src/main/bindings/c/bindings.h
src/main/core/scheduler/scheduler_policy_host_single.c
src/main/core/scheduler/scheduler_policy_thread_single.c
src/main/core/support/definitions.h
src/main/core/support/emulated_time.rs
src/main/core/worker.c
src/main/host/descriptor/timerfd.c
src/main/host/process.c

* Replaces `SIMULATED_TIME_TO_EMULATED_TIME` with `emutime_add_simtime`
* Replaces `EMULATED_TIME_TO_SIMULATED_TIME` with `emutime_sub_emutime`
These make it a bit clearer at the call site what's being done,
especially since the old helper names implicitly reference the
(deprecated) usage of `SimulatedTime` to reference an instant in time.
Also gets rid of some redundant C helpers in favor of wrapping the
equivalent Rust functionality.
Also:
* renames `EMULATED_TIME_UNIX_EPOCH` to `EMUTIME_UNIX_EPOCH` for conciseness and consistency with e.g. `EMUTIME_MAX`
* renames `EMULATED_TIME_OFFSET` to `EMUTIME_SIMULATION_START` for clarity.

Make time arithmetic more explicit

---

src/lib/syscall-logger/src/lib.rs
src/main/host/syscall/format.rs

It turns out that if you have a struct with generics that all have default types, you should surround the struct type with angled brackets. So `<SyscallArgsFmt>::new()`, not `SyscallArgsFmt::new()`.

Support logging syscalls with no arguments

---

src/main/host/descriptor/tcp.c

When enabling SYN packet retransmission, we noticed that the network performance was changing during Tor simulations. The performance change was narrowed down to the behaviour of the initial `tcp->send.unacked` value, which represents the next un-acked sequence number. In current Shadow since the first packet of a connection (the SYN packet) has a sequence number of 0 and the resulting ACK value is 1, I think it's more correct to initialize this `tcp->send.unacked` value as 0 instead of 1. Otherwise the first ACK isn't considered to be a valid ACK.
https://github.com/shadow/shadow/blob/87f5d75063fa4908e734c15513ebcb4800920f06/src/main/host/descriptor/tcp.c#L1778-L1780
Changing this value allows the connection to simultaneously send multiple data packets after the handshake has completed …

Initialize `tcp->send.unacked` as 0 not 1

---

src/main/bindings/c/bindings.h
src/main/core/work/task.rs
src/main/core/worker.c
src/main/host/descriptor/eventfd.rs
src/main/host/descriptor/mod.rs
src/main/host/descriptor/pipe.rs
src/main/host/descriptor/socket/mod.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/descriptor/tcp.c
src/main/host/descriptor/timerfd.c
src/main/host/network_interface.c
src/main/host/process.c
src/main/host/process.rs
src/main/host/syscall_condition.c
src/main/host/timer.c
src/main/host/tracker.c
src/main/utility/childpid_watcher.rs
src/main/utility/mod.rs
src/test/regression/CMakeLists.txt
src/test/regression/packet_after_simulation_end.yaml

Make SyncSendPointer unsafe and add HostObjectPointer    
Constructing a `SyncSendPointer` implies that the object pointed to by it as actually `Sync` and `Send`. Updated docs and marked unsafe to reflect that.
In most places we were using `SyncSendPointer`, the pointer is *not* actually fully thread-safe, and we instead rely on the Host lock being held at access time. Created `HostObjectPointer` for such pointers.

SyncSendPointer: be more explicit about safety

---

README.md
docs/README.md
docs/SUMMARY.md
docs/design_1x.md
docs/getting_started_basic.md
docs/getting_started_tgen.md
docs/getting_started_tor.md
docs/install_dependencies.md
docs/install_shadow_with_docker.md
docs/network_graph_overview.md
docs/sidechannels.md
docs/system_configuration.md

Documentation urls were changed to use https when possible, and surrounded by <> so that they are parsed correctly by mdbook's markdown parser.
Also made some other misc changes that I think are improvements, including moving the "(Experimental) Shadow with Docker" page further down in the documentation tree.

Fix documentation URLs, and other misc changes

---

src/lib/shim/shim_signals.c
src/main/host/process.c
src/test/regression/CMakeLists.txt
src/test/regression/sigkill_self.yaml

* Add a regression test for https://github.com/shadow/shadow/issues/2151
* Treat death by signal 9 as an error if Shadow didn't    
intentionally use it to stop the process.    
* Write an empty exitcode file when Shadow does kill the process (via    
signal 9), which is a more intuitive result for a process that didn't    
exit within the simulation itself.
Fixes https://github.com/shadow/shadow/issues/2151

Distinguish between sources of death by SIGKILL

---

.github/workflows/run_tests.yml
ci/run.sh
docs/supported_platforms.md

Fedora 36 was released in May 2022.
That makes Fedora 34 EOL on June 7 2022, but we'll wait for a major
version bump to deprecate it.
https://github.com/shadow/shadow/issues/2178

Support Fedora 36

---

src/main/host/descriptor/socket/unix.rs
src/main/host/syscall/handler/socket.rs
src/test/socket/connect/test_connect.rs
src/test/socket/getpeername/test_getpeername.rs
src/test/socket/sendto_recvfrom/test_sendto_recvfrom.rs
src/test/socket_utils.rs

The amount of data that a socket can send needs to be tracker per-sender rather than per-receive-buffer. Also adds support for returning the sender's sockaddr in `recvfrom()` calls, and adds additional unix socket tests. About half of the additions in this PR are for tests.
Closes #2125 and closes #2124.

Support fixed-size send buffers for unix dgram sockets

---

docs/iperf2.md

The iPerf 2 version on ubuntu 20.04 is `2.0.13 (21 Jan 2019)`. The next release was `2.1.1 (22 June 2021)`, which has been tested to work correctly in Shadow. (There may have been a `2.1.0` release, but it's not tagged or "branched" in git so I didn't test it.) The most recent version is `2.1.7 (11 April 2022)` which also works.

Update iPerf 2 docs now that itimer is supported

---

src/main/host/process.c

Rather than waiting for the user to provide input on stdin, shadow stops itself and waits for something to send it a SIGCONT.

When debugging a host, stop Shadow with SIGTSTP

---

src/main/bindings/c/bindings.h
src/main/core/manager.c
src/main/core/manager.rs
src/main/core/mod.rs
src/main/core/support/configuration.rs
src/main/routing/network_graph.rs
src/main/utility/mod.rs

We had discussed wanting to save the final configuration settings as yaml. It seems like it's generating a yaml that can be passed back into Shadow, but I don't think we should guarantee that.
Example for the sendto-recvfrom test:
```yaml
---
general:
stop_time: 5 sec
seed: 1
parallelism: 1
bootstrap_end_time: 0 sec
log_level: debug
heartbeat_interval: 1 sec
data_directory: sendto-recvfrom-shadow-preload.data
template_directory: ~
progress: false
model_unblocked_syscall_latency: false
network:
graph:
type: 1_gbit_switch
use_shortest_path: true
experimental:
use_sched_fifo: false
use_o_n_waitpid_workarounds: false
use_explicit_block_message: false
use_seccomp: ~
use_syscall_counters: true
use_object_counters: true
use_preload_libc: true
use_preload_openssl_rng: true …
```

Write the processed config to 'shadow.data/processed-config.yaml'

---

src/lib/shim/shim_tls.c
src/lib/shim/shim_tls.h
src/main/host/syscall/poll.c
src/test/poll/test_poll.rs
src/test/test_utils.rs

Progress on #1889 .
* Adds Interruptor utility struct to test_utils, which arranges for the current thread to be sent a signal after a specified timeout.
* Adds tests to poll for being interrupted by a signal, and fixes poll to correctly return EINTR.
* The tests ran into the hard-coded limit on number of threads in shim_tls; I reworked to remove the limit.

poll: return EINTR when interrupted

---

src/lib/shim/shim.c
src/lib/shim/shim.h
src/lib/shim/shim_syscall.c
src/lib/shim/shim_tls.c

* Allocate signal stacks explicitly using mmap instead of using thread-local-storage
* Arrange for signal stacks to be freed by another thread (the next one that exits and wants to free its own stack)
* Change ShimThreadLocalStorage to use native thread-local-storage directly, now that we're no longer using it to allocate the signal stack.

Stop leaking thread-local-storage including signal stacks

---

docs/semver.md
docs/supported_platforms.md

We realized that we don't use `SYS_pidfd_open` anymore.

Remove kernel version requirement

---

docs/shadow_config_spec.md

Forgot to update this in #2019.

Fix default value of 'use_syscall_counters' in docs

---

src/main/bindings/rust/wrapper.rs
src/main/core/controller.c
src/main/core/main.rs
src/main/core/manager.c
src/main/core/manager.h
src/main/core/support/configuration.rs
src/main/host/process.c
src/main/host/thread.c
src/main/host/thread.h
src/main/host/thread_preload.c
src/main/host/thread_protected.h
src/main/utility/mod.rs

- simplified logging initialization
- moved log buffering decision from controller to main fn
- moved tilde expansion unit test to the utility module
- use the plugin path rather than argv[0] for execvpe()
- removed unused 'runTimer' field from controller
The following changes are in preparation for moving the controller to rust.
- set the host CPU frequency in the manager
- manager reads the bootstrap end time directly from config

Simplified the logging init, and other small code simplifications 

---

src/main/bindings/rust/CMakeLists.txt
src/main/bindings/rust/wrapper.rs
src/main/core/controller.rs
src/main/core/sim_config.rs
src/main/utility/utility.c
src/main/utility/utility.h

This reverts commit 67badb26a66093807b98b583135035c4927942ef.
This will affect simulation results and performance, resulting in similar results/performance to https://github.com/shadow/benchmark-results/tree/master/tor/2022-06-13-T21-20-02.

Revert "Change random/seed/ordering behaviour to match older Shadow"

---

src/Cargo.lock
src/main/Cargo.toml
src/main/bindings/c/bindings.h
src/main/utility/mod.rs
src/main/utility/utility.c

The rust backtrace has better symbol resolution.
Example:
```
**ERROR ENCOUNTERED**
At process: 3260702 (parent 3260700)
At file: /shared/code/shadow/rust-backtrace/src/main/host/process.c
At line: 501
At function: _process_openStdIOFileHelper
Message: Assertion failed: 0
**BEGIN BACKTRACE**
0: backtrace
at /shared/code/shadow/rust-backtrace/src/main/utility/mod.rs:245:33
1: utility_handleError
at /shared/code/shadow/rust-backtrace/src/main/utility/utility.c:110:29
2: _process_openStdIOFileHelper
at /shared/code/shadow/rust-backtrace/src/main/host/process.c:501:5
3: _process_start
at /shared/code/shadow/rust-backtrace/src/main/host/process.c:540:5
4: _process_runStartTask
at /shared/code/shadow/rust-backtrace/src/main/host/process.c:751:5
5: …
```

Replace 'execinfo.h' backtrace with a rust-generated backtrace

---

src/main/bindings/c/bindings.h
src/main/bindings/rust/wrapper.rs
src/main/host/descriptor/descriptor.c
src/main/host/descriptor/descriptor.h
src/main/host/descriptor/descriptor_table.rs
src/main/host/descriptor/descriptor_types.h
src/main/host/descriptor/epoll.c
src/main/host/descriptor/mod.rs
src/main/host/descriptor/regular_file.c
src/main/host/descriptor/socket.c
src/main/host/descriptor/tcp.c
src/main/host/descriptor/tcp_cong_reno.c
src/main/host/descriptor/timerfd.c
src/main/host/network_interface.c
src/main/host/process.rs
src/main/host/syscall/file.c
src/main/host/syscall/fileat.c
src/main/host/syscall/mman.c
src/main/host/syscall/protected.c
src/main/host/syscall/socket.c
src/main/host/syscall_condition.c
src/main/host/tracker.c
src/main/host/tracker.h

The `LegacyDescriptor` struct combines the file descriptor and file description into a single object by combining the fd handle and CLOEXEC flag with the underlying file object. This forces them to have a 1:1 relationship, where they should have a n:1 relationship for n>=0 (any number of file descriptors for a file description).
This PR is a step towards removing this 1:1 relationship and towards supporting #1648. A follow-up PR will allow multiple fds for a `LegacyDescriptor`.

Remove handle field from `LegacyDescriptor`

---

src/main/host/memory_manager/memory_mapper.rs

This significantly reduces the number of warnings in tests, and I think it's expected that a null pointer address wouldn't be mapped into shadow.

Don't warn if null pointer address isn't mapped into shadow

---

src/main/bindings/c/bindings.h
src/main/bindings/rust/wrapper.rs
src/main/core/controller.rs
src/main/core/manager.c
src/main/core/manager.h
src/main/core/sim_config.rs
src/main/core/worker.c
src/main/core/worker.h
src/main/host/descriptor/tcp.c

The manager accesses `Host` objects without acquiring the hosts' locks, which is not safe.
Edit:
The simulation results have changed slightly in this PR, so I will try to investigate where this difference is from.
Edit 2:
With the workaround commit, the results are the same. We can revert that commit in a new PR.

Fix unsafe accesses of host objects from the manager

---

src/main/bindings/c/bindings-opaque.h
src/main/bindings/c/bindings.h
src/main/bindings/rust/wrapper.rs
src/main/core/controller.rs
src/main/core/manager.c
src/main/core/manager.h
src/main/core/scheduler/scheduler.c
src/main/core/worker.c
src/main/utility/status_bar.rs

Main changes:
- removed unnecessary complexity from the manager and scheduler
- removed `manager` field from the scheduler
- moved the status bar and plugin error count to the controller (the intended design is that the simulation may have multiple managers and a single controller, so the controller seems like a better place for these)

Changes to controller, manager, and scheduler

---

src/main/bindings/c/bindings.h
src/main/bindings/rust/wrapper.rs
src/main/core/manager.c
src/main/core/manager.h
src/main/core/scheduler/scheduler.c
src/main/core/scheduler/scheduler.h
src/main/core/support/configuration.rs
src/main/core/worker.c
src/main/core/worker.h
src/main/core/worker.rs
src/main/host/descriptor/tcp.c

These changes are to prepare for the rust migration of the `Manager`.
- Workers now add their local counters to the global counters --- Rather than having each worker add its counters to the manager through the global worker pool, each worker now adds its counters to the global counters and the manager then later reads from the global counters.
- Worker pool now accesses the controller, pid watcher, and config directly --- This is work towards making the controller/manager/scheduler/workerpool more composable and to limit parent references.

More organization changs to the manager / worker pool

---

src/main/shmem/shmem_allocator.c
src/main/shmem/shmem_file.c

Replace usage of `ftruncate` with `posix_fallocate`. `ftruncate` sets
the size of a file without actually allocating the backing storage,
which is allocated on-demand. While this allows the true allocation to
be "lazy", and thereby allows us to do large allocations without wasting
resources if the whole allocation isn't used, it can cause unpredictable
and confusing failure modes.
With `posix_fallocate`, the space is eagerly allocated. If the call
succeeds, we are guaranteed that the storage is actually available.
When we run out of storage, the call fails and we can fail with a clear
error message.
We were previously allocating quite-large chunks of memory at a time;
about 132 MB. While this probably wouldn't actually cause problems for a
single shadow simulation (which typically only …

Pre-allocate space in shared memory files

---

CHANGELOG
src/main/host/timer.rs
src/test/timerfd/test_timerfd.c

Definitely a bug; might be the root cause of https://github.com/shadow/tgen/issues/35

Ensure timerfd_settime resets expiration count

---

CHANGELOG
src/lib/shim/patch_vdso.c

Add support for smaller VDSO trampolines (13 bytes -> 5 bytes). This fixes panics in Ubuntu 22.04, whose vdso functions are already just 5-byte trampolines into internal functions (#2273)
Also adds some tests with an Ubuntu 22.04 kernel to the CI.

Add support for smaller vdso trampolines

---

CMakeLists.txt

Adding the `--always` tag allows `git describe` to succeed even if
a relevant tag can't be found. e.g. in the case of a shallow checkout
without tags it results in a version string like "5a6993e" instead of
the hard-coded version number "v2.1.0", which is misleading.

shadow version string: get commit hash and dirty status more robustly

---

CHANGELOG
src/main/host/timer.rs
src/test/timerfd/test_timerfd.c

Fairly sure this will fix https://github.com/shadow/tgen/issues/35

timerfd: ensure previously scheduled events are cancelled when re-arming

---

src/lib/shim/shim_api_addrinfo.c

Fix `getaddrinfo()` error on some systems

---

.github/workflows/run_tests.yml

* Add some configurations that run with a newer kernel, to help catch kernel incompatibilities such as https://github.com/shadow/shadow/issues/2273
* Only test clang in a couple configurations, to cut down the CI matrix a bit.

Tweak shadow tests CI matrix

---

.github/workflows/run_tests.yml
ci/run.sh
docs/supported_platforms.md

Ubuntu 21.10 is EOL. The upgrade path for Ubuntu 21.10 is to 22.04, which is already in the CI.
Ubuntu 22.10 is not scheduled to be released until October 20, 2022.
https://wiki.ubuntu.com/Releases
Fedora 34 is EOL. Fedora 35 and 36 are still supported.
https://docs.fedoraproject.org/en-US/releases/eol/
Closes #2307

Remove EOL distros from CI and docs

---

.github/workflows/run_tests.yml
ci/run.sh
docs/supported_platforms.md

This reverts commit ea7336d7c4ba937656d56dd8cbac545b2470bfac.
We should try to keep supported versions between minor releases, see #2309

Revert "Remove EOL Fedora 34"

---

.github/workflows/run_tests_incremental.yml
ci/run.sh
docs/ci.md

Adds a new workflow `run_tests_incremental.yml`, based on `run_tests.yml`.
When run manually, it gives the option of building and pushing Docker images with all dependencies installed, and a build of Shadow.
In other cases, it tries to *pull* such an image, and do an incremental build on top of the build baked into the image. In case the image can't be pulled, it falls back to building the image from scratch (but doesn't try to push to Dockerhub).
Note that no images exist yet in the `shadowsim:shadow-ci` repository, so in the runs on this PR it'll fall back to building images from scratch. We won't see the benefit until after merging this PR and doing a manual run that builds and pushes images.
The tentative plan is to *not* change the required tests when merging this PR. i.e. this adds …

Add shadow test workflow with incremental builds

---

src/Cargo.lock
src/main/Cargo.toml

We don't use the "macro" feature, so this removes some dependencies and probably slightly improves the build time.
```diff
diff --git a/tmp/tree-before b/tmp/tree-after
index f69469c..1a6846e 100644
--- a/tmp/tree-before
+++ b/tmp/tree-after
@@ -160,23 +160,7 @@ shadow-rs v2.2.0
│       └── serde v1.0.140 (*)
├── serde v1.0.140 (*)
├── serde_with v2.0.0
-│   ├── serde v1.0.140 (*)
-│   └── serde_with_macros v2.0.0 (proc-macro)
-│       ├── darling v0.14.1
-│       │   ├── darling_core v0.14.1
-│       │   │   ├── fnv v1.0.7
-│       │   │   ├── ident_case v1.0.1
-│       │   │   ├── proc-macro2 v1.0.40 (*)
-│       │   │   ├── quote v1.0.20 (*)
-│       │   │   ├── strsim v0.10.0
-│       │   │   └── syn v1.0.98 (*)
-│       │   └── darling_macro v0.14.1 (proc-macro)
-│       │       ├── …
```

Remove the 'macro' feature for 'serde_with'

---

CHANGELOG
src/lib/shim/shim_rdtsc.c
src/test/regression/test_busy_wait.rs

Previously the rdstc emulation code directly retrieved and returned the
simulated time.
This change uses an emulated syscall to get the time, ensuring that when
`model_unblocked_syscall_latency` is enabled, we correctly move
simulated time forward and yield if enough time has passed.
Fixes https://github.com/shadow/shadow/discussions/2299#discussioncomment-3198368

Handle busy-loops that only use rdtsc

---

docs/shadow_config_spec.md
src/main/bindings/c/bindings-opaque.h
src/main/bindings/c/bindings.h
src/main/bindings/rust/wrapper.rs
src/main/core/support/configuration.rs
src/main/core/support/emulated_time.rs
src/main/core/support/simulation_time.rs
src/main/host/descriptor/tcp.c
src/main/host/host.c
src/main/host/host.h
src/main/host/network_interface.c
src/main/host/network_interface.h
src/main/host/network_queuing_disciplines.c
src/main/host/network_queuing_disciplines.h
src/main/network/router/mod.rs
src/main/network/router/token_bucket.rs
src/main/routing/router.c
src/main/routing/router.h

This is the first step in rewriting the network interface and router in rust.
Most of the network interface C code that is changed here will be removed in my upcoming pull requests, so I'm not spending much effort to optimizing the code or it's design at this point.
Progress on #1727

Refactor token bucket from netiface to a rust module

---

docs/shadow_config_overview.md
docs/shadow_config_spec.md
src/Cargo.lock
src/main/Cargo.toml
src/main/core/main.rs
src/main/core/support/configuration.rs

- [merge keys](https://yaml.org/type/merge.html): not technically valid yaml 1.2, but is common enough that I don't think it hurts to support it
- [extension fields](https://docs.docker.com/compose/compose-file/#extension): fields beginning with "x-" that are ignored; this follows the convention of docker compose, but we only allow them at the top level of the document
This is technically a breaking change since "<<" was previously an allowed shadow hostname, but this isn't generally a valid hostname and I don't think is worth worrying about.
These are currently activated by a `--use-extended-yaml true` option.

Support yaml merge keys and extension fields

---

src/main/bindings/rust/CMakeLists.txt
src/main/bindings/rust/wrapper.rs
src/main/core/manager.rs
src/main/core/scheduler/scheduler.c
src/main/core/scheduler/scheduler.h
src/main/core/scheduler/scheduler_policy.h
src/main/core/scheduler/scheduler_policy_host_single.c
src/main/core/work/event.c
src/main/core/work/event.h
src/main/core/worker.c
src/main/core/worker.h
src/main/host/host.c
src/main/host/host.h

I think it's better to pass the `Host` into the `Event` when running the event. The reference counts for `Scheduler` and `SchedulerPolicy` were unused.

Remove src/dst host pointers from `Event`, and reference counts from `Scheduler` and `SchedulerPolicy`

---

src/main/utility/perf_timer.rs

I think we should have this to help prevent the compiler from reordering the start and stop operations relative to the code that's being measured. I'm not sure if it's sufficient, but I think is better than not having it.

Add compiler fence to `PerfTimer`

---

src/test/golang/CMakeLists.txt

There seems to be a nondeterministic bug when building the golang
targets, presumably due to a race condition. Seeing if building those
targets serially fixes it.
Ran the "Shadow Tests Incremental" twice without any failures, which seems promising.
See https://github.com/shadow/shadow/issues/2341

Force golang tests to build serially

---

src/main/bindings/rust/wrapper.rs
src/main/core/worker.c
src/main/core/worker.rs
src/main/host/descriptor/tcp.c
src/main/host/host.c
src/main/host/host.h
src/main/host/host.rs
src/main/host/network_interface.c
src/main/host/process.c
src/main/host/syscall_condition.c
src/main/host/timer.rs
src/main/host/tracker.c

New tasks should be added to the host rather than the worker. In this PR the host simply passes the tasks on to the worker, but in the future the host may want to handle these tasks internally without involving the global worker. The current plan is to move the event queue into the host itself.

Add tasks to the host instead of the worker

---

src/main/core/scheduler/scheduler.c
src/main/core/scheduler/scheduler_policy.c
src/main/core/scheduler/scheduler_policy.h

Haven't seen any crashes caused by this, but it's definitely a bug.
**Edit:** The nightly benchmark failed, possibly due to this.
```
Progress: 44% — simulated: 00:08:00/00:18:00, realtime: 01:30:00, processes failed: 0
Progress: 45% — simulated: 00:08:01/00:18:00, realtime: 01:31:00, processes failed: 0
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', main/core/support/emulated_time.rs:62:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
2022-08-10 05:44:57 1660110297.418442 [tornettools] [INFO] Cleaning up
2022-08-10 05:44:58 1660110298.407282 [tornettools] [INFO] Done simulating; shadow returned code '-6'
Error: -10 05:44:58 1660110298.423163 [tornettools] [ERROR] Shadow …
```

Fix use-after-free in scheduler

---

src/main/bindings/rust/wrapper.rs
src/main/host/host.h
src/main/host/network_interface.h
src/main/routing/router.c
src/main/routing/router.h
src/main/routing/router_queue_codel.c

Cleanup while migrating Host to Rust.

router_new: take NetworkInterface* instead of void*

---

src/main/host/host.c
src/main/host/network_interface.c
src/main/host/network_interface.h

Cleanup while working on migrating Host to Rust.

networkinterface_new: don't take Host*

---

src/main/bindings/c/bindings.h
src/main/bindings/rust/CMakeLists.txt
src/main/bindings/rust/wrapper.rs
src/main/core/manager.rs
src/main/core/scheduler/scheduler.c
src/main/core/scheduler/scheduler.h
src/main/core/scheduler/scheduler_policy.c
src/main/core/scheduler/scheduler_policy.h
src/main/core/work/event.rs
src/main/core/work/event_queue.rs
src/main/core/worker.c
src/main/core/worker.h
src/main/core/worker.rs
src/main/host/host.c
src/main/host/host.h
src/main/host/host_parameters.h

In this PR the event processing has been simplified and moved into the host object. Each host's event queue is reference counted and stored by both the host and the global scheduler. This allows the host to access the event queue when adding local events or when processing/iterating events, and allows other hosts to add packet events through the global worker without needing to acquire the destination host's lock.
The future plan is:
1. Rather than having the worker add packet events directly to a host's event queue, the worker will store pending packet events in separate per-host queues, and once the current scheduling round completes, those packet events will be popped from the queues and added to their respective host event queues. This will allow us to remove both reference counting …

Move the event queue into the host object

---

CHANGELOG
src/main/host/syscall/mman.c
src/test/memory/test_mmap.rs

When the plugin mmaps a file opened with `O_NOFOLLOW`, shadow cannot open the file for plugin and return error for mmap.
example.c:
```c
#include <sys/mman.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdlib.h>
#include <unistd.h>
#define errExit(msg)    do { perror(msg); exit(EXIT_FAILURE); \
} while (0)
int main() {
int fd = open("file", O_CREAT|O_NOFOLLOW|O_RDWR, 0666);
if (fd == -1) {
errExit("open");
}
int size = 32;
if (ftruncate(fd, size) == -1) {
errExit("ftruncate");
}
void *addr = mmap(NULL, size, PROT_READ, MAP_SHARED, fd, 0);
if (addr == MAP_FAILED) {
errExit("mmap");
}
return 0;
}
```
Running the above code will produce shadow log:
```
[memory_mapper.rs:499] [shadow_rs::host::memory_manager::memory_mapper] Handling mmap …
```

Remove O_NOFOLLOW flag when mmap file in plugin

---

src/main/bindings/c/bindings.h
src/main/bindings/rust/wrapper.rs
src/main/core/controller.rs
src/main/core/manager.rs
src/main/core/worker.c
src/main/core/worker.h
src/main/core/worker.rs
src/main/host/descriptor/tcp.c
src/main/host/syscall/socket.c
src/main/network/network_graph.rs

The `Controller` is currently globally accessible through the global worker pool, but since the controller exists on the stack, this is not allowed in rust (unless we use `Box::leak`). This breaks out some of the global state into a new global object. Accesses to this global state is made explicit through a `worker::WORKER_SHARED` static variable.

Move some of `Controller`'s global state to the worker module

---

src/main/core/worker.rs

When I fixed #2361 after the comments I didn't check code warnings before merging.

Fixed warning about unneeded `unsafe` from #2361

---

src/main/bindings/c/bindings-opaque.h
src/main/bindings/c/bindings.h
src/main/bindings/rust/wrapper.rs
src/main/core/controller.rs
src/main/core/manager.rs
src/main/core/mod.rs
src/main/core/scheduler/mod.rs
src/main/core/scheduler/runahead.rs
src/main/core/scheduler/scheduler.c
src/main/core/scheduler/scheduler.h
src/main/core/worker.c
src/main/core/worker.h
src/main/core/worker.rs

This is the last part of the controller that is accessed globally, and lets us remove the controller pointer from the global worker pool.

Move the runahead data from `Controller` to `WorkerShared`

---

src/main/utility/count_down_latch.c

From the documentation:
> When using condition variables, it is possible that a spurious wakeup may occur (ie: g_cond_wait() returns even though g_cond_signal() was not called). It’s also possible that a stolen wakeup may occur. [...] For this reason, g_cond_wait() must always be used in a loop.

Protect `CountDownLatch` against spurious wakeups

---

src/main/bindings/rust/wrapper.rs
src/main/host/process.c
src/main/host/process.h
src/main/host/syscall/futex.c
src/main/host/syscall/kernel_types.h
src/main/host/syscall/process.c
src/main/host/syscall/time.c
src/main/host/syscall_handler.c

This is primarily to fix https://github.com/shadow/shadow/issues/2368
* Emulate PR_SET_DUMPABLE instead of allowing it to execute natively, which interferes with Shadow's ability to access managed process memory.
Some other minor improvements:
* Return an error for some other prctl operations that would interfere with Shadow
* Add explicit cases for all known prctl operations, and return errors for any others.
* Enable the getgroups syscall to just execute natively.
* Add explicit cases for the unimplemented sched_getaffinity and sched_setaffinity syscalls, so that the logged warnings give the syscall names instead of just the numbers.
* Fix clock_gettime and futex syscalls to handle the cases where a bad user pointer is provided.

Emulate PR_SET_DUMPABLE and misc improvements

---

.github/workflows/coverage.yml
.github/workflows/docker.yml
.github/workflows/run_tests.yml
.github/workflows/run_tests_incremental.yml
.github/workflows/run_tor.yml

The 18.04 VM image is now deprecated.
https://github.com/actions/runner-images/issues/6002

workflows: Replace usage of ubuntu 18.04 image with 20.04

---

src/main/core/controller.rs
src/main/core/manager.rs
src/main/core/worker.rs

- wraps the global shared state (`WORKER_SHARED`) in an `AtomicRefCell` so that we can drop the state when the simulation ends
- adds a borrowed reference to the shared global state to the thread-local global state (`WORKER`) to reverse any performance impact caused by the `AtomicRefCell`

Improve design of rust global shared state

---

src/main/bindings/c/bindings.h
src/main/bindings/rust/CMakeLists.txt
src/main/bindings/rust/wrapper.h
src/main/bindings/rust/wrapper.rs
src/main/core/controller.rs
src/main/core/manager.rs
src/main/core/scheduler/scheduler.c
src/main/core/scheduler/scheduler.h
src/main/core/work/event_queue.rs
src/main/core/worker.c
src/main/core/worker.h
src/main/core/worker.rs
src/main/host/descriptor/tcp.c
src/main/host/host.rs
src/main/utility/childpid_watcher.rs

These changes allow us to remove the `WorkerPool`s pointers to the `Scheduler` and the `ConfigOptions`, which brings us a step closer to being able to write the scheduler and work pool in rust. The manager is becoming a bit overloaded with stuff, but it'll be easier to reorganize things later once it's all in rust.

Move more global state to the worker module

---

src/main/bindings/rust/wrapper.rs
src/main/core/controller.rs
src/main/core/manager.rs
src/main/core/scheduler/scheduler.c
src/main/core/scheduler/scheduler.h

We'll want to change the shuffle method to a rust method at some point, and by changing only the shuffle method now (the shuffle is changed from C to rust), we can isolate simulation performance changes due to the different host order and not conflate it with other changes.
I also think shuffling in the manager makes more sense anyways.

Change host shuffle method to rust

---

src/Cargo.lock
src/main/Cargo.toml

The [shadow/bytes](https://github.com/shadow/bytes) repository has been updated, and this points shadow to the new commit.

Updates the forked-from commit for bytes from 1.1.0 to 1.2.1

---

CMakeLists.txt
src/main/utility/rpath.c

We probably especially want this if we decide to release pre-built binaries ourselves (#2389), but even if we don't, it gives users some additional flexibility.
Make shadow installation directory relocatable

Make shadow installation directory relocatable

---

src/Cargo.lock
src/lib/shadow-shim-helper-rs/Cargo.toml
src/lib/shadow-shim-helper-rs/src/lib.rs
src/lib/shadow-shim-helper-rs/src/scmutex.rs
src/main/core/support/units.rs

This is a Mutex suitable for use in shared memory.
* Has a fixed layout (repr(C))
* Self-contained (no pointers)
* Works across processes (e.g. doesn't use FUTEX_PRIVATE_FLAG)
I've also implemented `rkyv::Archive` and `rkyv::Serialize` for it. This facilitates using it inside of types meant to be serialized with rkyv. That in turn may be useful for safely managing shared memory.

Add SelfContainedMutex

---

.github/workflows/sanitizers.yml
src/lib/syscall-logger/src/lib.rs
src/main/core/support/configuration.rs
src/main/host/descriptor/mod.rs
src/main/host/syscall/format.rs
src/main/utility/childpid_watcher.rs
src/main/utility/interval_map.rs
src/main/utility/proc_maps.rs
src/test/test_utils.rs

This seems like a good idea with our increasing adventures into `unsafe`-land
While putting this together I found that we're not actually running tests in our rust crates that don't have a cmake target. This runs them "by accident" since I'm invoking cargo directly, and I made a couple small corresponding fixes.  It'd probably be good to ensure those run via `setup test` as well, but I think that'll be a separate PR.

Run tests under Miri in CI

---

src/main/utility/mod.rs
src/main/utility/synchronization/count_down_latch.rs
src/main/utility/synchronization/mod.rs
src/main/utility/synchronization/semaphore.rs

Adds the synchronization primitives (semaphore and count down latch) needed for the rust scheduler.
This count down latch is a little more complex than the C version since it supports multiple waiters. The main difficulties of using multiple waiters in the C version are:
1. There isn't a nice way to synchronize which waiting thread will reset the latch, since it must always be the last waiting thread that resets the latch.
2. If the waiters are modified so that the waiting thread that last takes the lock is the one to reset the latch, it leads to a new issue where the waiting threads could be notified, and one thread resumes and loops all the way back to the wait again before the other threads have a chance to resume.

Add rust synchronization primitives needed for the scheduler

---

src/main/utility/synchronization/semaphore.rs

```
error: unsupported operation: can't call foreign function: sem_init
--> main/utility/synchronization/semaphore.rs:85:18
|
85  |         unsafe { libc::sem_init(self.inner.get(), 0, val) };
|                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't call foreign function: sem_init
|
= help: this is likely not a bug in the program; it indicates that the program performed an operation that the interpreter does not support
= note: BACKTRACE:
= note: inside `utility::synchronization::semaphore::LibcSemWrapper::init` at main/utility/synchronization/semaphore.rs:85:18
note: inside `utility::synchronization::semaphore::LibcSemaphore::new` at main/utility/synchronization/semaphore.rs:30:18
```

Exclude semaphore tests from miri

---

src/main/host/syscall/handler/mod.rs
src/main/network/router/token_bucket.rs
src/main/utility/byte_queue.rs
src/main/utility/counter.rs

I guess moving the value from inside to outside of the unsafe block counts as "using" the value, so the warning goes away.

Fix Box::from_raw `unused_must_use` warning in rust 1.64

---

src/CMakeLists.txt
src/main/lib.rs

Accidentally dropped running any rust unit tests in https://github.com/shadow/shadow/pull/2404
We were also previously not running doc tests, and I think not running tests for any crates for which we don't build a `staticlib` for C code to link to. (I'm not sure whether there were any such tests before, but there increasingly will be)
For simplicity and maintainability I just invoke `cargo test` now, instead of trying to directly run the test executables. While the cargo behavior of always rebuilding (if needed) may be slightly surprising, this approach should be more robust and maintainable.

Run rust unit tests (including doc tests)

---

CMakeLists.txt

* Opt into policies introduces since our minimum version (3.2)
* Opt *out* of policy CMP0075 since not all of our supported cmake versions support it.

Configure cmake policies

---

src/lib/shadow-shim-helper-rs/src/lib.rs
src/lib/shmem/src/lib.rs
src/lib/tsc/src/lib.rs
src/main/lib.rs

This is a more idiomatic solution for ensuring crates only referenced via C code are actually linked, as per
https://github.com/rust-lang/cargo/issues/9391

Use "extern crate" to force linking otherwise-unused crates

---

.github/workflows/lint.yml
src/lib/shadow-shim-helper-rs/shim_helper.h
src/lib/shadow-shim-helper-rs/src/signals.rs
src/lib/shadow-shim-helper-rs/src/simulation_time.rs
src/main/utility/synchronization/count_down_latch.rs

Linting the code documentation might be a little over-the-top, but I don't think it will be that bad and it makes sure that our documentation links are correct.

Lint rust documentation in CI

---

src/Cargo.lock
src/lib/logger/Cargo.toml
src/lib/shadow-build-common/Cargo.toml
src/lib/shadow-shim-helper-rs/Cargo.toml
src/lib/shmem/Cargo.toml
src/lib/tsc/Cargo.toml
src/main/Cargo.toml

Seems to significantly reduce the time to build Shadow's C code. For example:

Run C compiler in parallel

---

CMakeLists.txt
src/test/CMakeLists.txt

These are redundant for the C code built via Cargo, but still needed for the few remaining C modules built via cmake, including the openssl preload library.

cmake: set C compiler debug/release flags globally

---

src/Cargo.lock
src/main/Cargo.toml
src/main/core/support/configuration.rs

Some of the changes seem to have been reverted between the v4 rc and this current v4.0.8, so less changes were required than I was expecting.
Unfortunately this adds a bunch of windows dependencies to the lock file, but not much we can do about that.
Short help output changes (whitespace ignored):
```diff
diff --git a/help-clap-3 b/help-clap-4
index 9548607..fcbb67b 100644
--- a/help-clap-3
+++ b/help-clap-4
@@ -1,69 +1,60 @@
-Shadow v2.2.0-322-gf49f6e02-dirty 2022-10-03--11:07:21
Run real applications over simulated networks.
For documentation, visit https://shadow.github.io/docs/guide
-USAGE:
-    shadow [OPTIONS] [CONFIG]
+Usage: shadow [OPTIONS] [CONFIG]
-ARGS:
-    <CONFIG>    Path to the Shadow configuration file. Use '-' to read from stdin
+Arguments:
+  [CONFIG]  Path to the …
```

Upgrade from clap 3 to 4

---

src/CMakeLists.txt

I haven't been able to find clear documentation about when cargo does/doesn't enable host extended CPU features, but it seems plausible that explicitly setting the target might disable them.
In any case it probably makes sense to only use this workaround in the coverage build, where we actually need it.

Only set an explicit target platform on coverage builds

---

src/main/core/main.rs

This uses coloring and underlining in clap's help output (including help error messages).
Example:

Use formatted help output

---

src/main/core/manager.rs
src/main/cshadow.rs
src/main/host/host.c
src/main/host/host.h
src/main/host/host.rs

Now that the hosts are managed in rust code, this lock isn't needed.

Remove host lock

---

src/main/network/network_graph.rs

This test failed in the CI again, even with the rust version pinned (#2427). This seems to be caused by https://github.com/rayon-rs/rayon/issues/952.
```
Error: Undefined Behavior: deallocating while item [SharedReadOnly for <5756175>] is protected by call 1624160
--> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/registry.rs:479:9
|
479 |         })
|         ^ deallocating while item [SharedReadOnly for <5756175>] is protected by call 1624160
|
= help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
= help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
= note: BACKTRACE:
= note: inside …
```

Disable 'test_shortest_path' test under miri

---

src/main/host/syscall/uio.c

This fixes a part of #2379, and fixes #2452. No tests were added since we do have uio tests, but they're disabled since readv still does not work.

Allow empty iovecs in readv and writev

---

src/lib/shim/shim_api_ifaddrs.c
src/test/ifaddrs/test_ifaddrs.rs

The man page for `getifaddrs()` says this is allowed to be NULL, but some applications/libraries such as libuv assume that this is non-null, so we may as well return something here. It returns a netmask of /8 for localhost and /24 for the public IP.
Fixes the segfault in #2451.

Return a netmask in `getifaddrs()`

---

src/lib/shim/shim_logger.c
src/lib/shim/shim_sys.c

`gmtime_r` is not async-signal-safe, but we should only call async-signal-safe functions from the shim logger. This seems to fix #2457.
https://stackoverflow.com/a/53156211

Replace shim logger's usage of `gmtime_r()`

---

src/CMakeLists.txt

The timeout needs to take into account the time to rebuild shadow.

Extend 'rust-unit-tests' timeout

---

src/lib/libc_preload/gen_syscall_wrappers_c.py
src/lib/libc_preload/libc_impls.c
src/lib/libc_preload/syscall_wrappers.c

libc uses varargs to make the last option, `mode`, optional. When the caller doesn't explicitly provide a `mode`, we were getting unitialized data from the stack, which was sometimes causing the determinism tests to fail.
Fixes https://github.com/shadow/shadow/issues/2466

open, openat: use manual wrappers to make mode deterministic

---

src/Cargo.lock
src/lib/shadow-shim-helper-rs/Cargo.toml
src/lib/shadow-shim-helper-rs/src/scmutex.rs

This addresses a performance regression when using SelfContainedMutex to protect the shim's shared memory.
This adds some atomic operations to track whether anything is sleeping on the mutex, but saves a much more expensive `futex` syscall in the common case of unlocking while there is nothing waiting on it.
I benchmarked this on top of the shim-shared-memory pr in https://github.com/shadow/shadow/pull/2470 to verify the performance gain (well, lack of performance regression from switching from pthread_mutex to SelfContainedMutex)

SelfContainedMutex: avoid wake operations when there are no waiters

---

CHANGELOG
docs/shadow_config_spec.md
src/Cargo.lock
src/main/Cargo.toml
src/main/core/sim_config.rs
src/test/compressed-graph/compressed-graph.yaml
src/test/regression/sigkill_self.yaml
src/test/regression/small_stop_time.yaml
src/test/tor/minimal/CMakeLists.txt

This is a pretty large PR (with some possibly controversial changes) so just tell me what I should remove / change / split up to get this merged.
This PR does the following:
Reimplements `tilde_expansion` as `resolve_path`. It now takes a `&Path`, returns an `anyhow::Result<PathBuf>`, and looks in `$PATH` if input is a standalone string (e.g. `true` will now resolve to `/bin/true`)
Various edits to fix yaml files with absolute paths or relative paths that conflicted with the $PATH lookup.

Allow for sourcing executables from $PATH

---

src/main/core/scheduler/pools/bounded.rs
src/main/core/scheduler/pools/unbounded.rs
src/main/utility/synchronization/mod.rs
src/main/utility/synchronization/thread_parking.rs

The interface of this 'thread_parking' module is a little weird, but it was written this way to support both work pools, which take different approaches to how the flag is shared between threads.
There's no noticeable change in performance when switching from semaphores to park/unpark. On Linux, park/unpark is implemented [with a futex](https://twitter.com/m_ou_se/status/1312803599689355266) so this isn't surprising.
Thread-per-host:
Thread-per-core:

Use thread park/unpark instead of semaphores in work pools

---

.github/workflows/coverage.yml
.github/workflows/run_tests.yml
.github/workflows/run_tor.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Update CI to use new output format

---

src/main/core/worker.rs
src/main/host/context.rs
src/main/host/memory_manager/memory_mapper.rs
src/main/host/memory_manager/mod.rs
src/main/host/thread.rs

* Get rid of the Thread trait, since we don't anticipate needing it anymore.
* Rename to ThreadRef

Refactor Rust Thread

---

CMakeLists.txt
ci/container_scripts/test.sh
docs/compatibility_notes.md
examples/CMakeLists.txt
examples/nginx/CMakeLists.txt
examples/nginx/nginx.conf
examples/nginx/run.sh
examples/nginx/shadow.yaml

This PR makes an "examples" subdirectory where we can add examples, and can run these examples in ctest. The configuration code is also used in the documentation so that we can make sure our documentation is up to date.
I think it's better to have a dedicated "examples" directory rather than putting these in "src/test/" so that we can keep them self-contained, and so that they're easier to find.
In the future it would be nice to also run a CI workflow to test the examples, and to move the remaining examples from the "compatibility notes" documentation here.

Add NGINX example/test

---

CHANGELOG
docs/shadow_config_spec.md
src/main/core/support/configuration.rs

After more benchmarking, it seems that the thread-per-core scheduler is faster than the thread-per-host scheduler in most cases. We ran micro-benchmarks on 7 machines and 20% Tor benchmarks on 2 machines, which show the thread-per-core scheduler performing significantly better in all cases. The only regression is on a 5% Tor benchmark on our benchmark runner, where the thread-per-core performance is slightly worse (and we don't know why).
The following two graphs show the performance difference with a 20% Tor network on two different machines.
On the benchmark runner, it's expected that the thread-per-core scheduler will run slightly slower than the thread-per-host scheduler. Compare the blue "PR #2467 - tcp" line and the green "nightly benchmark" line in an older benchmark:

Change default scheduler to 'thread-per-core'

---

src/main/network/mod.rs
src/main/network/relay/token_bucket.rs
src/main/network/router/codel_queue.rs
src/main/network/router/mod.rs

This PR refactors the token bucket a bit so that we can write unit tests without calling into the worker module, and then adds several unit tests.

Add new token bucket unit tests

---

docs/coding.md
setup

Use `bear`'s `--append` flag to update an existing `compile_commands.json`, so that we can run it on incremental builds as well without erasing entries for files that weren't rebuilt.

setup: Support --compile-commands in incremental builds

---

src/main/core/manager.rs
src/main/core/scheduler/mod.rs
src/main/core/scheduler/thread_per_core.rs
src/main/core/scheduler/thread_per_host.rs

This PR adds unit tests for the thread-per-core scheduler. We can't add them for the thread-per-host scheduler since the unit tests require the scheduler to be generic over the host type, and the thread-per-host scheduler uses a thread-local that cannot be generic.
This also moves the worker functions out of the scheduler and into a helper function in the manager. I think this is good since it makes the manager not dependent on any external code, and it doesn't hide away the worker's global state inside the scheduler, which was something that made the old C scheduler hard to deal with.

Add unit tests for the thread-per-core scheduler

---

.github/dependabot.yml

Run daily, but ignore non-security patch updates. We hope this still keeps the number of new dependabot PRs low.

Set dependabot to ignore patch updates

---

docs/shadow_config_spec.md
src/main/build.rs
src/main/core/manager.rs
src/main/core/sim_config.rs
src/main/core/support/configuration.rs
src/main/core/worker.rs
src/main/host/descriptor/socket.c
src/main/host/descriptor/tcp.c
src/main/host/host.c
src/main/host/host.h
src/main/host/host.rs
src/main/host/host_parameters.h
src/main/host/mod.rs
src/main/host/network_interface.c
src/main/host/network_interface.h
src/main/host/network_interface.rs
src/main/utility/mod.rs
src/test/config/convert/shadow.original.xml
src/tools/convert_legacy_config.py

This PR includes:
- isolating use of network interfaces to the host module
- creating a new network interface rust module (still using the C netif code internally for the time being, to change in future PR)
- moving the interactions with the netif module from `host.c` to `host.rs`
NOTE: There are two places in `host.rs` where we do a potentially unsafe borrow of the internal netif C pointer: the places where we need to trigger the netif to send or receive more packets. I'm merging the current version for two reasons:
1. It keeps the control flow of receives and sends the same as it was before this PR (we cannot keep the same control flow with safe rust because of a double borrow problem)
2. I have another in-progress PR to make the flow safe, but it uses tasks to unwind the stack (to …

Move host handling of network interfaces to rust

---

.github/workflows/ci_maintenance.yml

I think this is the command that will update the `Cargo.lock`, `Cargo.toml`, and include major version bumps?

Add instructions for updating dependencies in CI maintenance workflow

---

.github/workflows/coverage.yml
.github/workflows/run_examples.yml
.github/workflows/run_tests.yml
.github/workflows/run_tor.yml

I think it hasn't been an issue so far since we don't run the regular shadow tests in these workflows, and the mmap test would have failed if we did.

Set executable /dev/shm in all workflows

---

src/main/core/manager.rs
src/main/core/worker.rs

We were forgetting to add the thread-local syscall counters to the shared syscall counter. Also removes some unused ffi code.

Fix sim syscall counters

---

src/Cargo.lock
src/main/Cargo.toml
src/main/core/manager.rs
src/main/core/mod.rs
src/main/core/sim_stats.rs
src/main/core/worker.rs
src/main/utility/counter.rs

Saves the total syscall counters and alloc/dealloc counters to a json file.
Example:
```json
{
"objects": {
"alloc_counts": {
"TaskRef": 18349,
"Event": 8928,
"Packet": 7616,
"Payload": 7316,
"SysCallCondition": 517,
"Timer": 492,
"LegacyDescriptor": 161,
"TCP": 82,
"UDP": 74,
"StatusListener": 26,
"RegularFile": 4,
"NetworkInterface": 2,
"Epoll": 1,
"FutexTable": 1,
"HostCInternal": 1,
"ManagedThread": 1,
"Process": 1,
"Router": 1,
"SysCallHandler": 1
},
"dealloc_counts": {
"TaskRef": 18349,
"Event": 8928,
"Packet": 7616,
"Payload": 7316,
"SysCallCondition": 517,
"Timer": 492,
"LegacyDescriptor": 161,
"TCP": 82,
"UDP": 74,
"StatusListener": 26,
"RegularFile": 4,
"NetworkInterface": 2,
"Epoll": 1,
"FutexTable": 1,
"HostCInternal": 1,
"ManagedThread": 1,
"Process": 1,
"Router": 1, …
```

Save counters to `sim-stats.json` file

---

docs/shadow_config_spec.md
src/main/core/support/configuration.rs

Enables host heartbeat messages. Each host will log its own header, and one line per simulated second.

Enable host heartbeat messages by default

---

src/main/host/host.rs

We thought the chained iterator adapters here would end up being constant time, but it looks like they interfere with eachother s.t. they're not. e.g. a contrived bigger version of this hangs, even in release builds:
```
use std::convert::TryInto;
pub fn main() -> std::process::ExitCode {
let ports = 0..=u64::MAX;
let random_offset = u64::MAX/2;
let start_offset = unsafe { std::ptr::read_volatile(&random_offset) };
let result = ports.clone().cycle().skip(start_offset.try_into().unwrap()).take(u64::MAX.try_into().unwrap()).next().unwrap();
(result as u8).into()
}
```

Host::get_random_free_port: avoid linear-time iterator operations

---

src/main/host/memory_manager/memory_copier.rs
src/main/host/memory_manager/mod.rs
src/main/utility/pod.rs

Progress on https://github.com/shadow/shadow/issues/2555, though maybe we should keep it open until we can fix the unsafe transformations from `&[MaybeUninit<u8>]` to `&[u8]`, which are currently needed to work with nix's wrappers around `process_vm_readv` and `process_vm_writev`.

Fix unsound methods in Pod and cleanup MemoryManager

---

src/main/core/worker.rs
src/main/host/host.rs
src/main/host/syscall/handler/random.rs
src/main/host/syscall/handler/socket.rs

I got this idea from what look like a style guide for `std` development, but now can't find it again :/
Anyway, the idea is to use [impl Trait](https://doc.rust-lang.org/stable/rust-by-example/trait/impl_trait.html) to return borrowed objects, while still isolating the caller from most of the implementation details about how they're stored.
The previous approach of `with_*` hides the implementation details, but forces callers to write a closure, which is sometimes inconvenient or messy.
Using impl Trait involves a little more boilerplate in the accessors, particularly when we want to provide both const and mut options, but not as much as e.g. wrapping references to the cells themselves in newtypes.
This approach also still lets us use `Ref::map` and `RefMut::map` to transform the …

Host accessors: use impl trait instead of taking closures

---

src/main/utility/counter.rs

Apparently inferred bounds like this are frowned upon.

Fix `Counter::sorted_for_display` warning on nightly

---

src/Cargo.lock
src/main/Cargo.toml
src/main/host/descriptor/socket/mod.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/syscall/handler/socket.rs
src/main/utility/mod.rs
src/main/utility/sockaddr.rs

This contains custom `SockaddrStorage` and `SockaddrUnix` types to replace the deprecated nix `SockAddr` types. The nix library does have its own [`SockaddrStorage`](https://docs.rs/nix/latest/nix/sys/socket/union.SockaddrStorage.html) type, and our `SockaddrStorage` is heavily influenced by it, but the nix `SockaddrStorage` and `UnixAddr` types have some issues and limitations which prevent us from using them in Shadow. There has been some progress on improving these (mainly unix socket address support on Linux), but for now it's probably best to use our own types that we can customize however we want, and re-evaluate nix again in the future. Rather than implementing our own types for inet/inet6 addresses, we just use nix's [`SockaddrIn`](https://docs.rs/nix/latest/nix/sys/socket/struct.S …

Custom socket address types to replace deprecated nix `SockAddr`

---

README.md

We don't have a "Tor Tests" workflow anymore. We could add one for "Extra Tests", but I think it's better just to remove it. Also fixed the "Shadow Tests" badge.

Remove "Tor Tests" ci badge from readme

---

.github/workflows/coverage.yml
.github/workflows/extra_tests.yml
.github/workflows/run_tests.yml

* Cache a bit more of ~/.cargo. Unclear whether this ended up being needed in the end, but matches other examples, and didn't seem to increase compressed cache size significantly.
* Key the ~/.cargo cache on the hash of the lock file instead of the current YYYY-MM. This invalidates the cache when our dependencies change, instead of having an increasingly stale cache over the course of the month.
* Use sccache to cache *compiled* dependencies. This ends up only needing ~200 MB of cache, and speeds up the build quite a bit. (~10m-15m -> ~5m)

Extra Tests CI: Improve Rust caching

---

src/main/host/descriptor/tcp.c
src/main/host/descriptor/udp.c
src/main/host/host.rs
src/main/host/network_interface.c
src/main/host/network_interface.h
src/main/host/network_interface.rs
src/main/host/syscall/socket.c

The network interface's association and disassociation methods use `compatsocket_getSocketName` and `compatsocket_getPeerName` to get the local ip/port and peer ip/port when generating the key, but this can be confusing and lead to bugs. For example, the calling code needs to make to set the correct addresses using `compatsocket_setSocketName` and `compatsocket_setPeerName` before associating the socket (setting them after would be a bug), and it's not clear that this requirement exists. Some related issues that come up because of this indirection are https://github.com/shadow/shadow/issues/2590 and https://github.com/shadow/shadow/issues/2592.
This PR changes the network interface to take the ip/ports explicitly instead. This also makes the code more flexible, and makes it easier to …

Update network interface association/disassociation

---

src/main/build.rs
src/main/host/descriptor/descriptor.c
src/main/host/descriptor/mod.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/descriptor/tcp.c
src/main/host/host.rs
src/main/host/process.rs
src/main/host/syscall/handler/ioctl.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/handler/unistd.rs
src/main/host/syscall/socket.c
src/main/utility/legacy_callback_queue.rs
src/main/utility/mod.rs

For most syscalls, we simply call the C syscall handler from the rust syscall handler just like we did before. This lets us incrementally add support for individual syscalls for this `TcpSocket` wrapper.
The `LegacyCallbackQueue` prevents circular borrows when running event listeners. For the `close()` syscall, this prevents a panic where the syscall handler mutably borrows the `TcpSocket`, the inner C `TCP` object changes to the `CLOSED` state, an epoll event listener callback is run, and the callback takes a shared borrow of the `TcpSocket`. Just like we do with the rust file objects, the callback queue allows us to delay callbacks until later.
A temporary `LegacyCallbackQueue` is stored as a thread-local so that the `LegacyDescriptor` can access it without us having to update large …

Add initial version of the `TCP` wrapper

---

src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/syscall/handler/ioctl.rs
src/main/host/syscall/ioctl.c

The forced generic type on `TypedPluginPtr::new` was useful here since originally I didn't specify it, and since functions like `tcp_getInputBufferLength` return an `i64` and the plugin memory is a `i32`, it would have overwritten too many bytes without any kind of warning or error. But since `TypedPluginPtr::new` has the `NoTypeInference` requirement, it failed to compile.

Support `ioctl()` for tcp wrapper

---

src/main/host/descriptor/tcp.c
src/main/host/host.rs
src/main/host/process.c
src/main/host/process.h
src/main/host/process.rs
src/main/host/syscall_condition.c
src/main/host/syscall_handler.c
src/main/host/thread.c
src/main/utility/mod.rs
src/test/Cargo.toml
src/test/itimer/CMakeLists.txt
src/test/itimer/itimer_scheduled_after_exit.yaml
src/test/itimer/test_itimer.rs
src/test/itimer/test_itimer_scheduled_after_exit.rs
src/test/test_utils.rs

This simplifies the migration of Process to Rust.
I had initially planned to used `RootedRc`, and to store `RootedRcWeak` in tasks and to avoid circular references, but I realized the *only* strong reference would currently be in the `Host`. It'll be simpler to avoid exposing the `RootedRc` and `RootedRcWeak` wrappers around `Process` to the C code, and this allows us to do it.
This adds some `BTreeTable` lookups to fetch `Process*`'s from the `Host`'s process table, but these should be quite fast, especially since most simulations use fairly few processes per host. I'll do a benchmark run to verify, though.

Don't refcount Process

---

src/main/core/manager.rs
src/main/host/host.rs

I wanted to move around some of the host's network objects, but it was a little complicated with the `setup()` function, so I moved the code from the `Host::setup()` into `Host::new()`. Hopefully this doesn't overlap with any other WIP changes.

Remove `Host::setup()`

---

docs/system_configuration.md

The parameter "-1" is no longer supported, instead "infinity" should be used. 
From SYSTEMD.RESOURCE-CONTROL(5)   
>  TasksMax=N
>            Specify the maximum number of tasks that may be created in the unit. This ensures that the number of tasks accounted for the unit (see above) stays below a specific limit. This either takes an
>            absolute number of tasks or a percentage value that is taken relative to the configured maximum number of tasks on the system. If assigned the special value "infinity", no tasks limit is
>            applied. This controls the "pids.max" control group attribute. For details about this control group attribute, see Process Number Controller[7].
> 
>            The system default for this setting may be controlled with DefaultTasksMax= in …

Changed systemctl TasksMax Parameter

---

src/main/host/host.rs
src/main/host/network_interface.rs
src/main/host/syscall/handler/socket.rs
src/main/network/mod.rs
src/main/network/net_namespace.rs

This serves two main purposes:
1. Consolidate the host's networking-related code into a new structure.
2. When we have a function like `Socket::bind()` that needs to be able to associate the socket with a network interface, we can pass it just this `NetworkNamespace` object instead of needing to pass the entire `Host`. This provides better encapsulation.

Move host networking to new `NetworkNamespace` object

---

src/main/host/descriptor/regular_file.c

I wanted to avoid comparing with equality to OSFILE_INVALID everywhere, in case we ever want to add other negative error values. Added an inline helper `_fd_isValid` instead.
Most of these checks could probably be omitted altogether in favor of letting the native file operation fail and return EBADF for us or us later failing to find the fd in our descriptor table, but probably not worth changing it right now.
Fixes https://github.com/shadow/shadow/issues/2604

regular_file.c: don't treat 0 as a bad file descriptor

---

src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/descriptor/socket/mod.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/syscall/handler/socket.rs

This passes the network namespace to the socket during the bind call, which isn't how Linux does it (in Linux, sockets hold a reference-counted reference to the network namespace in it's inode), but in Shadow we don't use reference counting on the network namespace and we don't support multiple network namespaces so we need to pass it here.

Support `bind()` for tcp wrapper

---

src/lib/syscall-logger/src/lib.rs
src/main/core/worker.rs
src/main/host/host.rs
src/main/host/memory_manager/mod.rs
src/main/host/process.rs
src/main/host/syscall/format.rs
src/main/host/syscall/handler/eventfd.rs
src/main/host/syscall/handler/fcntl.rs
src/main/host/syscall/handler/ioctl.rs
src/main/host/syscall/handler/random.rs
src/main/host/syscall/handler/sched.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/handler/sysinfo.rs
src/main/host/syscall/handler/time.rs
src/main/host/syscall/handler/unistd.rs

Follow-up to @stevenengler's feedback on https://github.com/shadow/shadow/pull/2612.
* Rename APIs that return borrow-counted objects
* add `#[track_caller]` to borrowing APIs

Rename borrowing accessors

---

src/main/host/syscall/handler/socket.rs

This will hopefully fix an occasional timeout in the `bind-shadow` test. This changes the rust `socket()` and `bind()` syscalls to behave how the C versions do, which should significantly reduce the number of log lines in the `bind-shadow` test.

Changed two debug logs to trace

---

src/main/host/descriptor/socket/inet/mod.rs

When #2611 was merged, it added the first use of rust `InetSocket` objects in the network interface. This seems to have affected the graphs in the tgen benchmark.
I don't think the simulation itself changed, just the tracker ~was~ became broken since only metrics that came from [Shadow](https://github.com/shadow/benchmark-results/blob/master/tgen/2022-12-20-T03-10-21/plots/shadow.results.pdf) changed, but not metrics that came from [tgen](https://github.com/shadow/benchmark-results/blob/master/tgen/2022-12-20-T03-10-21/plots/tgen.viz.pdf).
This PR changes it back to adding the C `LegacySocket` to the network interface instead, which causes the shadow metrics to go back to how they were before.

Add rust `TcpSocket` to network interface as `LegacySocket`

---

docs/extra_tests.md
src/test/tgen/fixed_duration/verify.sh

Lowers the threshold since @stevenengler found that running the tests slightly differently (e.g. changing the host id sort order) will require a lower threshold to pass all of the TGen tests. (I think the only one that requires a lower threshold is `tgen-duration-1mbit_300ms-1000streams-shadow`.)

TGen speed test threshold

---

.github/workflows/extra_tests.yml
docs/compatibility_notes.md
examples/CMakeLists.txt
examples/etcd/CMakeLists.txt
examples/etcd/install_deps.sh
examples/etcd/run.sh
examples/etcd/shadow.yaml

This required small changes to the sim since Ubuntu uses etcd 3.3.x.
- `--log-outputs` to `--log-output`
- `etcdctl put` to `etcdctl set`
- removed `model_unblocked_syscall_latency: true` (this option exacerbates non-determinism issues in shadow, causing the sim to fail sporadically)

Add example (and test) for etcd

---

src/main/host/syscall/formatter.rs
src/main/utility/time.rs

This can be useful when matching the strace log with the shadow log, or for seeing where syscall latency is applied.
Before:
```
00:00:01.000 [tid 1000] socket(Inet, 1, 0) = 3
00:00:01.000 [tid 1000] socket(Inet, 1, 0) = 4
00:00:01.000 [tid 1000] bind(3, 0x7fffffffdc88, 16) = 0
00:00:01.000 [tid 1000] getsockname(3, 0x7fffffffdc88, 16 (0x7fffffffdcf0)) = 0
00:00:01.000 [tid 1000] listen(3, 10) = 0
00:00:01.000 [tid 1000] connect(4, 0x7fffffffddec, 16) = 0
00:00:01.002 [tid 1000] nanosleep(...) = 0
00:00:01.002 [tid 1000] connect(4, 0x7fffffffe14c, 16) = -106 (EISCONN: Transport endpoint is already connected)
00:00:01.002 [tid 1000] close(4) = 0
00:00:01.002 [tid 1000] close(3) = 0
```
After:
```
00:00:01.000097028 [tid 1000] socket(Inet, 1, 0) = 3
00:00:01.000099028 [tid 1000] …
```

Show nanoseconds in strace log

---

docs/shadow_config_spec.md
src/lib/shadow-shim-helper-rs/src/lib.rs
src/lib/shadow-shim-helper-rs/src/option.rs
src/lib/shadow-shim-helper-rs/src/shim_shmem.rs
src/lib/shim/shim_sys.c
src/lib/shim/shim_syscall.c
src/main/host/managed_thread.c
src/main/host/managed_thread.h
src/main/host/process.c
src/main/host/process.rs
src/main/host/thread.c
src/main/host/thread.h
src/test/golang/CMakeLists.txt

Examples of shim-handled syscalls:
```
00:10:00.301000001 [tid 1000] epoll_wait(...) = 1
00:10:00.301000001 [tid 1000] read(7, 0x7ffffffee6d0, 65536) = 1460
000000600301000001 [tid 1000] clock_gettime(...) = 0
00:10:00.301000001 [tid 1000] epoll_wait(...) = 1
00:10:00.301000001 [tid 1000] epoll_wait(...) = 1
00:10:00.301000001 [tid 1000] read(7, 0x7ffffffee6d0, 65536) = 1460
000000600301000001 [tid 1000] clock_gettime(...) = 0
00:10:00.301000001 [tid 1000] epoll_wait(...) = 1
00:10:00.301000001 [tid 1000] epoll_wait(...) = 1
00:10:00.301000001 [tid 1000] read(7, 0x7ffffffee6d0, 65536) = 1460
000000600301000001 [tid 1000] clock_gettime(...) = 0
00:10:00.301000001 [tid 1000] epoll_wait(...) = 1
00:10:00.301000001 [tid 1000] epoll_wait(...) = 1
```
Examples of native syscalls:
``` …
```

Log syscalls that are handled in the shim

---

src/main/core/manager.rs
src/main/core/support/configuration.rs
src/main/host/host.rs
src/main/host/process.rs
src/main/host/syscall/formatter.rs

The `StraceFmtMode` type exists for compatibility with C code (it's better to represent the "off" state as an `Option::None`), so its use has been replaced with `Option<FmtOptions>` in the process, host, and manager code. The `strace_logging_options: Option<FmtOptions>` and `strace_file: Option<File>` fields have been merged into a single `strace_logging: Option<StraceLogging>` field.

Simplify strace logging in `Process`

---

src/lib/syscall-logger/src/lib.rs
src/main/host/syscall/formatter.rs
src/main/host/syscall/handler/file.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/handler/unistd.rs
src/main/host/syscall/type_formatting.rs
src/main/host/syscall_handler.c

In order to display syscall arguments in strace logging, we sometimes need to know the values of multiple syscall arguments. For example to display the byte buffer for `write()`, we need to know both `const void *buf` and `size_t count`. Shadow previously would just read bytes until a nul or a memory access error, but this wasn't correct since the buffer is often not nul-terminated.
To print a byte buffer like the one in `write()`, instead of using `*const libc::c_char` in the `log_syscall()` macro, we now have two types `SyscallStringArg` and `SyscallBufferArg<const LEN_INDEX: usize>` depending on whether the syscall takes a buffer (as in `write()`) or a nul-terminated string (as in `open()`). The constant generic in `SyscallBufferArg` allows us to specify the index of the `count` …

Support displaying more-complex syscall arguments

---

rust-toolchain.toml

This is a point release fixing a security vulnerability. https://blog.rust-lang.org/2023/01/10/Rust-1.66.1.html

Bump Rust to 1.66.1

---

src/main/core/logger/log_wrapper.c
src/main/core/logger/log_wrapper.rs
src/main/core/logger/shadow_logger.rs
src/main/core/main.rs

Previously if a host had a log level higher than the simulation log level, the host log level wouldn't take effect. Now you can specify higher host log levels (for example "trace") even if you specify a lower simulation log level (for example "info").
Closes #2643.
This doesn't appear to have any effect on runtime.
https://github.com/shadow/benchmark-results/tree/master/tor/2023-01-06-T17-24-59

Allow higher-level host log levels

---

src/main/host/host.rs
src/main/host/process.rs
src/main/host/syscall/handler/sched.rs
src/main/host/thread.rs

Fix `sched_{get,set}affinity` bug

---

src/test/socket/bind/CMakeLists.txt

This has been timing out occasionally in CI on debug builds. It doesn't seem to have gotten slower in release builds, and doesn't have any obvious culprits in `perf`.

bind-shadow test: extend timeout

---

src/main/host/descriptor/epoll.c
src/main/host/descriptor/tcp.c
src/main/host/syscall/epoll.c
src/main/host/syscall/protected.c

See https://github.com/shadow/shadow/issues/1101#issuecomment-1376485378. Also adds a check for closed files in `epoll_control()` since TCP sockets are no longer always treated as `LegacyFile`s (they are now sometimes wrapped as rust file objects).

 Remove unneeded workaround in `syscallhandler_epoll_ctl`

---

src/main/host/syscall/type_formatting.rs

Small improvements to the syscall string logging in `fmt_string` to make it more readable, and more similar to `fmt_buffer`. Also added an optional `len` argument since some syscalls that take string arguments can also have a length argument (for example `getsockopt` with `TCP_CONGESTION`).
I tried using the memory manager's string methods (`copy_str_from_ptr`) but these don't return partial strings when a NUL isn't found so they can't be used here. I think the current method should be of similar performance (it iterates over a `ProcessMemoryRef`), only it does an extra `String` allocation. We could have a stack-allocated `u8` array and cast it to a `&str` at the end, but I'm not sure it's worth it here.

Improve strace string logging

---

src/main/core/main.rs

See https://shadow.github.io/docs/guide/compatibility_notes.html#notes-6 for an example where this causes issues:
> ### Notes
>
> 1, Shadow must be run as a non-root user since opentracker will attempt to drop privileges if it detects that the effective user is root.

Warn if running with root privileges

---

src/main/host/descriptor/compat_socket.c
src/main/host/descriptor/compat_socket.h
src/main/host/descriptor/socket.c
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/descriptor/tcp.c
src/main/host/network_interface.c
src/main/host/tracker.c
src/main/host/tracker.h

This adds support for `InetSocket` in the tracker, ~and reverts the change from #2626~.

Support `InetSocket` in the tracker

---

src/lib/shadow-shim-helper-rs/ipc.cc
src/lib/shadow-shim-helper-rs/ipc.h
src/lib/shadow-shim-helper-rs/shim_event.h
src/main/host/managed_thread.c

* Rename SHD_SHIM_EVENT_STOP to SHD_SHIM_EVENT_PROCESS_DEATH
* Handling SHD_SHIM_EVENT_PROCESS_DEATH: mark whole process as dead
We inject a SHD_SHIM_EVENT_PROCESS_DEATH event into each individual
managed thread when we detect the process has died.
In https://github.com/shadow/shadow/issues/2674, this ended up causing
the memory write inside Process::reap_thread to fail. Since the process
has died, we don't need to do that write at all; marking the process as
dead correctly skips this step.
I tried to write a regression test but was unable to reproduce the
issue. As in the mongodb case, I set it up so that a child thread
called `abort` while the thread group leader was blocked. In both cases,
we end up trying to use the thread group leader to do the write, but it
is in a zombie state …

Multithread death

---

src/main/host/descriptor/descriptor_table.rs
src/main/host/process.rs
src/main/host/syscall/handler/eventfd.rs
src/main/host/syscall/handler/fcntl.rs
src/main/host/syscall/handler/mod.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/handler/unistd.rs

The descriptor table shouldn't ever allow descriptors to be registered with a handle larger than `libc::c_int::MAX`. The old code also had a loop that could wrap around unexpectedly in release builds.
While the libc API uses `int` values for file handles, the Linux syscall API uses `unsigned int` for file handles. This means that when you pass a file handle of -1 to a `close()` call for example, Linux will see this as 4,294,967,295. If we read file handles in Shadow's syscall handlers as `libc::c_uint` values, we run into problems in these edge cases (for example with `dup2(fd, -1)`). We can continue reading them as signed integers and casting them to unsigned for now, but I think it's nicer to force us to handle these edge cases.
The public API to `DescriptorTable` now uses …

Add `DescriptorHandle` and return `Result` from descriptor table methods 

---

src/main/host/descriptor/mod.rs
src/main/host/process.rs

This makes `LegacyFileCounter` more closely match `OpenFile`, so that if a descriptor is dropped, it may run the file's close method.
See discussion in https://github.com/shadow/shadow/pull/2691#discussion_r1086194738.

Close the `LegacyFile` when the last `LegacyFileCounter` is dropped

---

src/main/host/descriptor/socket/inet/mod.rs
src/main/host/host.rs
src/main/host/network_interface.rs
src/main/network/net_namespace.rs
src/main/utility/mod.rs

This changes the host's `net_ns: RefCell<Option<NetworkNamespace>>` to `net_ns: NetworkNamespace` by adding a `NetworkNamespace::cleanup` function that has to be run while the worker has an active host. The network namespace objects have also been wrapped in a `RefCell`. The network interface objects don't have any `&mut` methods so this `RefCell` isn't currently needed, but we'll likely want to give them `&mut` methods in the future.
@robgjansen This can be merged either before or after your changes, whichever makes it easier for your PR.

Simplify the host's networking cleanup

---

src/main/host/memory_manager/memory_mapper.rs

This is to work around an odd behavior in Linux kernel 6.1.6 on Fedora 37 - it sometimes reports two heap regions with identical properties.
Rather than further-complicating the heap mapping code, it's probably better to just normalize the initial region map to collapse the heaps into a single region.
Verified that this fixes the tor-minimal test in a Fedora 37 VM.
Fixes https://github.com/shadow/shadow/issues/2692

MemoryManager: coalesce initial adjacent compatible regions

---

src/main/host/process.rs
src/main/host/syscall_condition.c

Simplifies API and implementation

process_continue: take thread id instead of thread*

---

src/tools/plot-shadow.py

The `:` style is not visible underneath `-.`, so they've been reordered. For example, see the old version:

Reordered line styles in `plot-shadow.py`

---

src/main/host/context.rs
src/main/host/host.rs
src/main/host/memory_manager/memory_mapper.rs
src/main/host/memory_manager/mod.rs
src/main/host/process.rs
src/main/host/thread.rs

At a high level, I think we're going to need interior mutability in Thread/ThreadRef for similar reasons as in Process and Host - it'd be difficult to avoid incompatible borrows of Thread itself without it.
More concretely, I ran into a problem when changing SysCallCondition to store a tid instead of a `Thread*`: some `SysCallCondition` methods need to act on the `Thread`. Since the condition itself is a member of the `Thread`, it'll be impossible to simultaneously hold a `&mut Thread` and a reference to the condition. Using a `&Thread` instead of a `&mut Thread` works around this.
I went a bit further here than strictly necessary and removed the `RootedRefCell` wrapper around `Process`'s `ThreadRef`s altogether. I think as with `Process` we'll end up making ~all methods take `&self` …

Plan for interior mutability in Thread / ThreadRef

---

src/main/host/descriptor/socket/inet/mod.rs
src/main/host/network_interface.c
src/main/host/network_interface.h
src/main/host/network_interface.rs
src/main/host/network_queuing_disciplines.c
src/main/network/net_namespace.rs
src/main/utility/priority_queue.c
src/main/utility/priority_queue.h

Changes:
- add a `remove_all_sockets` method to the network interface — since sockets might access the global host when they're freed/dropped, we should free/drop the sockets while the global host is still set (so before we drop the host)
- when adding a socket to the qdisc, check for the canonical handle rather than the pointer address (involves a hash table iteration unfortunately) — closes #2704 
- add the tcp socket to the network interface as a rust `InetSocket` rather than as a `LegacySocket`
The benchmark results change slightly for some reason, but they're very similar in both the tgen and tor benchmarks.

Support rust `InetSocket`s in the network interface

---

.github/workflows/coverage.yml
.github/workflows/extra_tests.yml
.github/workflows/lint.yml
.github/workflows/run_tests.yml
.github/workflows/run_tests_incremental.yml
.github/workflows/sanitizers.yml
README.md

We don't need to run our CI on commits to main since main is already a protected branch that only allows merging from a PR that is up to date with main and has already passed the CI.

Don't run workflows on merge to main

---

.github/workflows/run_tests.yml
.github/workflows/run_tests_incremental.yml

Testing both debug and release builds for every configuration is overkill. Testing a debug build for each compiler should be sufficient to catch most debug-only bugs; e.g. a debug assertion that fails.
Note that the same is not true of release builds - bugs arising from unsound/undefined behavior may only trigger on some platforms.

CI: remove debug builds from the primary test matrix

---

src/lib/shim/shim.c
src/main/host/managed_thread.c
src/main/host/managed_thread.h
src/main/host/process.rs
src/main/host/thread.c
src/main/host/thread.h

Shadow now uses an fd passed through fork/exec for the shim log rather than passing a filename using `SHADOW_LOG_FILE`, and also uses this fd for stdout and stderr.
If the shim writes to stdout/stderr (or the plugin disables interposition and writes to stdout/stderr), it should be written to the shim log rather than to shadow's stdout/stderr (which may be the terminal or some other file).
@sporksmith If this overlaps with your `Thread` migration let me know and I'll hold off on merging.

Set shim's stdout/stderr to the shim log file

---

src/main/core/worker.rs
src/main/host/context.rs
src/main/host/memory_manager/memory_copier.rs
src/main/host/process.rs
src/main/host/syscall/clone.c
src/main/host/syscall/epoll.c
src/main/host/syscall/fcntl.c
src/main/host/syscall/file.c
src/main/host/syscall/fileat.c
src/main/host/syscall/futex.c
src/main/host/syscall/ioctl.c
src/main/host/syscall/mman.c
src/main/host/syscall/poll.c
src/main/host/syscall/process.c
src/main/host/syscall/protected.c
src/main/host/syscall/protected.h
src/main/host/syscall/select.c
src/main/host/syscall/shadow.c
src/main/host/syscall/signal.c
src/main/host/syscall/socket.c
src/main/host/syscall/time.c
src/main/host/syscall/timerfd.c
src/main/host/syscall/uio.c
src/main/host/syscall/unistd.c
src/main/host/syscall_handler.c
src/main/host/thread.rs

These circular references otherwise somewhat complicate migrating Thread to Rust.
To facilitate getting rid of these, I added back `worker_getCurrentProcess` and `worker_getCurrentThread`. These are easier to implement safely now that they are wrapped in `RootedRc` objects, and we aren't trying to provide mutable access to the Rust objects. I tentatively still think it's better to prefer passing explicitly where possible, particularly in Rust code, but these are helpful in C code and for interop with C code during the migration.

SysCallHandler: don't store pointers to Process and Thread

---

src/main/build.rs
src/main/host/descriptor/descriptor.c
src/main/host/descriptor/descriptor_types.h
src/main/host/descriptor/mod.rs
src/main/utility/callback_queue.rs
src/main/utility/legacy_callback_queue.rs

This should allow us to add rust state/status listener callback closures to `LegacyFile`s in the future. This means that we can write rust objects that add listeners to `LegacyFile`s. For example, we can write a rust epoll file object that listens for events on C `TCP` or `RegularFile` objects using rust closures.

Support Rust listeners on C `LegacyFile`s

---

src/main/host/descriptor/mod.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/process.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/handler/unistd.rs

This is to make room for an eventual all-rust `TcpSocket` object.

Rename `TcpSocket` to `LegacyTcpSocket`

---

src/main/build.rs
src/main/host/process.rs
src/main/host/syscall_types.rs

This also changes both PhysicalPtr and PluginPhysicalPtr to directly store a usize internally instead of their C counterparts. This is a step towards removing the C counterparts and making the Rust types be the single canonical type. Actually doing that requires detangling circular dependencies in the generated C headers though, so I'm deferring it for the moment.

Add a Rust PluginPhysicalPtr type

---

src/main/host/managed_thread.c
src/main/host/managed_thread.h
src/main/host/syscall_handler.c
src/main/host/syscall_handler.h
src/main/host/thread.c

This simplifies the conversion of Thread to Rust.

Thread: remove more circular references and usages

---

src/lib/shadow-shim-helper-rs/src/rootedcell/cell.rs
src/lib/shadow-shim-helper-rs/src/rootedcell/rc.rs
src/lib/shadow-shim-helper-rs/src/rootedcell/refcell.rs

By default, Rust doesn't inline calls across crate boundaries. Since these functions are small, called frequently, and from across a crate boundary, we probably want them to be inline. We force this by marking them `#[inline]`, which is also done in the analogous functions in `std`.
A quick local benchmark using the tor minimal test shows there might be a measurable improvement here, though it's inconclusive since the confidence intervals overlap substantially:
Before:
```
Benchmark 1: ./setup test --extra tor-minimal
Time (mean ± σ):     17.424 s ±  0.455 s    [User: 18.446 s, System: 6.024 s]
Range (min … max):   16.818 s … 18.123 s    10 runs
```
After:
```
Benchmark 1: ./setup test --extra tor-minimal
Time (mean ± σ):     17.119 s ±  0.482 s    [User: 18.211 s, System: 5.993 s]
Range …
```

Rooted*: make public APIs inline

---

src/main/utility/mod.rs

This is analogous to `SyncSendPointer`, but only asserts that the pointee is `Send`, not that it is necessarily `Sync`.
This also changes  `SyncSendPointer<T>` and `HostTreePointer<T>` to unconditionally implement `Copy` and `Clone`, even when `T` does not.

Add SendPointer

---

docs/install_dependencies.md

Shadow doesn't really make use of any of these. We do have Python log parsing/plotting scripts, but they're not officially supported.

Remove optional dependencies

---

docs/SUMMARY.md

These aren't officially supported, and we've decided that parsing the log messages is a "developer-only" thing.

Move the "Shadow Output" docs to the "Developer Guide" section

---

src/main/host/syscall_condition.c

The timeout condition in the `SysCallCondition` is backwards, causing the process to wake up before its timeout has expired. (And maybe not wake up at all when it does exceed the timeout?)
(This doesn't fix our tor onion service stream timeout issue.)

Fix backwards timeout condition

---

src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/descriptor/socket/mod.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/syscall/handler/socket.rs

The logic for generally follows the logic from `src/main/host/syscall/socket.c`.
https://github.com/shadow/shadow/blob/8638dc4acd92b194215701c669259f23a29738b2/src/main/host/syscall/socket.c#L1179-L1211

Support `shutdown()` for tcp wrapper

---

src/lib/syscall-logger/src/lib.rs
src/main/host/syscall/handler/mod.rs
src/main/host/syscall/handler/sched.rs

Similar to #2664 but for return types.
Syscalls can return various types (`int`, `size_t`, pointers, etc). We probably don't want to return the wrong type, which the plugin may interpret incorrectly. For example if a syscall is supposed to return an `int`, we probably don't want to return a `u64::MAX` from our syscall handler.
Currently our syscall handlers return a `SysCallReg`, which is a 64-bit union of various types, and there is no type checking to make sure our syscall handler is returning a valid type. This PR allows our syscall handlers to specify an explicit return type (ex: `libc::c_int` instead of `SysCallReg`).
Only the "sched.h" syscall handlers have been updated to use this. I didn't bother with the others. We can update them later if we want to, but for now this change …

Support explicit return types in the syscall handlers

---

src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/descriptor/socket/mod.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/descriptor/tcp.c
src/main/host/descriptor/tcp.h
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/socket.c

The logic generally follows the logic from `src/main/host/syscall/socket.c`.
https://github.com/shadow/shadow/blob/e0cf19596456fbfb162ee67b23e15dbd01d01c30/src/main/host/syscall/socket.c#L1072-L1115

Support `listen()` for tcp wrapper

---

src/main/core/worker.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/descriptor/socket/mod.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/socket.c

The logic generally follows the logic from `src/main/host/syscall/socket.c`.
https://github.com/shadow/shadow/blob/a8f49014f18d6da428f3548a914a7bdbbb88e9c2/src/main/host/syscall/socket.c#L784-L901

Support `connect()` for tcp wrapper

---

src/main/host/descriptor/mod.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/descriptor/socket/mod.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/socket.c

The logic generally follows the logic from `src/main/host/syscall/socket.c`.
https://github.com/shadow/shadow/blob/a8f49014f18d6da428f3548a914a7bdbbb88e9c2/src/main/host/syscall/socket.c#L156-L239
Since the TCP code has already (incorrectly) added the socket to the descriptor table, we need to remove it from the table so that we can re-add it later in the `accept()` syscall handler.

Support `accept()` for tcp wrapper

---

src/Cargo.lock
src/lib/vasi-macro/Cargo.toml
src/lib/vasi-macro/src/lib.rs

Extending this to facilitate use with `ShimEvent`.

VirtualAddressSpaceIndependent derive macro: support enums and unions

---

src/Cargo.lock
src/lib/shadow-shim-helper-rs/src/option.rs
src/lib/shadow-shim-helper-rs/src/rootedcell/cell.rs
src/lib/shadow-shim-helper-rs/src/rootedcell/refcell.rs
src/lib/vasi-macro/Cargo.toml
src/lib/vasi-macro/src/lib.rs
src/lib/vasi-sync/src/scchannel.rs
src/lib/vasi-sync/src/scmutex.rs
src/lib/vasi-sync/src/sync.rs
src/lib/vasi/src/lib.rs

Extends the VirtualAddressSpaceIndependent Derive macro to handle generics, and replaces manual implementation of the trait by using the derive macro.
(Previously:)
> For discussion purposes - I'm a bit stumped how to get this to work. In particular I don't see a way to write the `static_assertions` for generics.
> 
> The current incarnation fails in a doc test that tries to use the macro with a generic type.
> 
> The test:
> ```
> /// #[derive(VirtualAddressSpaceIndependent)]
> /// struct MyWrapper<T> {
> ///   val: T,
> /// }
> ```
> 
> The failure:
> ```
>  --> src/lib.rs:120:8
>   |
> 6 | struct MyWrapper<T> {
>   |                  - type parameter from outer function
> 7 |   val: T,
>   |        ^ use of generic parameter from outer function
> ```
> 
> The problem is we end up …

VirtualAddressSpaceIndpendent: use trait bounds in derive macro

---

src/main/host/syscall/protected.h
src/main/host/syscall_handler.c
src/main/host/syscall_handler.h
src/main/host/thread.rs

I don't think we need this ref count.

Remove reference count from `SysCallHandler`

---

src/lib/shadow-shim-helper-rs/shim_shmem.c
src/lib/shadow-shim-helper-rs/shim_shmem.h
src/lib/shadow-shim-helper-rs/src/ipc.rs
src/lib/shadow-shim-helper-rs/src/shim_event.rs
src/lib/shim/shim.c
src/lib/shim/shim.h
src/lib/shim/shim_syscall.c
src/main/host/managed_thread.c

This will make it easier to work with from Rust code; in particular avoiding `unsafe` union access.

ShimEvent: convert from union to enum

---

src/Cargo.lock
src/lib/vasi-sync/Cargo.toml
src/lib/vasi-sync/benches/scchannel.rs
src/lib/vasi-sync/src/scchannel.rs
src/lib/vasi-sync/src/sync.rs
src/lib/vasi-sync/tests/scchannel-tests.rs
src/lib/vasi/src/lib.rs

This adds criterion-based microbenchmarks for SelfContainedChannel. On top of that it adds several candidate optimizations, with the microbenchmark results in the corresponding commit messages.
On my desktop dev machine these are all either neutral or *hurt* performance.
On a larger simulation machine, removing the internal "Reading" and "Writing" states has some benefit, but mostly only when pinning is disabled.
The candidate optimizations and microbenchmark results are reverted, but left in the commit history in case we want to revisit in the future.
@robgjansen would it be possible for you to run these on the benchmark machine or an equivalent machine? It should only take a few minutes to run.
I think it'd look something like this:
```bash
git remote add sporksmith …
```

SelfContainedChannel benchmarks and candidate optimizations

---

src/main/host/descriptor/eventfd.rs
src/main/host/descriptor/mod.rs
src/main/host/descriptor/pipe.rs
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/mod.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/syscall/handler/unistd.rs
src/main/utility/enum_passthrough.rs

Similar to #2797, but with `readv` and `writev` instead. This doesn't add support for the `readv` and `writev` syscalls, but restructures the socket code so that we can support these syscalls in the future.

Restructure `File` to use `readv` and `writev`

---

CHANGELOG.md
src/main/host/syscall/uio.c
src/test/file/test_file.c

Shadow didn't reconstruct the offset correctly and didn't handle negative offsets.

Fix preadv/preadv2/etc offset calculation and handling

---

src/lib/shim/shim.c
src/main/host/managed_thread.c
src/main/utility/utility.c
src/main/utility/utility.h

Bare vfork + exec are tricky to use, since it's easy to accidentally corrupt the parent process's state from the child process. It's also unsupported in Rust (https://github.com/rust-lang/libc/pull/1574, https://github.com/rust-lang/libc/issues/1596).
I think we could work around this in Rust by using inline assembly or a C helper function to wrap the fork and exec, but `posix_spawn` basically does that for us already.

Use posix_spawn instead of vfork + exec

---

CHANGELOG.md
src/main/host/managed_thread.c
src/main/utility/childpid_watcher.rs

We were failing to save the ChildPidWatcher notification handles, which
in turn meant we weren't unregistering threads with the ChildPidWatcher
after they exited, thus creating a resource leak. The relevant data was
still getting freed when the whole Process exited, so it would have only
affected Processes that had many threads start and end over their
lifetime.
The callback registered for each thread is only about 16 bytes - a
function pointer and a data pointer.
Additionally this fixes a bug causing a panic when we do unregister a callback for a process that's already been unregistered.

Unregister threads with ChildPidWatcher

---

src/main/build.rs
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/tcp.c
src/main/host/descriptor/tcp.h
src/main/host/memory_manager/mod.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/handler/uio.rs
src/main/host/syscall/handler/unistd.rs
src/main/host/syscall/socket.c
src/main/routing/packet.c
src/main/routing/packet.h
src/main/routing/payload.c
src/main/routing/payload.h

We don't limit the send/recv buffer size using `SYSCALL_IO_BUFSIZE = 10 MiB` in this new version. I don't think this is needed with the current memory manager.
I duplicated some packet-related C functions to support passing the memory manager through, but this should hopefully be cleaned up once UDP sockets are migrated to rust.
The logic generally follows the logic from `src/main/host/syscall/socket.c`.
https://github.com/shadow/shadow/blob/ec2f888138ef9d466092d027441ad8fedc6ffbc5/src/main/host/syscall/socket.c#L407-L654

Support `sendmsg()` and `recvmsg()` for tcp wrapper

---

src/main/utility/childpid_watcher.rs

This is an attempt to fix the crash in https://github.com/tmodel-ccs2018/tmodel-ccs2018.github.io.git
I added some testing for unregistration but wasn't able to reproduce the crash.
This *should* fix it, though.

ChildPidWatcher more robust unregistration

---

src/main/utility/childpid_watcher.rs

We were getting rare failures in CI unit tests, and consistent failures in large benchmarks. I was able to reproduce with:
```
for i in `seq 1000`; do
echo trial $i
if ! RUST_BACKTRACE=full cargo test --manifest-path=src/Cargo.toml -p shadow-rs childpid_watcher ; then
break
fi
done
```
I think what was happening is that we could get an epoll event for a dying process in the worker thread just as we were in the middle of unregistering it from another thread.
The simplest fix is to just let the worker thread handle unregistration so that it's serialized with other operations in that thread.

ChildPidWatcher: fix a race condition when unregistering a pid

---

src/lib/shadow-build-common/src/lib.rs
src/main/build.rs
src/main/core/main.c
src/main/core/main.h
src/main/core/main.rs
src/main/host/descriptor/tcp.c
src/main/host/process.rs
src/main/utility/mod.rs
src/main/utility/utility.c
src/main/utility/utility.h

Also moves some utility functions to `tcp.c` since they're only ever called from there.

Move misc code to rust

---

src/main/host/memory_manager/mod.rs

One fix is in a log statement, and the other is in `AllocdMem` which we only ever use as an `AllocdMem<u8>`, so neither of these currently cause incorrect behaviour.

Fix some incorrect buffer sizes in the memory manager

---

src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/memory_manager/mod.rs
src/main/host/syscall/handler/ioctl.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/handler/time.rs
src/main/utility/pod.rs

This also renames it to `read` and removes the UB from the `MaybeUninit::uninit().assume_init()` (part of #2555).

Simplify memory manager `read_vals`

---

CHANGELOG.md

In particular the next release will have a number of breaking changes; it'd probably be useful to have those highlighted and separate from smaller changes. Similarly I think it'd generally be useful to split along `MINOR` and `PATCH` lines.
I think we can still omit changes that should be completely invisible to users (e.g. refactors, conversions to Rust, etc)

Split CHANGELOG by semver-level

---

src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/memory_manager/mod.rs
src/main/host/process.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/handler/sysinfo.rs
src/main/host/syscall/handler/time.rs
src/main/host/syscall/handler/unistd.rs
src/main/host/syscall/io.rs

This is similar to the existing `read` method, and I think it is a little nicer to use than `copy_to_ptr` in simpler cases.
(Also I'm not sure that the pid address write in `reap_thread()` is correct since I think it's supposed to write a pointer, not a `pid_t`, but for now I'm leaving this the same as it was before.)

Add a `write` method to the memory manager

---

src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/syscall/io.rs

I think it's clearer this way, and lets us remove the `NoTypeInference` restriction from the function.

Change definition of `io::write_partial`

---

CHANGELOG.md
src/lib/vasi-sync/src/scchannel.rs
src/main/host/managed_thread.rs
src/main/host/process.rs

This moves waiting for thread-exit from `Process` to `ManagedThread`, where it more logically belongs. It also adds a check in `ManagedThread`'s `Drop` implementation to validate that we never drop it while the native thread is still running, and adds documentation about why this is important - to prevent memory corruption due to shared memory regions being deallocated and reused.
This also fixes a bug - Before we *weren't* waiting for the thread to exit if the `clear_child_tid` attribute wasn't set. I belive this was a race condition, but in practice I think most higher level thread APIs (e.g. libc's `pthread` and Rust's `std::thread`) use this attribute, so wouldn't have wouldn't have been affected.

Move and better-document waiting for thread exit

---

CHANGELOG.md
src/main/host/descriptor/socket/unix.rs
src/main/host/syscall/socket.c
src/test/socket/send_recv/test_send_recv.rs

These are some old changes that might as well be added. Having the tests in place will make it easier to support for inet sockets in the future.

Add `MSG_TRUNC` support for unix sockets

---

src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/mod.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/handler/uio.rs

This field usually is the number of bytes read, but not always (for example see the `MSG_TRUNC` flag).

Rename `RecvmsgReturn.bytes_read` field to `return_val`

---

docs/semver.md
docs/supported_platforms.md

In Shadow 3.0, we plan to relax our stability guarantees so that we can drop support for unsupported platforms between minor releases. The currently unsupported platforms have been removed from the docs, but not the CI tests. I also added text about the kernel version.

Update our semver guidelines and supported platforms

---

CHANGELOG.md
docs/ci.md
docs/install_dependencies.md

This is one of the planned breaking changes in
https://github.com/shadow/shadow/discussions/2496
I left in the two CI runs with clang, since I *think* the decision was to still run those for the extra diagnostics. OTOH I'd be happy to remove them; their value will continue to decrease as we get rid of C code.

Drop official support for clang

---

CHANGELOG.md
src/main/host/syscall/time.c
src/test/sleep/test_sleep.rs

Support the `TIMER_ABSTIME` flag for `clock_nanosleep`

---

CHANGELOG.md
docs/shadow_config_spec.md
src/lib/shadow-shim-helper-rs/src/shim_shmem.rs
src/lib/shim/shim.c
src/lib/shim/shim.h
src/lib/shim/shim_rdtsc.c
src/lib/shim/shim_sys.c
src/lib/shim/shim_syscall.c
src/main/core/manager.rs
src/main/core/support/configuration.rs
src/main/host/host.rs
src/main/host/process.rs
src/main/host/syscall/time.c
src/main/host/syscall/time.h
src/main/host/syscall_handler.c
src/main/host/thread.rs

Removes the environment variables SHADOW_DISABLE_SHIM_SYSCALL, SHADOW_SHM_PROCESS_BLK, and SHADOW_SHM_HOST_BLK.
As part of removing SHADOW_DISABLE_SHIM_SYSCALL, this also removes the experimental option `use_shim_syscall_handler`, and removes the redundant shadow-side syscall handlers.
Progress on #2848

Reduce usage of special environment variables

---

CHANGELOG.md
docs/shadow_config_spec.md
src/main/core/manager.rs
src/main/core/sim_config.rs
src/main/core/support/configuration.rs
src/main/host/host.rs
src/main/host/process.rs
src/test/config/CMakeLists.txt
src/test/config/shutdown/CMakeLists.txt
src/test/config/shutdown/shutdown_signal_sigint.yaml
src/test/config/shutdown/shutdown_signal_sigkill.yaml
src/test/config/shutdown/shutdown_signal_sigterm.yaml
src/test/socket/bind/bind_in_new_process.yaml

Progress on https://github.com/shadow/shadow/discussions/2034, which is part of the planned breaking changes for 3.0: https://github.com/shadow/shadow/discussions/2496

Replace process stop_time with shutdown_time and shutdown_signal

---

src/main/core/scheduler/pools/unbounded.rs
src/main/utility/synchronization/mod.rs
src/main/utility/synchronization/simple_latch.rs
src/main/utility/synchronization/thread_parking.rs

I'm not sure that the `ThreadUnparker` works correctly when using rust's parking API, so I've updated a comment in it and replaced it in the thread-per-core scheduler (the unbounded thread pool) with a simple futex-based latch instead. The thread-per-host scheduler continues to use the (possibly broken) `ThreadUnparker`.
Another advantage is that it can futex-wake all threads with one syscall, rather than unparking each thread individually.
I ran a benchmark on an earlier version of this PR and there was no performance improvement.

Switch the unbounded thread pool to use a latch instead of parkers

---

src/main/utility/synchronization/simple_latch.rs

This changes the atomic from `AtomicI32` to `AtomicU32` since I realized that futex(2) in ubuntu 20.04 is out of date, and newer man pages show that its unsigned.
This also adds `FUTEX_PRIVATE_FLAG` which may improve performance (but I doubt it will in practice). This flag can be used since the latch will only ever be used in the same process.

Small latch improvements

---

CHANGELOG.md
docs/shadow_config_spec.md
src/main/host/network_interface.c
src/main/host/network_interface.h
src/main/host/network_interface.rs
src/main/network/net_namespace.rs
src/test/determinism/determinism1.test.shadow.config.yaml
src/test/determinism/determinism1_compare.cmake
src/test/determinism/determinism2.test.shadow.config.yaml
src/test/determinism/determinism2_compare.cmake

The interface names for 127.0.0.1 and the public IP have been chosen as "lo" and "eth0", which are standard names for these interfaces on Linux. Part of the 3.0 changes.

Change pcap filenames to use the interface name

---

CHANGELOG.md
docs/shadow_config_spec.md
src/main/core/manager.rs
src/main/core/sim_config.rs
src/main/core/support/configuration.rs
src/test/environment/environment.yaml
src/test/environment/test_env.rs
src/test/golang/gc.yaml
src/test/golang/go_preempt.yaml
src/test/golang/goroutines.yaml
src/test/tgen/fixed_duration/100mbit_100ms.yaml
src/test/tgen/fixed_duration/10mbit_200ms.yaml
src/test/tgen/fixed_duration/1gbit_10ms.yaml
src/test/tgen/fixed_duration/1mbit_300ms.yaml
src/test/tgen/fixed_size/100mbit_100ms.yaml
src/test/tgen/fixed_size/10mbit_200ms.yaml
src/test/tgen/fixed_size/1gbit_10ms.yaml
src/test/tgen/fixed_size/1mbit_300ms.yaml
src/test/tor/minimal/tor-minimal.yaml

Part of the 3.0 changes.
This also removes the tilde expansion of the user-provided `LD_PRELOAD` arguments.

Change the process 'environment' option to a map

---

src/main/core/manager.rs

Tornettools shouldn't search for this string anymore as of shadow/tornettools#96. Part of the 3.0 changes.

Remove the '_manager_heartbeat' string

---

src/main/host/managed_thread.rs
src/main/host/process.rs
src/main/host/syscall/unistd.c
src/main/host/thread.rs

Refactors Process to remove more state variables and make process teardown easier to follow.

Refactor Process teardown

---

src/main/build.rs
src/main/core/support/definitions.h
src/main/core/worker.rs
src/main/host/descriptor/tcp.c
src/main/host/host.rs
src/main/host/process.rs
src/main/host/syscall/formatter.rs
src/main/host/syscall/protected.h
src/main/host/syscall/signal.c
src/main/host/syscall_condition.c
src/main/host/syscall_condition.h
src/main/host/syscall_handler.c
src/main/host/thread.rs

This unblocks some further cleanup of managing Process's internal state, and removes some complexity in itself.

Process: remove circular weak reference

---

docs/shadow_config_spec.md
src/main/core/sim_config.rs
src/main/core/support/configuration.rs

This takes a bit more code, but keeps with trying to do as much input validation as we can up front. We can also reuse it when adding process end state expectations (e.g. "killed with signal X") for https://github.com/shadow/shadow/discussions/2034

Move signal parsing into serde

---

CHANGELOG.md
docs/shadow_config_spec.md
src/main/core/sim_config.rs
src/main/core/support/configuration.rs
src/test/determinism/determinism1.test.shadow.config.yaml
src/test/determinism/determinism2.test.shadow.config.yaml

https://github.com/shadow/shadow/issues/2065#issuecomment-1507299498
> top-level field "host_defaults" -> "host_option_defaults"
> host field "options" -> "host_options"
Closes #2065.

Rename the `host_defaults` and `options` config fields

---

src/tools/parse-shadow.py

This broke in https://github.com/shadow/shadow/pull/2874.
This bug prevents the benchmark runner from generating tgen runtime performance graphs.

Fix search string in the parse script

---

src/Cargo.lock
src/Cargo.toml
src/lib/std-util/Cargo.toml
src/lib/std-util/src/lib.rs
src/lib/std-util/src/nested_ref.rs
src/main/Cargo.toml
src/main/host/process.rs
src/main/host/syscall_condition.c

Processes can be kept around as zombies after they exit, but it usually doesn't make sense to access most of their internal state at this point. Previously there were ad-hoc checks for whether the Process was still running, but by moving the internals into an enum we can't forget to make such checks.
This also helps ensure we clean up everything that ought to be cleaned up when the process exits (goes from the `Runnable` state to the `Zombie` state).

Split Process internals by state

---

CHANGELOG.md
src/lib/libc_preload/gen_syscall_wrappers_c.py
src/lib/libc_preload/syscall_wrappers.c

Unlike most libc syscall wrappers, getcwd is supposed to return NULL instead of -1 on errors. The incorrect wrapper was causing a segfault when trying to run bash under shadow.

Don't auto-generate getcwd libc wrapper

---

src/main/routing/dns.c

This means that Shadow's fake hosts file isn't written to the filesystem and won't clutter /tmp with hundreds of files.

Replace hosts file with a memfd

---

CHANGELOG.md
CMakeLists.txt
cmake/FindDL.cmake
cmake/FindM.cmake
cmake/FindRPTH.cmake
cmake/FindRT.cmake
setup

Part of the 3.0 changes.
- remove the `--profile` option
- closes #2405
- remove the `-C` short form for `--coverage`
- the coverage option is rarely used and I don't think it needs a short form
- remove deprecated `--include` and `--library` options
- i don't know if these are still useful, but they're marked as deprecated so now would be the time to remove them

Clean up setup script options

---

docs/shadow_config_spec.md
src/main/core/manager.rs
src/main/core/scheduler/pools/unbounded.rs
src/main/core/scheduler/thread_per_core.rs
src/main/core/support/configuration.rs
src/main/utility/synchronization/simple_latch.rs

This adds the experimental option `use_worker_spinning`, which is disabled by default. If enabled, the worker threads will spin indefinitely in a sched_yield loop rather than wait on a futex while waiting for a new task to be ready. This has a large performance benefit on our benchmark runner (#2877). Using this option, we can test on other machines and see if/when we should enable this spinning behaviour by default.
https://github.com/shadow/benchmark-results/tree/master/tgen/2023-04-19-T21-22-45
https://github.com/shadow/benchmark-results/tree/master/tor/2023-04-25-T16-56-53

Add experimental option to spin in the worker threads

---

rust-toolchain.toml
src/main/host/memory_manager/mod.rs
src/main/utility/sockaddr.rs

`CStr::from_bytes_until_nul` makes the code nicer, and probably performs better since it uses `memchr::memchr` rather than our `position(|c| *c == 0)`.

Update to rust 1.69.0 and use `CStr::from_bytes_until_nul`

---

src/main/core/manager.rs
src/main/core/mod.rs
src/main/core/resource_usage.rs

In the future, we should be able to use this data to compute memory usage in tornettools instead of running `/usr/bin/free` in a loop. While I think it would be best to not write json directly in the log file, I think this is fine until we have better structured logging. Even though it's json, we'll still consider it unsupported along with everything else in the log file.
Ex:
```
00:00:01.057619 [546333:shadow] n/a [INFO] [n/a] [manager.rs:765] [shadow_rs::core::manager] System memory usage in bytes at simtime 6120000000 ns reported by /proc/meminfo: {"mem_total":67169312768,"mem_free":48688345088,"swap_total":68719472640,"swap_free":55525654528,"buffers":0,"cached":7910858752,"s_reclaimable":0,"shmem":5169258496}
```
Double-checked that the performance didn't change: …

Log system memory info during the heartbeat

---

ci/container_scripts/install_extra_deps.sh
docs/compatibility_notes.md
docs/install_dependencies.md

We don't use it, so no point in installing it.
Also updates the etcd compatibility notes.

Don't install a rustup toolchain in the docs

---

CHANGELOG.md
docs/getting_started_basic.md
src/main/host/process.rs

The semantics of these were a bit awkward (e.g. 128+signum for death-by-signal; empty for still-running), and the per-process `expected_final_state` attribute replaces their primary use-case.
If we decide to bring these back, we should consider a richer format; maybe just the serialized actual process final state. e.g. "running", "{exited: 0}", "{signaled: SIGINT}", ...

Drop per-process exitcode files

---

CHANGELOG.md
docs/shadow_config_spec.md
src/main/core/support/configuration.rs

This enables it in all cases unless opted out of. The performance impact is documented in #2877. We may change this before the 3.0 release.

Enable the experimental worker spinning by default

---

CHANGELOG.md
src/main/core/support/configuration.rs

This seems to fix it.
With:
```yaml
host_option_defaults:
pcap_enabled: true
hosts:
hostname:
host_options:
log_level: trace
```
We now get:
```
host_options: HostDefaultOptions {
log_level: Some(
Value(
Trace,
),
),
pcap_enabled: Some(
true,
),
pcap_capture_size: Some(
Bytes {
value: 65535,
prefix: Base,
},
),
},
```

Fix merging of `host_options` and `host_option_defaults`

---

CHANGELOG.md
src/lib/shim/shim.c
src/lib/shim/shim.h
src/lib/shim/shim_api_addrinfo.c
src/lib/shim/shim_api_syscall.c
src/lib/shim/shim_rdtsc.c
src/lib/shim/shim_seccomp.c
src/lib/shim/shim_seccomp.h
src/lib/shim/shim_syscall.c
src/lib/shim/shim_syscall.h
src/lib/shim/shim_tls.c
src/main/host/syscall/handler/clone.rs
src/main/host/syscall/handler/mod.rs
src/main/host/syscall_handler.c
src/main/utility/pod.rs

Implements clone3, currently using clone internally.
This also requires restoring general purpose registers from the original context of the syscall, since glibc's clone3 implementation assumes they still have the original values from the parent in the newly created child thread.

Implement clone3

---

CHANGELOG.md
docs/shadow_config_spec.md
src/main/core/cpu.rs
src/main/core/manager.rs
src/main/core/mod.rs
src/main/core/scheduler/thread_per_core.rs
src/main/core/scheduler/thread_per_host.rs
src/main/core/support/configuration.rs
src/test/CMakeLists.txt

If `parallelism` is 0 (the new default), shadow will choose the parallelism level equal to the number of physical CPU cores available.

Support a `parallelism` of 0

---

src/lib/shim/shim_seccomp.c
src/lib/shim/shim_syscall.c
src/lib/shim/shim_syscall.h

There's no easy way to get an authoritative "end" address of an    
arbitrary individual function, so we were just guessing a loose upper    
bound, and hoping that managed code that tried to make direct syscalls    
didn't unluckily end up in the allow-listed address range.    
We *can* reliably get the end address of a linker section, and place    
functions we want to allow-list into that section.    
Since we're not using a linker script, we're depending on the linker    
to create the `__start_*` and `__end_*` symbols. This is a little    
fragile, but should be obvious if it breaks, and resolvable by    
adding/modifying a linker script to explicitly add such symbols    
ourselves.

Allow-list seccomp native syscalls by code section

---

src/lib/syscall-logger/src/lib.rs
src/main/host/syscall/io.rs

```
warning: variable does not need to be mutable
--> lib/syscall-logger/src/lib.rs:63:13
|
63 |         let mut input_fn = match &mut input {
|             ----^^^^^^^^
|             |
|             help: remove this `mut`
|
= note: `#[warn(unused_mut)]` on by default
```
```
warning: variable does not need to be mutable
--> main/host/syscall/io.rs:392:9
|
392 |     let mut plugin_msg = &mut mem_ref.deref_mut()[0];
|         ----^^^^^^^^^^
|         |
|         help: remove this `mut`
|
= note: `#[warn(unused_mut)]` on by default
```

Fix two warnings on nightly

---

src/lib/shadow-shim-helper-rs/src/syscall_types.rs
src/lib/shadow-shim-helper-rs/src/util/mod.rs
src/main/core/manager.rs
src/main/core/work/task.rs
src/main/core/worker.rs
src/main/host/host.rs
src/main/host/thread.rs
src/main/network/net_namespace.rs
src/main/network/packet.rs
src/main/utility/childpid_watcher.rs
src/main/utility/mod.rs

This also:
- ~makes `PhantomData<T>` `VirtualAddressSpaceIndependent` for all `T`~
- adds inlining to methods of `ForeignPtr`, `SysCallReg`, and `SysCallArgs` since these methods are very small functions around integer operations, otherwise they wouldn't be inlined across crate boundaries

Make `ForeignPtr` `Send` and `Sync`

---

src/lib/shadow-shim-helper-rs/build.rs
src/lib/shadow-shim-helper-rs/src/ipc.rs
src/lib/shadow-shim-helper-rs/src/shim_event.rs
src/lib/shim/shim.c
src/lib/shim/shim_syscall.c
src/main/host/managed_thread.rs

This is mostly to make it easier to follow which events can be sent which direction and when. It also has a small benefit that ShimEventToShadow is a little smaller, which should make copying it slightly cheaper.

Split ShimEvent into ShimEventToShadow and ShimEventToShim

---

src/main/core/manager.rs
src/main/core/sim_config.rs
src/main/host/host.rs
src/main/host/managed_thread.rs
src/main/host/process.rs
src/main/host/syscall_handler.c

Shadow outputs a lot of messages at 'info' level that aren't very useful unless you're debugging something. This PR reduces the number of 'info' log messages to unclutter the log at the default log level.

Reduce the number of log messages at 'info' level

---

docs/shadow_config_spec.md
docs/system_configuration.md

Changes to:
- `hosts.<hostname>.processes[*].path` in `docs/shadow_config_spec.md`
- `docs/system_configuration.md`

Small changes to docs

---

CHANGELOG.md
docs/coding_style.md
src/main/host/syscall_handler.c

This PR adds some guidance about log levels to our style guide, and changes the logging for unimplemented syscalls to conform to this proposed policy.

Log level policy

---

src/main/core/support/configuration.rs

Clap is only showing them for `bool` options.
Before:
```
--use-worker-spinning <bool>
Each worker thread will spin in a `sched_yield` loop while waiting for a new task. This is ignored if not using the thread-per-core scheduler.
[default: true]
[possible values: true, false]
```
After:
```
--use-worker-spinning <bool>
Each worker thread will spin in a `sched_yield` loop while waiting for a new task. This is ignored if not using the thread-per-core scheduler.
[default: true]
```

Hide clap's "possible values" text

---

.github/workflows/extra_tests.yml
.github/workflows/run_tests.yml
CHANGELOG.md
ci/run.sh
docs/ci.md
docs/supported_platforms.md

Now that the MemoryMapper uses `memfd_create` instead of creating files in `/dev/shm` (a422da50ea7e6ee8438486b534c251ae9c1e9a0c), `/dev/shm` no longer needs to be executable.

We no longer need executable /dev/shm

---

src/test/CMakeLists.txt
src/test/cli/CMakeLists.txt
src/test/cli/help-long-expected
src/test/cli/help-short-expected

Clap often changes the formatting of the help text. This adds a test that compares the help output to a golden output. If we update our config options or upgrade clap, we will need to regenerate the golden output. This should hopefully help prevent unexpected changes in the help text when we upgrade clap.

Add test for cli help output

---

src/main/core/work/event.rs
src/main/core/worker.rs
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/network_interface.rs
src/main/network/mod.rs
src/main/network/packet.rs
src/main/network/relay/mod.rs
src/main/network/router/codel_queue.rs
src/main/network/router/mod.rs

The rust packet is a wrapper around a reference-counted `c::Packet`, so I think `PacketRc` better describes what the rust wrapper is.

Rename `Packet` to `PacketRc` and other small changes

---

src/main/host/descriptor/mod.rs
src/main/host/process.rs

This is split out of #2959. I thought this might change the network results since it may delay notifying some event listeners, but a benchmark shows no change.

Add more uses of the global callback queue

---

src/lib/logger/logger.c
src/lib/logger/logger.h
src/lib/shim/patch_vdso.c
src/main/host/descriptor/descriptor_types.h
src/main/host/syscall/mman.c
src/main/host/syscall_handler.c
src/main/utility/utility.c
src/main/utility/utility.h

This is part of a larger attempt to switch the C code over to using Linux kernel headers where appropriate. I think switching everything over is going to be more than we want to bite off right now, but this PR removes some of the conflicts with `glib.h` and `stdlib.h`.
Related to #2919

Remove some header dependencies

---

src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/inet/udp.rs
src/main/host/descriptor/socket/mod.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/handler/uio.rs
src/main/network/packet.rs
src/main/routing/packet.c
src/main/routing/packet.h
src/main/routing/payload.c
src/main/routing/payload.h
src/main/utility/sockaddr.rs
src/test/socket/send_recv/test_send_recv.rs
src/test/socket/shutdown/test_shutdown.rs

This adds a rust implementation of udp. A future PR will remove the C version, along with the C socket syscall handlers and other legacy code.
There are still some TODO comments in the udp code that should be looked at and have tests added for, but I'll leave those for future PRs. All of the existing udp tests pass with this new rust version, and it also supports `sendmsg`/`recvmsg` and `shutdown`. It should behave similar to the C version, but there are a few changes such as the socket buffer size acting as a soft limit rather than a hard limit. There are also some accesses of the host through the worker that shouldn't be there, but these are required until we rewrite the network interface in rust.

Add a rust UDP implementation

---

ci/container_scripts/test.sh
src/Cargo.lock
src/lib/shim/shim_seccomp.c
src/lib/shim/shim_seccomp.h
src/lib/shim/shim_syscall.c
src/lib/shim/shim_tls.c
src/lib/vasi-sync/Cargo.toml
src/lib/vasi-sync/src/sync.rs
src/test/clone/CMakeLists.txt
src/test/clone/test_clone.c

This removes some dependencies from the shim on native thread local storage (https://github.com/shadow/shadow/issues/1559). Together with modifying the clone test to explicitly set an empty TLS descriptor, this allows the clone tests to work under shadow... sometimes.
I haven't been able to reproduce the remaining failures locally, but I suspect it's due to usage of libc from the shim, which assumes that native thread local storage is set up. In particular, most libc functions will try to set `errno` on error, which it expects to be in native thread local storage. These accesses result in a segfault in the test.
It would be nice if we could set up proper native thread local storage in these tests, but the process for doing so is not well documented, and I think would conflict with the …

Partly fix raw clone test

---

src/main/host/descriptor/socket/inet/udp.rs
src/test/socket/connect/test_connect.rs

UDP sockets shouldn't rely on the network interface for dropping these packets.
This also adds another connect test, but it's disabled as it doesn't work in Shadow.

Have UDP sockets drop packets from non-peers

---

.github/workflows/sanitizers.yml
ci/container_scripts/install_extra_deps.sh
rust-toolchain.toml

The main reason is so we can start using the sparse registry.

Upgrade rustup toolchain to 1.70

---

src/lib/vasi-sync/src/sync.rs
src/main/host/descriptor/mod.rs
src/main/utility/synchronization/simple_latch.rs

Some small code improvements using new library features. I've been waiting for the `Arc::into_inner` for a long time.

Clean up some code for rust 1.70.0

---

src/main/host/descriptor/socket.c
src/main/host/descriptor/socket.h
src/main/host/descriptor/tcp.c
src/main/utility/legacy_callback_queue.rs

This is split out of #2959. This PR changes the sockets to use the global `C_CALLBACK_QUEUE` to notify the host that the socket wants to send packets. This is similar to how we delay status change events (ex: readable/writable/closed/etc) to prevent "multiple mutable borrow errors" due to circular references.
We'll need this in the future when we want TCP sockets to add their rust wrappers to the network interface rather than its C objects.
The network results change, but not significantly (it's similar to changes we'd expect if we simply changed the simulation seed).
https://github.com/shadow/benchmark-results/tree/master/tor/2023-05-24-T15-05-14

Delay "socket wants to send" notification

---

src/main/build.rs
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/tcp.c
src/main/host/descriptor/tcp.h

Previously the C `TCP` object would be added to the qdisc, but we want the rust `LegacyTcp` wrapper to be added instead. This requires a circular reference between the `TCP` and `LegacyTcp` objects since the `TCP` object adds itself to the qdisc, but the `TCP` object has been made to only hold a weak reference to the `LegacyTcp`.  Some additional changes needed to be made to prevent multiple mutable borrows of the `LegacyTcp`, and to extend the lifetime of the `LegacyTcp`, otherwise upgrading the weak reference won't work.

Add the `LegacyTcp` wrapper to the interface qdisc 

---

src/lib/shim/shim_seccomp.c
src/lib/shim/shim_seccomp.h
src/lib/shim/shim_syscall.c

This fixes a performance regression introduced in 789f9f247cf9a87c55518cf735725001891f4f5d: making a direct syscall instead of a libc function call in vasi-sync caused us to go through the slow path of getting stopped by seccomp, and have to retry in our seccomp-handling.                   
Allowing native syscalls made from the shim's whole `.text` segment includes direct syscalls made from anything linked statically with the shim. This fixes the performance regression and likewise allows us to continue moving from libc to direct syscalls in the shim without sacrificing performance.    
We currently don't have a use-case of *wanting* syscalls made directly from the shim to be intercepted. e.g. the closest would be when we call a managed-code-provided signal handler from shim code, and …

shim: allow native syscalls from shim's whole .text segment

---

src/main/utility/macros.rs

This adds a `log_once_at_level` (and `warn_once_then_debug`/`warn_once_then_trace`) macro to log a message once at one level, and then at a different level every time after. The caller should indicate somewhere in the log message that it's only being logged once.

Add `log_once` macro

---

src/Cargo.lock
src/Cargo.toml
src/lib/pod/Cargo.toml
src/lib/pod/src/lib.rs
src/lib/shmem/Cargo.toml
src/lib/shmem/src/allocator.rs
src/main/Cargo.toml
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/managed_thread.rs
src/main/host/memory_manager/memory_copier.rs
src/main/host/memory_manager/memory_mapper.rs
src/main/host/memory_manager/mod.rs
src/main/host/syscall/handler/sched.rs
src/main/host/syscall/handler/sysinfo.rs
src/main/host/syscall/io.rs
src/main/lib.rs
src/main/utility/mod.rs

We need to be able to implement this trait from crates outside of `main`. It also makes the crate `no_std`, since we'll need it from `no_std` crates like `linux-api`.

Break Pod into its own crate

---

src/main/host/descriptor/socket/inet/udp.rs
src/main/host/descriptor/socket/unix.rs
src/test/socket/send_recv/test_send_recv.rs

This adds support for the `MSG_TRUNC` flag for `msg_flags` in unix sockets, and adds support for the `MSG_TRUNC` flag in both `flags` and `msg_flags` for unix sockets. The only socket missing `MSG_TRUNC` support in shadow is tcp sockets.

Improve `MSG_TRUNC` support

---

src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/inet/udp.rs
src/main/host/host.rs
src/main/host/network/namespace.rs

The purpose of the handle is to make it harder to accidentally forget to disassociate the socket, to have multiple associations, or to disassociate a different socket address than what was originally associated. For example when re-associating a socket with another address. See for example #2590. This could be made nicer if the network interface was in rust, but I think this is good enough for the time being.

Add an `AssociationHandle` which disassociates the socket when dropped

---

src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/udp.rs
src/test/socket/sockopt/test_sockopt.rs

This adds support for `SO_DOMAIN`, `SO_PROTOCOL`, and `SO_ACCEPTCONN` for tcp and udp.

Support more sockopts for TCP and UDP

---

src/main/host/descriptor/socket/inet/udp.rs
src/test/socket/ioctl/test_ioctl.rs

UDP sockets return the number of bytes in the next received message, not the number of bytes in the receive buffer.

Fix bug in `FIONREAD` ioctl for udp

---

src/main/host/descriptor/socket/inet/udp.rs
src/test/socket/connect/connect.yaml
src/test/socket/connect/test_connect.rs

Fix multiple udp sockets with different peers binding to the same port, and fix a udp socket connecting to an IP on a different interface (ex: connecting to 8.8.8.8 from a socket that's bound to localhost).

Improvements to udp binding and connecting

---

CHANGELOG.md
src/lib/libc_preload/gen_syscall_wrappers_c.py
src/lib/libc_preload/syscall_wrappers.c
src/main/host/syscall/handler/sched.rs
src/test/file/test_file.c

This adds an advisory check in our script for generating syscall wrappers that warns when we generate wrappers for syscalls whose man pages note "C library/kernel differences".
Suppressed most of the syscalls that it was warning about; reviewed some, adding those to either a "definitely suppress" list, or an "allow list".
Removing an incorrect wrapper for `sched_getaffinity` uncovered a bug in our `sched_getaffinity` syscall implementation. Fixes the bug.

libc_preload: check for C library/kernel differences

---

src/lib/linux-api/src/errno.rs
src/main/host/syscall/handler/clone.rs
src/main/host/syscall/handler/eventfd.rs

We could do this in more syscall handlers, but I don't want to make too much of a mess of mixing the nix and linux_api `Errno` types in many places. It's probably best to do the remaining conversion in one go.

Use `linux_api::errno::Errno` in eventfd and clone syscall handlers

---

src/lib/linux-api/Cargo.toml
src/lib/linux-api/src/errno.rs
src/lib/linux-api/src/lib.rs
src/main/Cargo.toml

This adds a "std" feature to linux-api, which if enabled adds a `From<errno::Errno> std::io::Error` conversion and a `TryFrom<std::io::Error> for errno::Errno` conversion.
Since we build shadow and the shim separately, I don't think enabling the "std" feature in shadow should affect the shim which is no_std.

Add `linux_api::errno::Errno`/`std::io::Error` conversions

---

src/lib/linux-api/src/errno.rs
src/main/host/descriptor/eventfd.rs
src/main/host/descriptor/mod.rs
src/main/host/descriptor/pipe.rs
src/main/host/descriptor/shared_buf.rs
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/inet/udp.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/descriptor/timerfd.rs
src/main/host/memory_manager/memory_copier.rs
src/main/host/memory_manager/memory_mapper.rs
src/main/host/memory_manager/mod.rs
src/main/host/process.rs
src/main/host/syscall/handler/fcntl.rs
src/main/host/syscall/handler/ioctl.rs
src/main/host/syscall/handler/mod.rs
src/main/host/syscall/handler/random.rs
src/main/host/syscall/handler/sched.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/handler/time.rs
src/main/host/syscall/handler/timerfd.rs
src/main/host/syscall/handler/uio.rs
src/main/host/syscall/handler/unistd.rs
src/main/host/syscall/io.rs
src/main/host/syscall_types.rs
src/main/host/thread.rs
src/main/network/packet.rs
src/main/utility/syscall.rs

There are still a few places we use the nix type, but this gets rid of most of them.

Replace uses of nix's `Errno` with linux_api's `Errno` in syscall handlers, memory manager, process, etc

---

src/test/test_utils.rs
src/test/time/clock_nanosleep/test_clock_nanosleep.rs
src/test/time/mod.rs

This PR refactors and moves a bunch of functionality written for the `clock_nanosleep` out to the test_utils lib so that it can be re-used in other tests.

Sleep rafactor

---

src/main/host/descriptor/compat_socket.c
src/main/host/descriptor/compat_socket.h
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/inet/udp.rs
src/main/host/network/interface.rs
src/main/host/network/network_interface.c
src/main/host/network/network_interface.h
src/test/socket/ioctl/test_ioctl.rs

This is only supported by Linux for udp sockets, so tcp has been updated to only return `ENOENT`.

Support `SIOCGSTAMP` for inet sockets

---

src/lib/shadow-shim-helper-rs/src/syscall_types.rs
src/main/host/syscall/type_formatting.rs

The `TryFrom<SysCallReg>` has been changed to `From<SysCallReg>` for non-nix bitflags types, and now uses `from_bits_retain`. The `TryFromSyscallReg` has been removed as it doesn't have a purpose anymore.
Since the bitflags types support `From<SysCallReg>`, they can be used directly in the syscall handler arguments now. I tried making this change, but found it made the existing syscall handlers harder to read so I don't think this is worth actually doing.
I also tried a generic `impl<T> From<SysCallReg> for T where T: bitflags::Flags`, but this doesn't work since `bitflags::Flags` is an external trait.

Simplify converting from `SysCallReg` in the strace logger

---

src/lib/shim/Cargo.toml
src/main/Cargo.toml

Both the shim and main crates need `shadow-shim-helper-rs` to have already been built when their build scripts run, so that `shadow-shim-helper-rs`'s generated bindings files are already built.

add shadow-shim-helper-rs to build deps

---

.github/workflows/sanitizers.yml

We don't touch the vasi-sync code often, but when we do it's important to validate that the loom tests still pass.
Ideally we'd only force a run if something in that crate changed, but trying to implement and maintain such conditions have been more trouble than they're worth in the past.

CI: add a loom test

---

src/lib/pod/src/lib.rs

I realized that having interior mutability in a `Pod` type would be bad, so added some documentation disallowing it.

Restrict `UnsafeCell` in `Pod` types

---

.github/workflows/sanitizers.yml
src/lib/vasi-sync/tests/scchannel-tests.rs
src/lib/vasi-sync/tests/scmutex-tests.rs
src/lib/vasi-sync/tests/sync/mod.rs

This gives a little more flexibility, e.g. allowing new tests to be added that need a lower bound without having to change the bound for all the tests.

loom tests: Move preemption bound into individual tests

---

.github/workflows/sanitizers.yml
src/Cargo.lock
src/lib/vasi-sync/Cargo.toml
src/lib/vasi-sync/src/atomic_tls_map.rs
src/lib/vasi-sync/src/lib.rs
src/lib/vasi-sync/src/sync.rs
src/lib/vasi-sync/tests/atomic-tls-map-tests.rs

This should be able to replace the ad-hoc hash table implemented in `shadow_shim::tls`.
It still has somewhat scary safety requirements for users, but should ultimately be an improvement over the current implementation. It also adds refcounting to let us catch some issues.

Create a specialized hash table for the shim's TLS

---

src/lib/shim/shim.c
src/lib/shim/src/lib.rs
src/lib/shim/src/shimlogger.rs

We need at least the Process shared memory in Rust to be able to migrate the signal handling to Rust. Might as well move the others too.

Shim: Move shared memory objects into Rust

---

src/Cargo.toml
src/lib/linux-api/src/exit.rs
src/lib/linux-api/src/lib.rs
src/lib/shim/build.rs
src/lib/shim/shim_syscall.c
src/lib/shim/shim_tls.c
src/lib/shim/shim_tls.h
src/lib/shim/src/lib.rs
src/lib/shim/src/mmap_box.rs
src/lib/shim/src/tls.rs
src/lib/vasi-sync/src/atomic_tls_map.rs
src/lib/vasi-sync/src/lazy_lock.rs
src/lib/vasi-sync/src/sync.rs
src/lib/vasi-sync/tests/lazylock-tests.rs
src/main/host/descriptor/regular_file.c
src/test/golang/CMakeLists.txt

* use `AtomicTlsMap` instead of an ad-hoc equivalent
* Have individual references to thread-local-storage hold a borrowed reference to the corresponding `AtomicTlsMap` entry, which results in a panic if the thread is unregistered while still holding such a reference (instead of undefined behavior)
* Add `MmapBox` and use it for allocations instead of using `mmap` directly; allocate and deallocate the storage for individual threads as needed instead of allocating all up front.
* Get rid of the `static` state in `tls.rs` so that unit tests can be hermetic- no longer need a global lock, and we're able to add  `should_panic` tests (which previously would have poisoned the lock and possibly other state).

Shim TLS improvements

---

src/Cargo.toml
src/lib/shim/src/tls.rs
src/test/clone/CMakeLists.txt

These tests *appear* to no longer be flaky with the new implementation of shim thread local storage. I did have to make some changes to avoid smashing the relatively small stack we use in this test though:
* Enable minimal optimizations in debug builds. Rust has a tendency to put more temporaries on the stack than in C code. Enabling some optimizations lets us optimize many of those away, e.g. when initializing an object that will ultimately live in static or heap memory.
* Reduced the max threads supported by shim TLS from 1000 to 100. 1000 was from when this was a maximum number of threads *ever* for a process. In the new implementation this limit is for *simultaneous* threads per process, so 1000 is probably excessive. This reduces the size of the corresponding table, which seems to …

Fix and reenable clone tests

---

src/Cargo.lock
src/lib/formatting-nostd/Cargo.toml
src/lib/formatting-nostd/src/borrowed_fd_writer.rs
src/lib/linux-api/Cargo.toml
src/lib/shim/Cargo.toml
src/lib/vasi-sync/Cargo.toml

Automated bump to latest version:
```
(cd src/ && cargo upgrade -p rustix --incompatible)
```
Plus manual updates for breaking changes.

Bump rustix from 0.37 to 0.38

---

.dockerignore
.github/workflows/ci_maintenance.yml
.github/workflows/lint.yml
.github/workflows/sanitizers.yml
.gitignore
ci/container_scripts/install_extra_deps.sh
ci/rust-toolchain-nightly.toml
ci/rust-toolchain-stable.toml
docs/install_dependencies.md

Replaces `rust-toolchain.toml` with `rust-toolchain-stable.toml` and `rust-toolchain-nightly.toml`. This consolidates the pinning of the nightly version (used in some CI tests) to one place.
For users/developers, this means the version won't be automatically pinned anymore; they can choose to pin to the CI stable or nightly version by creating a symbolic link to one of these two files.
Alternatively we could check in a symbolic link to pin to the stable version by default, but then if a user wants to change the link to point to the nightly version, it'd be easy to accidentally check in the new link as well.

Rework Rust version pinning

---

src/main/host/syscall/shadow.c
src/main/host/syscall/shadow.h
src/main/host/syscall_handler.c
src/main/host/syscall_numbers.h

We don't use this anymore, and it's one of the few remaining C references to the shmem allocator.

Remove syscall shadow_get_shm_blk

---

src/CMakeLists.txt

- build the shim after shadow
When we run two 'cargo build's at the same time, the build output gets jumbled and things like 'cargo build --timings' don't work as intended. Cargo already parallelizes the builds, so we don't gain much from overcommitting the CPU.
- don't build unit tests twice
The unit tests always need to be rebuilt when we run `cargo test` during our 'rust-unit-tests' test, so there's not much point in building them twice (once during `cargo build` and once during `cargo test`).
- update build comments
We're supposed to be building integration tests without optimizations, but we're currently building them with optimizations. This just adds a TODO since our build script would need to be reorganized to support this.

Updates to rust builds

---

src/main/utility/synchronization/simple_latch.rs

This test has been having occasional spurious failures under miri. e.g. https://github.com/shadow/shadow/actions/runs/5588856718/jobs/10216246666?pr=3077

simple_latch tests: increase test timing threshold

---

.github/workflows/extra_tests.yml

Fetch of sccache release was failing: https://support.github.com/ticket/personal/0/2258460
Was going to disable it in this PR, but it looks like the issue has been resolved. Still worth merging the other couple small tweaks I made to the related code though, I think.

Extra tests workflow: tweaks to sccache

---

.github/workflows/lint.yml
ci/container_scripts/build_and_install.sh
ci/container_scripts/install_deps.sh
ci/container_scripts/install_extra_deps.sh
ci/run.sh
src/test/legacy/run_plugin_test.sh
src/test/tgen/fixed_duration/verify.sh
src/test/tgen/fixed_size/verify.sh
src/test/tor/minimal/run.sh
src/test/tor/minimal/verify.sh

We had a subtle issue in our tor minimal test validation script causing it to ignore some errors.
trinity @ Tor pointed out that shellcheck would've caught it. Tor uses shellcheck in their CI in general.
So I also added a shellcheck lint to our CI and fixed various warnings. I don't think any of these were currently causing issues, but they could potentially have caused issues in the future (e.g. if an unquoted variable value later ended up having spaces in it).
I locally tested `ci/run.sh` since some of the related scripts were being modified. It turns out there were some issues with the rust toolchain files from a previous commit, so I also fixed those.

Fix shell scripts

---

src/main/host/descriptor/compat_socket.c
src/main/host/descriptor/compat_socket.h
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/inet/udp.rs
src/main/host/network/network_interface.c

@robgjansen You had mentioned a long time ago why this `updatePacketHeader` function existed, but I can't remember anymore and I can't find an issue for it. Regardless, I don't think it's needed anymore as its own separate function since it's currently only called immediately after a `pullOutPacket()` and we can just merge them into a single operation (just `pullOutPacket`).
Since this is only relevant to the C TCP sockets, `tcp_networkInterfaceIsAboutToSendPacket` is now called from `LegacyTcpSocket::pull_out_packet`.
(This was added in 840234d0a3a92292.)

Remove `updatePacketHeader` function

---

src/main/host/descriptor/descriptor.c
src/main/host/descriptor/descriptor.h
src/main/host/descriptor/descriptor_table.rs
src/main/host/descriptor/epoll.c
src/main/host/descriptor/mod.rs
src/main/host/process.rs

Add reference counts for `EpollWatch` and `Descriptor`, and remove `DescriptorTable::shutdown_helper`.
Calling `DescriptorTable::shutdown_helper`, which unregisters all epoll descriptors' listeners, would be incorrect if there are still open descriptors to the same epoll file description (e.g. in a forked process).

Rm shutdown helper

---

src/main/host/descriptor/descriptor_table.rs
src/main/host/descriptor/mod.rs

When a Process is forked (without CLONE_FILES), the child gets a copy of the descriptor table. IIUC simply cloning the table should give us the right behavior - the child will gets its own table, with cloned references to the same descriptors.
Progress on https://github.com/shadow/shadow/issues/1987

Make DescriptorTable clonable

---

CHANGELOG.md
docs/shadow_config_spec.md
src/main/core/logger/shadow_logger.rs
src/main/core/main.rs
src/main/core/support/configuration.rs
src/test/CMakeLists.txt
src/test/cli/help-long-expected

In the common use-case of redirecting stdout to a log file, but viewing stderr on the console, it'd be nice to see errors on the console in addition to in the log file. I think this will be particularly helpful for errors that aren't at the very end of the log file. e.g. see the new user debugging experience here: https://gitlab.torproject.org/tpo/core/arti/-/merge_requests/1229#note_2924406
Example:
After locally inserting garbage into `src/test/tor/minimal/conf/tgen.server.graphml.xml`, before this PR:
```
$ (cd build/src/test/tor/minimal/ && rm -rf tor-minimal-shadow.data       &&  /home/jnewsome/projects/shadow/dev/build/src/main/shadow       --data-directory=tor-minimal-shadow.data    --template-directory shadow.data.template  --progress=true …
```

Log errors to stderr in addition to stdout

---

src/main/core/controller.rs
src/main/core/main.rs
src/main/utility/mod.rs

`isatty` can return surprising errors on some file systems. `IsTerminal` interprets such errors as "not a terminal", which is generally the behavior we want. In particular this should fix a crash we're getting in our tor and tgen benchmarks.
Background:
* https://docs.kernel.org/driver-api/ioctl.html#return-code
* https://github.com/containers/podman/issues/120700
Crash example:
* https://github.com/shadow/benchmark/actions/runs/5746502577/job/15576071390
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ENOSYS', main/core/main.rs:146:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

Use std::io::IsTerminal instead of nix::unistd::isatty

---

src/lib/shadow-shim-helper-rs/src/syscall_types.rs
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/syscall/handler/uio.rs
src/test/socket/send_recv/test_send_recv.rs

read() and recv() with 0-length buffers seem to have different behaviour. And the man page for recv(2) seems to be wrong in regard to the behaviour of read() with 0-length datagrams. Tests were added for both cases.

Fix `read()` and `recv()` with 0-length buffer

---

src/main/host/descriptor/socket/inet/udp.rs
src/main/host/network/namespace.rs
src/test/socket/send_recv/test_send_recv.rs

I don't think this is a proper fix since it means that localhost packets from sockets bound to 0.0.0.0 will be sent over the internet interface rather than the loopback interface. But I don't think there's anything else we can do here. The C TCP code does [something](https://github.com/shadow/shadow/issues/3088#issuecomment-1668389960) slightly different, but I don't think it's better than using just the internet interface.
Closes #3088.

Fix sending packets from sockets bound to 0.0.0.0

---

src/lib/shadow-shim-helper-rs/src/explicit_drop.rs
src/lib/shadow-shim-helper-rs/src/lib.rs
src/lib/shadow-shim-helper-rs/src/rootedcell/cell.rs
src/lib/shadow-shim-helper-rs/src/rootedcell/rc.rs
src/lib/shadow-shim-helper-rs/src/rootedcell/refcell.rs
src/main/core/worker.rs
src/main/host/context.rs
src/main/host/host.rs
src/main/host/process.rs

This is in preparation for moving the `DescriptorTable` into a `RootedRc`. Since the object containing the `DescriptorTable` (currently `Process`, but soon to be `Thread`) is also in a `RootedRc`, safely dropping becomes a bit complex.
In the past when we've run into this, we've solved it by having the `Drop` impl of the "outer" type get the `Root` from the thread-local `Worker`, but in general we're trying to move away from implicit thread-local accesses in favor of explicit parameter passing.
This first adds `RootedRc::into_inner`. This lets us extract the inner value when dropping the last strong reference of a `RootedRc`. The caller is then able to recursively safely destruct the inner value. This has the downside though of requiring any call site that wants to destruct a …

Add better support for recursive RootedRc

---

src/Cargo.lock
src/lib/linux-api/Cargo.toml
src/lib/linux-api/src/ldt.rs
src/lib/linux-api/src/lib.rs
src/lib/linux-api/src/signal.rs
src/lib/shim/src/signals.rs
src/test/Cargo.toml
src/test/clone/CMakeLists.txt
src/test/clone/clone-nomm.yaml
src/test/clone/clone_leader_exits_early.yaml
src/test/clone/test_clone.rs
src/test/clone/test_clone_leader_exits_early.c

This is in preparation to add additional clone tests as we extend clone functionality.
Since we're not setting up thread local storage in these tests, we can't safely call libc functions from the child threads. Using Rust lets use no_std alternatives that don't use thread local storage.

Migrate most bare clone tests to Rust

---

src/Cargo.lock
src/lib/shadow-shim-helper-rs/Cargo.toml
src/lib/shadow-shim-helper-rs/src/emulated_time.rs
src/lib/shadow-shim-helper-rs/src/simulation_time.rs
src/main/network/router/codel_queue.rs

This will allow `SimulationTime` and `EmulatedTime` to be used with the tcp library.

Impl tcp time traits for `SimulationTime` and `EmulatedTime`

---

src/Cargo.lock
src/Cargo.toml
src/lib/linux-api/Cargo.toml
src/lib/shadow-shim-helper-rs/src/rootedcell/refcell.rs
src/main/core/worker.rs
src/main/host/descriptor/descriptor_table.rs
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/tcp.c
src/main/host/process.rs
src/main/host/syscall/epoll.c
src/main/host/syscall/fcntl.c
src/main/host/syscall/file.c
src/main/host/syscall/fileat.c
src/main/host/syscall/handler/clone.rs
src/main/host/syscall/handler/eventfd.rs
src/main/host/syscall/handler/fcntl.rs
src/main/host/syscall/handler/ioctl.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/handler/timerfd.rs
src/main/host/syscall/handler/uio.rs
src/main/host/syscall/handler/unistd.rs
src/main/host/syscall/ioctl.c
src/main/host/syscall/mman.c
src/main/host/syscall/poll.c
src/main/host/syscall/uio.c
src/main/host/syscall/unistd.c
src/main/host/thread.rs
src/test/Cargo.toml
src/test/clone/clone.yaml
src/test/clone/test_clone.rs

`fork` and `fork`-like syscalls have the behavior of `clone` without the `CLONE_FILES` flag set: the child gets a copy of the parent's descriptor table.
While it's rare in the wild to use `clone` to create a new thread without setting `CLONE_FILES`, testing this use-case gets us closer to supporting `fork` etc.

Support clone with CLONE_FILES unset

---

src/lib/linux-api/Cargo.toml
src/lib/linux-api/src/exit.rs
src/lib/linux-api/src/posix_types.rs
src/lib/linux-api/src/sched.rs
src/lib/linux-api/src/signal.rs
src/lib/shim/src/signals.rs
src/test/Cargo.toml
src/test/clone/test_clone.rs

Doesn't pass in shadow yet.
This also includes some additions and tweaks to linux-api. Some of this ended up being unused for now; I intended to write an analogue of `wait_for_thread_exit` for a child process, but it appears that `kill(child_pid, 0)` "succeeds" (i.e. doesn't return `ESRCH`) if the child hasn't been reaped, even if no exit signal was specified. (I also don't want the first version of this test to use `waitpid`, since that implementation is a little further down the road)

Add a basic fork test

---

docs/shadow_config_spec.md
src/Cargo.lock
src/main/Cargo.toml
src/main/build.rs
src/main/core/manager.rs
src/main/core/support/configuration.rs
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/descriptor/socket/inet/udp.rs
src/main/host/descriptor/socket/mod.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/host.rs
src/main/host/network/interface.rs
src/main/host/network/namespace.rs
src/main/host/network/network_interface.c
src/main/host/network/network_interface.h
src/main/host/syscall/handler/socket.rs
src/main/network/packet.rs
src/main/routing/packet.c
src/test/cli/help-long-expected
src/test/socket/accept/CMakeLists.txt
src/test/socket/bind/CMakeLists.txt
src/test/socket/socket/CMakeLists.txt
src/test/tcp/CMakeLists.txt

This adds a new TCP socket using the tcp library from #3098. This has the same current limitations of the tcp library (no retransmission, congestion control, etc). This also doesn't support ioctl(), shutdown(), most socket options, and some other things.
This TCP socket can be enabled with the experimental `--use-new-tcp true` flag. A few tests have been added that use this flag to test the new TCP socket. Some other tests are close to passing, but need retransimssion support before they can be enabled.
Current passing socket tests:
- socket-new-tcp-shadow
- bind-new-tcp-shadow
- accept-new-tcp-shadow
- tcp-nonblocking-epoll-lossless-new-tcp-shadow
- tcp-nonblocking-select-lossless-new-tcp-shadow
- tcp-blocking-loopback-new-tcp-shadow
- tcp-nonblocking-poll-lossless-new-tcp-shadow
- …

Add new TCP socket implementation

---

src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/descriptor/socket/inet/udp.rs
src/main/host/host.rs
src/main/host/network/interface.rs
src/main/host/network/namespace.rs
src/main/host/network/network_interface.c
src/main/host/network/network_interface.h

I changed `networkinterface_isAssociated` to check only a single 4-tuple. This moves the complexity further up, and calling code can choose whether or not to also check the more-generic association (peer 0.0.0.0:0). This doesn't fix any bugs in the network interface code.
This is a follow up from https://github.com/shadow/shadow/pull/3105#discussion_r1293687008.

Reorganize `networkinterface_isAssociated`

---

src/Cargo.lock
src/lib/vasi-sync/Cargo.toml
src/lib/vasi-sync/src/atomic_tls_map.rs
src/lib/vasi-sync/tests/atomic-tls-map-tests.rs

Intended for use after fork; we can't safely drop values belonging to other threads, but can safely forget about and overwrite them.

Add AtomicTlsMap::forget_all

---

src/lib/formatting-nostd/src/borrowed_fd_writer.rs
src/lib/formatting-nostd/src/utf8.rs
src/lib/shim/src/tls.rs
src/lib/shmem/src/allocator.rs
src/lib/tcp/src/tests/mod.rs
src/lib/tsc/src/lib.rs
src/lib/vasi-sync/benches/scchannel.rs
src/lib/vasi-sync/tests/atomic-tls-map-tests.rs
src/lib/vasi-sync/tests/scchannel-tests.rs
src/main/host/syscall/formatter.rs
src/main/host/syscall_condition.rs
src/main/network/relay/token_bucket.rs
src/main/network/router/codel_queue.rs
src/main/utility/byte_queue.rs

`cargo clippy --fix` can be helpful for fixing clippy warnings. There are currently a lot of things in our code it changes though, making it awkward to use in a PR since it'll change code unrelated to the PR.
I'm not sure why, but `cargo clippy --fix` warns about and fixes things that just `cargo clippy` doesn't complain about. Maybe it has a different default policy set.
This PR includes some manual fixes as well for things that `clippy --fix` fixes suboptimally, or complains about without fixing.

cargo clippy --fix

---

src/main/core/work/task.rs
src/main/host/descriptor/mod.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/memory_manager/mod.rs
src/main/host/syscall/handler/mod.rs
src/main/host/timer.rs
src/main/utility/counter.rs
src/main/utility/pcap_writer.rs

I don't really think this should be a warning, but it's easy to work around anyways.
```
warning: unused return value of `Box::<T>::from_raw` that must be used
--> main/utility/pcap_writer.rs:184:18
|
184 |         unsafe { Box::from_raw(pcap) };
|                  ^^^^^^^^^^^^^^^^^^^
|
= note: call `drop(Box::from_raw(ptr))` if you intend to drop the `Box`
help: use `let _ = ...` to ignore the resulting value
|
184 |         unsafe { let _ = Box::from_raw(pcap); };
|                  +++++++                    +
```

Fix warning in rust 1.72 beta

---

src/lib/formatting-nostd/src/borrowed_fd_writer.rs
src/lib/shim/src/signals.rs
src/lib/syscall-logger/src/lib.rs
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/host.rs
src/main/host/syscall/formatter.rs
src/main/host/syscall/handler/unistd.rs
src/main/host/syscall_types.rs

The latest rustfmt version (the version bundled with cargo 1.72) now formats `let else` expressions, so there's some churn in our code. It makes some questionable formatting choices, but :shrug:.
```diff
@@ -610,7 +612,8 @@ mod export {
let socket = unsafe { socket.as_ref() }.unwrap();
#[allow(irrefutable_let_patterns)]
-        let InetSocket::LegacyTcp(socket) = socket else {
+        let InetSocket::LegacyTcp(socket) = socket
+        else {
panic!("Socket was not a legacy TCP socket: {socket:?}");
};
```
It also adds semicolons:
```diff
@@ -294,7 +294,7 @@ mod export {
let logging_mode = logging_mode.into();
let Some(logging_mode) = logging_mode else {
// logging was disabled
-            return result.into()
+            return result.into();
};
```

Format with rustfmt 1.6.0-stable (cargo 1.72)

---

CHANGELOG.md
src/lib/linux-api/src/signal.rs
src/main/core/support/configuration.rs
src/main/host/host.rs
src/main/host/process.rs
src/main/host/syscall/handler/clone.rs
src/test/Cargo.toml
src/test/clone/test_fork.rs

Have child processes signal their parents on death.
Add additional checks for when a dead process should be kept around as a zombie (e.g. *not* when the parent process created the child with no exit signal, or has themselves blocked the child exit signal).

Improve process exit handling

---

src/test/tgen/fixed_duration/verify.sh
src/test/tgen/fixed_size/verify.sh

Fixing the bug in the verification script causes the `tgen-duration-1mbit_300ms-1stream-shadow` test to fail:
```text
Verification failed: 1mbit_300ms net expected 106250 got client=88716 server=119740
```
As a workaround, I reduced the required throughput for this test. This PR also cherry picks a commit from #3125 which modifies the verification script.

Fix tgen test verification script

---

src/lib/tcp/src/connection.rs
src/lib/tcp/src/tests/send_recv.rs

I missed this before. It was previously skipping sequence number ranges and somehow still worked.

Fix bug in rust tcp sequence number

---

src/lib/tcp/src/buffer.rs
src/lib/tcp/src/connection.rs
src/lib/tcp/src/lib.rs
src/lib/tcp/src/states.rs
src/lib/tcp/src/tests/mod.rs
src/lib/tcp/src/tests/send_recv.rs
src/lib/tcp/src/tests/transitions.rs
src/lib/tcp/src/tests/window_scale.rs
src/lib/tcp/src/window_scaling.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/descriptor/tcp.c
src/main/network/packet.rs
src/main/routing/packet.c
src/main/routing/packet.h

Window scaling is pretty simple: if each peer sends the window scale option in the syn packet then they both use window scaling, and window scaling is only used in non-syn packets. But handing the edge cases makes this a bit of a mess.

Add window scaling to rust tcp

---

src/lib/tcp/src/buffer.rs
src/lib/tcp/src/connection.rs
src/lib/tcp/src/lib.rs
src/lib/tcp/src/states.rs
src/lib/tcp/src/tests/mod.rs
src/lib/tcp/src/tests/send_recv.rs
src/lib/tcp/src/tests/transitions.rs
src/lib/tcp/src/tests/window_scale.rs
src/main/host/descriptor/socket/inet/tcp.rs

Since each `sendmsg` call by the application would add its own chunk to the send buffer, this meant that each chunk passed in the `sendmsg` call would be sent in its own packet even if the chunk was small. Now a packet can contain several chunks, so chunks passed in multiple `sendmsg` calls will be combined together into a single packet.
~A future PR will reduce the number of small chunks so that there generally will only be one or two chunks per packet.~

Coalesce chunks when sending packets in rust tcp

---

src/Cargo.lock
src/lib/shadow-shim-helper-rs/Cargo.toml
src/lib/shmem/Cargo.toml
src/lib/vasi-sync/Cargo.toml
src/main/Cargo.toml
src/main/host/memory_manager/memory_mapper.rs
src/main/utility/childpid_watcher.rs
src/test/Cargo.toml

The latest nix version makes three main changes:
- no default cargo features
- old epoll api deprecated
- many (but not all) functions take `AsFd` types instead of `RawFd` (an integer)
This third point is particularly painful in tests where we use integer file handles everywhere. I've left the tests on nix 1.26 for now, but it seems worthwhile to get this upgrade out of the way for the actual shadow code. If we're going to need to update a lot of tests, it's probably worth changing them to rustix or linux-api instead.
Also I added nix cargo features to the `shadow-shim-helper`, `shadow-rs`, and `shadow-tests` crates. Ideally we should add all of the nix features to every crate that requires them, but this would probably quickly become out of date anyways so I haven't bothered with that. …

Partially upgrade nix to 1.27.1

---

src/main/core/sim_config.rs
src/main/host/host.rs
src/main/host/managed_thread.rs
src/main/host/process.rs
src/main/utility/mod.rs
src/test/static-bin/CMakeLists.txt

Our implementation of `execve` will spawn a new `ManagedThread`. Unlike for processes that are spawned directly from shadow's config file, we'll want to gracefully return an error instead of panicking when this fails.
Progress on #2988

Make spawning processes fallible

---

src/main/core/manager.rs
src/main/host/host.rs
src/main/host/managed_thread.rs
src/main/host/process.rs
src/main/utility/mod.rs

When using `ManagedThread::spawn` to help implement `execve`, we'll want to ensure that shadow's `LD_PRELOAD`'d libraries are injected into the new processes as well (in case the parent didn't pass through it's own `LD_PRELOAD` environment through to the child's environment).
Progress on #2988

Move preload injection to ManagedThread::spawn

---

src/lib/syscall-logger/src/lib.rs
src/main/host/syscall/formatter.rs

Previously if a syscall blocked, it wasn't recorded in the strace file until if and when it ran again and completed. Recording blocked syscalls is slightly redundant since it logs the syscall and parameters multiple times, but makes it easier to see why control switched to another thread, and logs syscalls that blocking and never complete, e.g. because another thread in the process called `exit_group`, the simulation ended, or in the (unmerged) implementation of execve, which "blocks" and never returns.
e.g.
```
00:00:01.000000000 [tid 1000] clone(17, 0x0, 0x0, 0x0, 0x0) = 1001
00:00:01.000000000 [tid 1001] write(4, "*", 1) = 1
00:00:01.000000000 [tid 1001] exit_group(...) = <native>
00:00:01.000000000 [tid 1000] read(3, 0x7fffffffe707, 1) = 1
```
->
```
00:00:01.000000000 [tid 1000] …
```

syscall-logger: log blocked syscalls

---

docs/compatibility_notes.md
examples/apps/nginx/nginx.conf

`fork` is now supported, but there are other issues. See https://github.com/shadow/shadow/issues/3174

nginx example: update explanation for disabling worker processes

---

src/lib/linux-api/src/signal.rs
src/main/host/process.rs
src/main/host/syscall/handler/wait.rs
src/test/clone/test_fork.rs

Whether a signaled process generates a core dump depends on platform conditions outside of our control (see `core(5)`). To avoid different simulation results depending on whether a core was actually dumped, which in turn depends on the system configuration, we should always report that it hasn't been.

Don't report core dumps

---

src/lib/tcp/src/buffer.rs
src/lib/tcp/src/connection.rs
src/lib/tcp/src/states.rs
src/lib/tcp/src/tests/send_recv.rs

- Improves the handling of TCP resets.
- Fixes an incorrect packet payload size calculation.
- Now allows reading data remaining in the receive buffer of the "closed" TCP state. There isn't yet a code path that allows this, since if there is data remaining in the receive buffer when a socket is `close()`d, the connection will be reset and the buffer cleared. It is possible to read the remaining data in the receive buffer when `shutdown()` is used to reach the "closed" state, but the rust TCP code doesn't support `shutdown()` yet.

Improve rust tcp reset handling

---

docs/shadow_config_spec.md
src/main/core/support/configuration.rs
src/test/cli/help-long-expected

Progress on https://github.com/shadow/shadow/issues/2581
I'm still on the fence about ripping out entirely. I think we definitely want to disable by default so that `fork` works by default. I'd feel better waiting a release or two to give ourselves a chance to change our minds before removing it.

Disable the MemoryManager by default

---

docs/limitations.md
src/Cargo.lock
src/lib/preload-libc/gen_syscall_wrappers_c.py
src/lib/preload-libc/syscall_wrappers.c
src/lib/shim/src/clone.rs
src/main/host/syscall/handler/clone.rs
src/test/Cargo.toml
src/test/clone/test_fork.rs

The implementation isn't strictly correct, because we effectively implement `vfork` as a synonym for `fork` (and likewise ignore `CLONE_VFORK|CLONE_VM` flags to `clone` and `clone3`).
In cases where `vfork` is treated as a "faster `fork`", this should work correctly. Confirmed with new tests that exercise `libc::posix_spawn` and `std::process::Command::spawn`.
It's possible though for a managed process to depend on implementation details of `vfork` that we don't honor. e.g. they could rely on the parent being paused until the child `exec`'s, or on having writes to memory by the child be visible to the parent. For this reason we log a warning when executing this code-path.
This seems preferable to the previous state of returning an error for `vfork`, since none of the uses I've found fall …

Implement vfork

---

src/main/core/logger/shadow_logger.rs
src/main/core/scheduler/mod.rs
src/main/core/worker.rs
src/main/utility/legacy_callback_queue.rs

We had some extra layers of lazy initialization in some globals and thread-locals that are no longer needed with improvements to const-initialization support.
Theoretically this should save a little overhead on every access to these, but it probably won't make a measurable difference in most sims.

Clean up unnecessary lazy init

---

src/lib/tcp/notes/shutdown.md
src/lib/tcp/src/lib.rs
src/lib/tcp/src/states.rs
src/lib/tcp/src/tests/mod.rs
src/lib/tcp/src/tests/send_recv.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/test/socket/shutdown/CMakeLists.txt
src/test/socket/shutdown/test_shutdown.rs

Also checks for any async errors when `recvmsg()` is called.

Support `shutdown()` for rust tcp sockets

---

src/lib/tcp/src/lib.rs
src/lib/tcp/src/states.rs
src/lib/tcp/src/tests/mod.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/descriptor/tcp.c
src/test/socket/connect/test_connect.rs

These sockets were returning the wrong value when connect() was called on a listening socket. The C TCP sockets were panicking due to a failed assert.

Fix return value for connect() with unix and tcp sockets

---

.github/workflows/extra_tests.yml
ci/rust-toolchain-nightly.toml
ci/rust-toolchain-stable.toml
src/Cargo.lock
src/lib/formatting-nostd/Cargo.toml
src/lib/linux-api/Cargo.toml
src/lib/pod/Cargo.toml
src/lib/shim/Cargo.toml
src/lib/syscall-logger/Cargo.toml
src/lib/tcp/Cargo.toml
src/lib/vasi-macro/Cargo.toml
src/lib/vasi-sync/Cargo.toml
src/main/Cargo.toml
src/test/Cargo.toml

- tor and tgen version in the CI
- rust stable and nightly versions in the CI
- cargo dependencies, excluding nix (see #3141) and clap (breaks our cli test; seems to use the terminal width even though stdout and stderr are not the terminal)

Upgrade dependencies

---

src/main/host/descriptor/socket/inet/udp.rs

UDP ignores some `setsockopt()` arguments with comments that tor/tgen/libevent use them, but these must have been incorrectly applied to UDP sockets since tor/tgen don't use UDP. UDP sockets now will fail if `setsockopt()` is used with `SO_REUSEADDR`, `SO_REUSEPORT`, or `SO_KEEPALIVE`, instead of just ignoring them. We continue to ignore `SO_BROADCAST` instead of failing since that is needed with UDP sockets for Go.
This may break some existing applications, but I think that's fine since we didn't correctly handle these sockopts anyways.

Correctly fail for unsupported udp sockopts

---

src/main/host/descriptor/epoll/mod.rs
src/main/host/descriptor/eventfd.rs
src/main/host/descriptor/mod.rs
src/main/host/descriptor/pipe.rs
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/mod.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/descriptor/socket/inet/udp.rs
src/main/host/descriptor/socket/mod.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/descriptor/timerfd.rs
src/main/host/syscall/handler/fcntl.rs
src/main/host/syscall/handler/ioctl.rs
src/main/host/syscall/handler/socket.rs
src/main/host/syscall/handler/uio.rs

I've been holding off on this one until epoll was merged.

Rename `get_status()` to `status()`

---

ci/rust-toolchain-nightly.toml
ci/rust-toolchain-stable.toml
src/lib/shadow-shim-helper-rs/src/simulation_time.rs
src/main/host/syscall/handler/socket.rs
src/main/utility/byte_queue.rs

Also fixes two minor clippy warnings and a documentation warning.

Upgrade rust in CI to 1.73.0

---

src/main/host/descriptor/epoll/mod.rs
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/udp.rs
src/main/host/descriptor/timerfd.rs
src/main/host/syscall/handler/clone.rs
src/main/host/syscall/handler/epoll.rs
src/main/host/syscall/handler/fcntl.rs
src/main/host/syscall/handler/futex.rs
src/main/host/syscall/handler/mman.rs
src/main/host/syscall/handler/time.rs
src/main/host/syscall/handler/timerfd.rs
src/main/utility/macros.rs

Now the "(LOG_ONCE)" will be prepended automatically. I think this is an improvement so that you don't need to remember to add it, and they will stay consistent.

Remove the "(LOG_ONCE)" requirement from `warn_once_*` macros

---

ci/rust-toolchain-nightly.toml
ci/rust-toolchain-stable.toml
src/lib/gml-parser/src/parser.rs
src/lib/shadow-shim-helper-rs/src/simulation_time.rs
src/lib/shim/src/syscall.rs
src/lib/tcp/src/connection.rs
src/main/build.rs
src/main/core/main.rs
src/main/core/worker.rs
src/main/host/syscall/handler/fcntl.rs
src/main/host/syscall/handler/unistd.rs
src/main/network/packet.rs
src/main/network/relay/mod.rs

Also upgrades to the latest rust stable/nightly versions in the CI.

Fix clippy warnings in rust 1.74 and rust 1.75-beta

---

src/main/host/network/network_interface.c
src/main/host/network/network_queuing_disciplines.c

The queue may change in between when we pop the socket and when we re-add the socket. This can lead to duplicate entries in the queue if we don't check before re-adding. I'm not exactly sure what the implication of this is. I think it can lead to some sockets being prioritized over others.
**Edit:** [No change](https://github.com/shadow/benchmark-results/blob/master/tor/2023-11-27-T05-35-50/README.md) in performance or simulation behaviour in a 10% network benchmark.

Fix a bug in `_networkinterface_pop_next_packet_out`

---

src/main/core/scheduler/logical_processor.rs
src/main/host/host.rs
src/main/host/process.rs
src/main/host/thread.rs

These are nightly lints, but I think they're an improvement. Example:
```text
warning: this bound is already specified as the supertrait of `std::iter::ExactSizeIterator`
--> main/core/scheduler/logical_processor.rs:75:15
|
75 |     ) -> impl std::iter::Iterator<Item = usize> + Clone + std::iter::ExactSizeIterator {
|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#implied_bounds_in_impls
= note: `#[warn(clippy::implied_bounds_in_impls)]` on by default
help: try removing this bound
|
75 -     ) -> impl std::iter::Iterator<Item = usize> + Clone + std::iter::ExactSizeIterator {
75 +     ) -> impl Clone + std::iter::ExactSizeIterator<Item = usize> {
```

Fix some rust nightly clippy lints

---

src/Cargo.lock
src/Cargo.toml
src/lib/shadow-build-info/Cargo.toml
src/lib/shadow-build-info/build.rs
src/lib/shadow-build-info/src/lib.rs
src/main/Cargo.toml
src/main/build.rs
src/main/core/main.rs

This improves the incremental build time if you're updating code that is *not* in `src/main/`. This improves incremental compilation in this case by about 8 seconds on my laptop since it skips the build script in `src/main/`. It still needs to (incrementally) rebuild `src/main/` though, which takes about 4 seconds.
This also makes small formatting changes to the `shadow --show-build-info` text.

Move git and timestamp info to new crate

---

src/Cargo.toml

This noticeably reduces the runtime of build scripts during incremental builds, and does not seem to significantly increase the build time during clean builds. The shadow-rs build script run time reduces from 9 seconds to 4 seconds on my laptop.

Use 'opt-level = 3' for build scripts

---

CHANGELOG.md
README.md

Also added a README change that removes a mention of `fork` as a non-working syscall.

Add missing changelog entries

---

CMakeLists.txt

This seems like it was accidentally bumped during the shadow version bump in 172f88c7b.

Fix bumped clang version check

---

src/lib/linux-api/src/futex.rs
src/main/utility/synchronization/simple_latch.rs

This adds a `libc_futex` helper to the simple latch code. Originally I was going to use the linux-api library so I added futex support to that, but then remembered that it won't work with miri. I included the linux-api code anyways since it might be useful in the future, and is a little nicer to use than the rustix equivalent since it takes a `&AtomicU32` instead of a `*mut u32`.

Add futex helpers

---

.github/workflows/ci_maintenance.yml
.github/workflows/extra_tests.yml
.github/workflows/run_tests.yml
codecov.yml
docs/supported_platforms.md
src/Cargo.lock
src/lib/formatting-nostd/Cargo.toml
src/lib/linux-api/Cargo.toml
src/lib/log-c2rust/Cargo.toml
src/lib/pod/Cargo.toml
src/lib/shadow-build-info/Cargo.toml
src/lib/shim/Cargo.toml
src/lib/syscall-logger/Cargo.toml
src/lib/tcp/Cargo.toml
src/lib/vasi-macro/Cargo.toml
src/lib/vasi-sync/Cargo.toml
src/main/Cargo.toml
src/test/Cargo.toml

- Rust was already updated in #3257
- Codecov access has now been revoked (as decided in #3143)
Closes #3197

CI and repo maintenance

---

docs/SUMMARY.md
docs/profiling.md

The documentation on profiling was very out of date, including references to build options that no longer exist, plugins, and elf-loader. I went ahead and re-wrote most of it to reflect good strategies for the current architecture.

update profiling documentation

---

docs/pull_requests.md

This procedure can be done without adding and removing the contributor repo as a remote.

Document rebasing a contributor PR

---

src/lib/linux-api/rename.py

The previous version would accidentally rename `const` functions. For example:
```rust
pub const fn foo() {}
```
would be renamed to:
```rust
pub const LINUX_fn foo() {}
```
The updated version now requires a semicolon in the regex: `r"pub const (\w+): "`
I also regenerated the bindings to make sure this doesn't change any of the existing bindings.

Fix bug in linux-api rename script

---

src/main/host/syscall/type_formatting.rs

From https://github.com/shadow/shadow/pull/2815#discussion_r1152382178.
If the strace logger is unable to read some memory, a `<invalid>` tag will be added after the pointer. This matches when an invalid flag is passed to a syscall.
There are two downsides to this change.
1. Some syscall arguments allow NULL values, but the strace logger will show a NULL as "Invalid". For example this occurs with the address length pointer argument to `recvfrom`.
2. We don't always try to read pointers, so some pointers might be invalid but we never try to read them and they never get the "invalid" tag.

Add context to strace output when we can't read memory

---

src/main/host/syscall/handler/mod.rs

The assertion that was here can (and did, once, for me) fail, and isn't needed.

syscallhandler: handle WARNED_SET race condition

---

src/lib/tcp/src/connection.rs
src/lib/tcp/src/lib.rs
src/lib/tcp/src/states.rs
src/lib/tcp/src/tests/mod.rs
src/lib/tcp/src/tests/send_recv.rs
src/main/host/descriptor/epoll/entry.rs
src/main/host/descriptor/epoll/mod.rs
src/main/host/descriptor/eventfd.rs
src/main/host/descriptor/mod.rs
src/main/host/descriptor/pipe.rs
src/main/host/descriptor/shared_buf.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/descriptor/socket/inet/udp.rs
src/main/host/descriptor/socket/unix.rs
src/main/host/descriptor/tcp.c
src/test/Cargo.toml
src/test/epoll/CMakeLists.txt
src/test/epoll/epoll-edge-rs.yaml
src/test/epoll/test_epoll.rs
src/test/epoll/test_epoll_edge.rs

EDITED: I have already implemented this feature for tcp sockets, udp sockets, unix domain sockets, pipes, eventfds.

Edge-triggered epoll events

---

src/main/core/worker.rs
src/main/host/context.rs
src/main/host/host.rs
src/main/host/process.rs
src/main/host/syscall/handler/clone.rs
src/main/host/syscall/handler/wait.rs
src/main/host/thread.rs

Audited calls to explicit_drop and:
* Used `ExplicitDropper` in cases where the code might otherwise return early or panic without explicitly dropping.
* Made `Process` `ExplicitDrop` to drop its internal `RootedRc`s. (Normally they would have already been dropped anyways, but possibly not e.g. in case of a panic)
* Changed various calls of `explicit_drop` to `RootedRc::explicit_drop_recursive` to ensure the inner value also gets explicitly dropped if that was the last reference.
I didn't see any "normal" early returns that these changes fix, but they may prevent some confusing "double panics" in case of panic, and makes the code more robust in case early returns get added at some point in the future.

More explicit_drop cleanup

---

CHANGELOG.md
src/main/host/syscall/syscall_condition.c

The previous condition for clearing the trigger listener is no longer correct, since TRIGGER_CHILD doesn't take an object. As a result we were failing to clear the listener after `wait4` blocked when the thread ran again.
This resulted in duplicate child triggers, and then duplicate wakeup events, which would in turn schedule more duplicate triggers, resulting in an exponential slowdown after repeated `wait4` usage.

Fix exponential slowdown in wait4 syscall

---

src/Cargo.lock
src/lib/linux-api/Cargo.toml
src/lib/linux-api/build.rs
src/lib/log-c2rust/Cargo.toml
src/lib/logger/Cargo.toml
src/lib/shadow-build-common/Cargo.toml
src/lib/shadow-build-common/src/lib.rs
src/lib/shadow-shim-helper-rs/Cargo.toml
src/lib/shim/Cargo.toml
src/lib/tsc/Cargo.toml
src/lib/vasi-sync/Cargo.toml
src/main/Cargo.toml
src/test/Cargo.toml

When building the tests we also build extra stuff that we don't need, for example the linux-api C bindings. This PR reduces the build time of the tests from 66 seconds to 42 seconds (207 compilation units to 150) when built with `./setup build --test`, as documented in the report from `cargo build --timings`. The next most problematic crates are the linux-api, vasi-sync, formatting-nostd/toml-edit, and neli crates due to their use of syn and related proc macros, but there's not much we can do about those.
Partial graph of the time taken by the test crates after this PR:

Reduce the build time of the tests

---

CMakeLists.txt

This adds a CMake warning if Go 1.21.x is installed when building Shadow. I don't see a nice way of enabling this check only when the `--extra` flag is used, so we need to always perform this check even if the `--extra` flag isn't used. For this reason I've made it a warning rather than an error. For example:
```text
$ ./setup build --test --extra
2024-03-12 23:39:35,595 [INFO] running 'cmake /shadow -DCMAKE_INSTALL_PREFIX=/root/.local -DCMAKE_BUILD_TYPE=Release -DSHADOW_TEST=ON -DCMAKE_PREFIX_PATH=' from '/shadow/build'
-- System name: Linux
-- System version: 5.15.0-91-generic
-- System processor: x86_64
-- CMAKE_MODULE_PATH = /shadow/cmake/
CMake Warning at CMakeLists.txt:82 (MESSAGE):
Go version '1.21.7' is not supported.  Some extra tests will likely fail.
See issue #3267.
-- …
```

Show warning if Go 1.21.x is installed

---

.github/workflows/run_tests.yml

See https://github.com/shadow/shadow/issues/3267#issuecomment-2007940284.
Fedora 38 is EOL on May 18, so our support policy lets us drop this from our supported platforms soon anyways. Since the non-extra tests don't require Go, I don't think we need to update anything in our documentation (for example golang isn't listed as a dependency). We do have a CMake warning at build-time if a broken Go version is installed.
This will also require removing Fedora 38 from the required GitHub tests.

Remove Fedora 38 from the CI tests

---

src/lib/linux-api/src/signal.rs
src/lib/linux-api/src/time.rs
src/lib/shadow-shim-helper-rs/src/shim_shmem.rs
src/lib/shim/src/syscall.rs
src/lib/shmem/src/raw_syscall.rs
src/main/core/manager.rs
src/main/core/work/task.rs
src/main/core/worker.rs
src/main/host/host.rs
src/main/host/managed_thread.rs
src/main/host/network/namespace.rs
src/main/host/process.rs
src/main/host/syscall/handler/wait.rs
src/main/host/syscall/types.rs
src/main/host/thread.rs
src/main/shadow.rs
src/main/utility/counter.rs
src/main/utility/shm_cleanup.rs
src/test/signal/test_signals.rs
src/test/test_utils.rs
src/test/time/mod.rs

This fixes some rust and clippy warnings in the latest beta (the stable is to be released in a few days) and in rust nightly.

Fix rust/clippy warnings

---

src/Cargo.toml

As of Rust 1.77, release builds are stripped of debugging symbols by default. That's typically not what we want, since we do want useful backtraces etc, and don't care so much about the shadow binary size.

Don't strip debug symbols in release builds

---

src/lib/linux-api/src/signal.rs
src/main/host/process.rs
src/main/host/syscall/handler/signal.c
src/main/host/syscall/handler/signal.h
src/main/host/syscall/handler/signal.rs

I changed two `ENOSYS` return values to `ENOTSUP`. I've found it to be confusing when a shadow syscall handler returns `ENOSYS`, so I think `ENOTSUP` is more clear.

Move the `kill` syscall handler to rust

---

src/lib/shadow-shim-helper-rs/build.rs
src/lib/shadow-shim-helper-rs/src/shim_event.rs
src/lib/shadow-shim-helper-rs/src/syscall_types.rs
src/lib/shim/src/syscall.rs
src/lib/syscall-logger/src/lib.rs
src/main/build.rs
src/main/host/descriptor/mod.rs
src/main/host/managed_thread.rs
src/main/host/syscall/condition.rs
src/main/host/syscall/formatter.rs
src/main/host/syscall/handler/fcntl.c
src/main/host/syscall/handler/fcntl.rs
src/main/host/syscall/handler/file.c
src/main/host/syscall/handler/fileat.c
src/main/host/syscall/handler/futex.c
src/main/host/syscall/handler/ioctl.c
src/main/host/syscall/handler/mod.rs
src/main/host/syscall/handler/poll.c
src/main/host/syscall/handler/select.c
src/main/host/syscall/handler/signal.c
src/main/host/syscall/handler/uio.c
src/main/host/syscall/handler/unistd.c
src/main/host/syscall/handler/wait.rs
src/main/host/syscall/protected.h
src/main/host/syscall/types.rs
src/main/host/thread.rs
src/main/utility/syscall.rs

We had decided a long time ago to standardize on the prefix "Syscall" rather than "SysCall", so this just renames some types.

Rename "SysCall" to "Syscall"

---

src/main/host/syscall/handler/file.rs
src/test/file/test_file.c

`lseek()` on a pipe should return `ESPIPE`. I just added a C test in the existing `file.c` since it was simplest and keeps the `lseek` tests in one place.

Support lseek syscall on pipes

---

src/lib/linux-api/src/time.rs
src/main/host/syscall/handler/mod.rs
src/main/host/syscall/handler/time.rs
src/test/time/itimer/test_itimer.rs

Possibly needed by python's subprocess module and/or tor's bandwidth scanner. See #3306

Implement alarm syscall

---

src/main/host/syscall/handler/time.rs
src/main/host/timer.rs
src/test/time/itimer/test_itimer.rs

* If `alarm` has already fired, calling it again should return 0
* If `alarm` is called at exactly the time when the timer was going to fire, but before it has fired, we should return 1 instead of 0.

alarm syscall: return 1 instead of 0 if timer was scheduled to fire now

---

.github/workflows/run_tests.yml
ci/container_scripts/install_deps.sh
ci/run.sh
docs/ci.md
docs/supported_platforms.md

Fedora 38 becomes EOL in two weeks (14 May 2024). We already dropped CI testing for this version.
Ubuntu 24.04 and Fedora 40 were just released. I also tested Shadow in an Ubuntu 24.04 VM and the standard tests passed, so the updated kernel (6.8.0-31-generic) should be fine.
The required CI tests will need to be updated before merging.

Add support for Ubuntu 24.04 and Fedora 40, and drop Fedora 38

---

.github/workflows/ci_maintenance.yml

v6 uses Node 16 and is deprecated.
v7 uses Node 20.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
Also fixed a syntax error causing the workflow to fail.

Upgrade actions/github-script to v7

---

CHANGELOG.md

Mostly by looking through the output of
`git log -p --first-parent --reverse v3.1.0..origin/main`

Update CHANGELOG with changes since 3.1.0.

---

src/main/host/syscall/handler/mod.rs

Fixes a bug introduced in 0412e0af74f59790515a2cc6b7653005a98a4a63.

syscall handler: fix inverted "warn once" logic

---

CHANGELOG.md
src/main/host/host.rs
src/main/host/managed_thread.rs
src/main/utility/childpid_watcher.rs

On failure, `posix_spawn` and related functions return the error code
directly instead of through errno. This fixes our handling of the return
codes to correctly detect and interpret errors from these functions.

Fix error-handling for posix_spawn

---

.bumpversion.cfg
src/Cargo.lock
src/Cargo.toml
src/lib/formatting-nostd/Cargo.toml
src/lib/gml-parser/Cargo.toml
src/lib/linux-api/Cargo.toml
src/lib/log-c2rust/Cargo.toml
src/lib/logger/Cargo.toml
src/lib/pod/Cargo.toml
src/lib/scheduler/Cargo.toml
src/lib/shadow-build-common/Cargo.toml
src/lib/shadow-build-info/Cargo.toml
src/lib/shadow-shim-helper-rs/Cargo.toml
src/lib/shim/Cargo.toml
src/lib/shmem/Cargo.toml
src/lib/std-util/Cargo.toml
src/lib/syscall-logger/Cargo.toml
src/lib/tcp/Cargo.toml
src/lib/tsc/Cargo.toml
src/lib/vasi-macro/Cargo.toml
src/lib/vasi-sync/Cargo.toml
src/lib/vasi/Cargo.toml
src/main/Cargo.toml
src/test/Cargo.toml

This means we only need to update the edition and publish options in a single place (the workspace Cargo.toml file). It's a little unfortunate that we need to specify `foo.workspace = true` in all crates, but it's not too bad.
Documentation for this feature: https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table
Previously most of our libraries were version 0.1.0, and now they are changed to 0.0.0 to indicate that we don't actually update their version numbers. This shouldn't have any user-facing changes.

Set Cargo edition/publish in workspace, and change non-main crates to 0.0.0

---

src/main/host/syscall/handler/mod.rs
src/main/utility/macros.rs
src/main/utility/mod.rs
src/main/utility/once_set.rs

This pulls the `OnceSet` commit out of #3332. It moves the locking correctness logic to its own type. This also adds changes for the following review comments from #3332:
- https://github.com/shadow/shadow/pull/3332#discussion_r1604012045
> Nit: Maybe append
>
> ```rust
> assert!(!set.insert("BAR".to_string()));
> ```
>
> to make sure inserting still works after attempting to insert a duplicate?
- https://github.com/shadow/shadow/pull/3332#discussion_r1604020948
> I think this is still replicating the `warn_once_then_debug` behavior though, right? If so, I would add that detail to the comment. And maybe a back reference to here from `warn_once_then_debug` so that if that function is ever changed we know to update this code too.

Add `OnceSet` for unhandled syscall warnings

---

CHANGELOG.md
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/descriptor/socket/inet/udp.rs

These lines can otherwise be fairly noisy in large simulations.

getsockopt/setsockopt: use log_once_per_value_at_level for unknown opts

---

src/lib/vasi-sync/Cargo.toml

This is in preparation for the upcoming changes in rust 1.80:
https://blog.rust-lang.org/2024/05/06/check-cfg.html
Rust 1.80 will likely be released before we publish another Shadow release (end of July), so I don't think it hurts to merge now.
Fixes around 40 warnings of the form:
```
warning: unexpected `cfg` condition name: `loom`
--> lib/vasi-sync/src/sync.rs:163:15
|
163 |     #[cfg(not(loom))]
|               ^^^^
|
= help: consider using a Cargo feature instead
= help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }
= help: or consider adding `println!("cargo::rustc-check-cfg=cfg(loom)");` to the top of the `build.rs`
= note: see …
```

Add exception for loom cfg in rust 1.80-beta

---

src/lib/shim/src/clone.rs
src/lib/shim/src/tls.rs
src/lib/vasi-sync/src/scchannel.rs
src/main/host/memory_manager/mod.rs

Example:
```
warning: doc list item missing indentation
--> lib/vasi-sync/src/scchannel.rs:144:5
|
144 | /// single-consumer channel.
|     ^
|
= help: if this is supposed to be its own paragraph, add a blank line
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_lazy_continuation
= note: `#[warn(clippy::doc_lazy_continuation)]` on by default
help: indent this line
|
144 | ///   single-consumer channel.
|     ++
```
(Aside:)
If anyone finds them useful, these are the vim settings I use for formatting rust comments, and they seem to work fairly well. Figured I'd might as well post them here:
```vim
" fix gq formatting: https://stackoverflow.com/a/28078855
autocmd Filetype rust set comments^=:///
autocmd Filetype rust set comments^=://!
" …
```

Fix clippy warnings in rust 1.80-beta

---

src/main/core/work/event_queue.rs

In https://github.com/shadow/shadow/pull/3367#issuecomment-2230884488, shadow panics because an event is scheduled to occur at a time earlier than a previously run event, meaning that time moves backwards. I'm not actively debugging the linked issue, but I think it would good to have an assertion here anyways to catch this sort of thing earlier.
This PR checks that a pushed event does not occur before a previously popped event. We already had an equivalent check when popping an event (which is the panic in the linked issue), but by also checking when pushing an event, we should hopefully catch it sooner and get a more useful backtrace.

Add an assertion when an event is pushed

---

setup

This PR simplifies some things, and uses lists instead of space-separated strings for commands. This should hopefully make the script more robust against arguments and paths with spaces. I have not looked at the CMake code yet to see if that handles commands properly.

Improve setup script

---

src/main/host/descriptor/epoll/mod.rs
src/main/host/syscall/handler/clone.rs
src/main/host/syscall/handler/close_range.rs
src/main/host/syscall/handler/epoll.rs
src/main/host/syscall/handler/eventfd.rs
src/main/host/syscall/handler/futex.rs
src/main/host/syscall/handler/ioctl.rs
src/main/host/syscall/handler/mman.rs
src/main/host/syscall/handler/mod.rs
src/main/host/syscall/handler/random.rs
src/main/host/syscall/handler/sched.rs
src/main/host/syscall/handler/shadow.rs
src/main/host/syscall/handler/signal.rs
src/main/host/syscall/handler/socket.rs

This extends the syscall handler trait to support functions that return `Into<SyscallError>`, and changes some syscall handlers to return `Errno` instead of `SyscallError` when it simplifies the code.

Return `Errno` from some syscall handlers

---

src/Cargo.lock
src/lib/formatting-nostd/Cargo.toml
src/lib/linux-api/Cargo.toml
src/lib/log-c2rust/Cargo.toml
src/lib/logger/Cargo.toml
src/lib/pod/Cargo.toml
src/lib/scheduler/Cargo.toml
src/lib/shadow-build-common/Cargo.toml
src/lib/shadow-build-info/Cargo.toml
src/lib/shadow-shim-helper-rs/Cargo.toml
src/lib/shim/Cargo.toml
src/lib/tcp/Cargo.toml
src/lib/tsc/Cargo.toml
src/lib/vasi-macro/Cargo.toml
src/lib/vasi-sync/Cargo.toml
src/main/Cargo.toml
src/test/Cargo.toml

Held out nix from the version update to prevent API incompatibility.
Closes #3341

Update Shadow's rust dependencies

---

src/lib/preload-libc/gen_syscall_wrappers_c.py
src/main/host/syscall/handler/fileat.c
src/main/host/syscall/handler/fileat.h
src/main/host/syscall/handler/fileat.rs
src/main/host/syscall/handler/mod.rs

The 'fchmodat' syscall doesn't have a flags argument, and there was recently a 'fchmodat2' syscall that does.
The PR only needs a review for the last two commits. the others are from other dependent open PRs.

Add the fchmodat2 syscall handler and fix fchmodat

---

ci/rust-toolchain-nightly.toml
ci/rust-toolchain-stable.toml

https://blog.rust-lang.org/2024/08/08/Rust-1.80.1.html
> Rust 1.80.1 fixes two regressions that were recently reported.
Neither probably affects us, but probably a good idea to update.

Upgrade rust version in CI to 1.80.1

---

src/main/host/syscall/handler/unistd.rs
src/main/host/thread.rs

This is likely causing #3390. We should have been calling `with_global_cb_queue` in `Thread::update_for_exec` to initialize the global thread-local callback queue so that callbacks made from C won't occur while we already have the rust socket borrowed. I also added `with_global_cb_queue` in a few other places where it was missing.

Add missing `with_global_cb_queue` wrappers

---

CHANGELOG.md
src/lib/shim/src/signals.rs
src/test/golang/CMakeLists.txt
src/test/golang/sigterm.yaml
src/test/golang/test_sigterm.go

This *can* be safe in some circumstances, and golang appears to do it in its default SIGTERM handler.
Fixes https://github.com/shadow/shadow/issues/3395

Allow signal handlers to switch to in-use stack

---

CHANGELOG.md
src/Cargo.lock
src/main/host/managed_thread.rs
src/main/utility/mod.rs
src/test/Cargo.toml
src/test/clone/CMakeLists.txt
src/test/clone/test_fork.rs

We can handle scripts using the "shebang line" mechanism, provided that the specified interpreter is a dynamically linked ELF (or another script whose interpreter is a dynamically linked ELF, etc).
Fixes #3400

verify_plugin_path: support scripts

---

src/main/core/worker.rs
src/test/regression/3148/CMakeLists.txt
src/test/regression/3148/regression-3148.yaml
src/test/regression/CMakeLists.txt

Closes #3148. Also added a regression test.
This was really easy to add now that we have `log_once_per_value_at_level!()`.
```
[WARN] [testnode:11.0.0.1] [worker.rs:354] [shadow_rs::core::worker] (LOG_ONCE) Packet has destination 13.62.123.22 which doesn't exist in the simulation. Dropping the packet.
```

Drop packet instead of panicking if dst IP is unknown

---

CHANGELOG.md
src/main/routing/dns.c

The comment that was here indicated intent to allow restricted IP addresses as long as they were unique (or local), but the code rejected them.
I *think* we want to reject any non-unique + non-local IP address assignment, and don't otherwise care if it's in a restricted range.

DNS: Allow assignment of restricted IPs

---

src/lib/gml-parser/src/parser.rs
src/main/utility/macros.rs
src/test/signal/test_signals.rs

Fixes `elided_named_lifetimes`, `static_mut_refs`, and `non_local_definitions` warnings.
[Apparently](https://github.com/rust-lang/rust/issues/120363) they are considering making non-local `impl` definitions a hard error in the future (so we won't be able to `allow(non_local_definitions)` anymore), which would be unfortunate since we wouldn't be able to have our syscall logger macros at the beginning of the syscall handler functions anymore. But this wouldn't take effect until 2028, so I'm happy to ignore this.
For `static_mut_refs` we can make it a little nicer using raw references when they release in rust 1.82 in ~10 days.

Fix nightly warnings

---

CHANGELOG.md
docs/shadow_config_spec.md
src/main/core/configuration.rs
src/main/core/logger/shadow_logger.rs
src/main/shadow.rs
src/test/CMakeLists.txt
src/test/cli/help-long-expected

Trying to detect whether stdout and stderr are terminals and deduplicating based on that can be tricky, e.g. in CI environments..
Instead:
* Make the `stderr` version more of a human-consumable message instead of the raw log line, which also makes the duplication easier to understand in the case where stdout and stderr are merged.
* Disable this feature in our cmake tests, where stdout and and stderr are merged.
New output on a process failure in the unmerged case (where stdout is written to a file and stderr is the terminal):
** Starting Shadow 3.2.0
Error: process 'testnode.test_sleep.1000' exited with status Normal(101); expected end state was exited: 0 but was exited: 101
Error: Failed to run the simulation
Error:
Error: Caused by:
Error:     1 managed processes in unexpected final …

Replace `--log-errors-to-tty` with `--report-errors-to-stderr`

---

CHANGELOG.md
ci/rust-toolchain-nightly.toml
ci/rust-toolchain-stable.toml
src/main/build.rs

Fix link error with rust 1.82 (#3445), and bump our toolchain version to 1.82.

Bump rust to 1.82 and fix link error

---

.github/workflows/run_tests.yml
CHANGELOG.md
ci/container_scripts/install_deps.sh

It's passed EOL: https://wiki.debian.org/LTS. Its python3 package is also pretty old (3.7), which would have required substantial changes to #3449 to support.

Remove support for debian:10

---

shadowtools/pyproject.toml

When tools like mypy analyze *other* code that *imports* shadowtools, this tells the tool that shadowtools has inline type annotations. Otherwise it treats the package as untyped.

shadowtools: add PEP 561 type annotation marker

---

.github/workflows/lint.yml
.github/workflows/sanitizers.yml

This leaves some workflows as 'ubuntu-latest', for example very simple workflows and workflows that run in containers.
This is needed due to the github change of 'ubuntu-latest' from 'ubuntu-22.04' to 'ubuntu-24.04', which breaks the CI.

Change some workflows from 'ubuntu-latest' to 'ubuntu-22.04'

---

shadowtools/CMakeLists.txt

Most people won't have the python dependencies installed (they're not shadow's dependencies), so this shouldn't run by default.

Make 'shadowtools-tests' an "extra" test

---

.github/workflows/lint.yml
.github/workflows/sanitizers.yml

* Install libglib in workflows that run our rust build scripts
* Bump our pinned action images from ubuntu 22.04 to 24.04
Fixes #3459

Bump pinned action images to ubuntu 24.04

---

src/main/core/manager.rs
src/main/core/worker.rs
src/main/host/descriptor/regular_file.c
src/main/host/host.rs
src/main/host/network/namespace.rs
src/main/routing/dns.c
src/main/routing/dns.h

Limit accesses to C DNS in preparation for removing the C Address and DNS code.
Follow-up to #3455 ; this should be rebased and merged AFTER #3455 is merged.

Limit dns scope

---

.github/workflows/lint.yml
docs/coding_style.md
src/lib/shadow-shim-helper-rs/src/simulation_time.rs
src/lib/shmem/src/allocator.rs
src/lib/tcp/src/lib.rs
src/lib/tcp/src/tests/mod.rs
src/lib/tcp/src/tests/send_recv.rs
src/lib/tcp/src/tests/window_scale.rs
src/lib/vasi-sync/tests/sync/mod.rs
src/main/utility/shm_cleanup.rs

Closes #3468.
This is branched from #3469, ~so the first 4 commits should be ignored.~

Fix clippy warnings in unit tests and add '--all-targets' to clippy CI

---

CHANGELOG.md
src/main/host/syscall/formatter.rs
src/main/host/syscall/handler/fcntl.rs
src/main/host/syscall/handler/futex.rs
src/main/host/syscall/handler/ioctl.rs
src/main/host/syscall/type_formatting.rs

This makes the determinism tests pass again on my computer.
Example:
```text
00:00:01.000000000 [tid 1000] futex(<pointer>, 265, 1001, <pointer>, <pointer>, <non-deterministic>) = 0
```
Closes #3460.

Add `SyscallNonDeterministicArg` strace logger wrapper

---

src/main/shadow.rs

Before:
```text
00:00:00.194137 [70289:shadow] n/a [WARN] [n/a] [shadow.rs:180] [shadow_rs::shadow] Could not disable address space layout randomization. This may affect determinism: ENOSYS: Function not implemented
Stack backtrace:
0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.89/src/backtrace.rs:27:14
1: shadow_rs::shadow::run_shadow
at /shadow/src/main/shadow.rs:178:11
2: main_runShadow
at /shadow/src/main/shadow.rs:473:22
3: main
at /shadow/src/main/main.c:17:12
4: __libc_start_call_main
5: __libc_start_main@@GLIBC_2.34
6: _start
```
After:
```text
00:00:00.000205 [113136:shadow] n/a [WARN] [n/a] [shadow.rs:180] [shadow_rs::shadow] Could not disable address space layout …
```

Remove backtrace from logs when disabling ASLR fails

---

CHANGELOG.md
src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/socket/inet/tcp.rs
src/main/host/descriptor/socket/inet/udp.rs
src/test/socket/sockopt/test_sockopt.rs

Previously, we had stubs for setsockopt with `SO_BROADCAST` for tcp and udp:
```rust
(libc::SOL_SOCKET, libc::SO_BROADCAST) => {
// TODO: implement this, pkg.go.dev/net uses it
log::trace!("setsockopt SO_BROADCAST not yet implemented");
}
```
The old behaviour for tcp/udp was:
- getsockopt:
- return ENOPROTOOPT
- setsockopt:
- show trace (for tcp) or "warn_once_then_debug" (for udp) log and return 0
The new behaviour for tcp/udp is:
- getsockopt:
- always returns 0 since we don't support broadcast sockets
- setsockopt:
- if value is 0, do nothing and return 0
- if value is not 0, show "warn_once_then_debug" log and return 0
Our tests aren't set up to test get/setsockopt for unix sockets, so I didn't implement the option for unix sockets. I would expect it to return an error.
Closes #3439.

Improve `SO_BROADCAST` stubs

---

docs/shadow_config_spec.md

Closes #3427.
Documents the behaviour as of #3474.
I don't want to go into too much detail since it would be bad if users write their simulations in a way that relies on this behaviour, but changing the behaviour would be a breaking change anyways so I think it's okay to specify some of the details (like the starting address 11.0.0.1).

Document automatic IP address assignment

---

src/lib/shmem/src/shmalloc_impl.rs

This adds a `dead_code` exception in release builds, which wasn't caught since we only do debug builds in the CI.

Fix `dead_code` warning in `canary_check` in release builds

---

.github/workflows/extra_tests.yml

Tor 0.4.8.13 fixes some conflux issues.
- https://forum.torproject.org/t/new-tor-stable-release-0-4-8-13/15397
- https://gitlab.torproject.org/tpo/core/tor/-/raw/release-0.4.8/ReleaseNotes

Bummp Tor version in the CI extra test

---

src/main/host/network/network_queuing_disciplines.c
src/main/host/network/network_queuing_disciplines.h

Our fifo qdisc violates the assumption that a queued item's priority does not change while the item is enqueued. This allows a socket that had only bad priority packets when it was initially pushed into the queue to move up in priority when it suddenly has new packets with better priority. This case can happen often in the legacy TCP stack because it assigns priority=0 to control packets (ACKS) without data. This means we can be more responsive to TCP controls.
This PR does two things:
1. Fixes the fifo qdisc so that it always produces a non-equal sort order over sockets. This is done by tracking the push order of the sockets and using the push order to break equality ties.
2. Tracks the socket priority that existed at push time to enable us to show the performance difference when sorting …

Fix fifo qdisc

---

CHANGELOG.md
src/test/clone/test_fork.rs

This is a new warning in rust 1.84.
There are two warnings of the form:
```text
warning: a dangling pointer will be produced because the temporary `Vec<*const i8>` will be dropped
--> test/clone/test_fork.rs:1825:55
|
1825 |                         in("rsi") execv_argvec(&args).as_ptr(),
|                                   ------------------- ^^^^^^ this pointer will immediately be invalid
|                                   |
|                                   this `Vec<*const i8>` is deallocated at the end of the statement, bind it to a variable to extend its lifetime
|
= note: pointers do not have a lifetime; when calling `as_ptr` the `Vec<*const i8>` will be deallocated at the end of the statement because nothing is referencing it as far as the type system is concerned
= help: for …
```

Fix 'dangling_pointers_from_temporaries' warning in test

---

src/main/host/syscall/handler/futex.c
src/test/futex/test_futex.c

In the current futex syscall handler:
https://github.com/shadow/shadow/blob/85d08b739741479f00100a4e5650136dc1c0acf9/src/main/host/syscall/handler/futex.c#L118-L124
When the `futex_op` is `FUTEX_WAIT_BITSET`, the timeout argument points to a `timespec` structure specifying the absolute timeout. If the provided timestamp is earlier than the current emulated time, the worker panics during event scheduling:
https://github.com/shadow/shadow/blob/85d08b739741479f00100a4e5650136dc1c0acf9/src/main/host/timer.rs#L191-L199
To fix this, I simply set `timeoutEmulatedTime` to the current emulated time in that case. I also added a unit test for this fix.

Fix the expired timeout issue in the futex syscall handler

---

docs/supported_platforms.md

Remove Debian 10 from supported platforms

---

src/main/network/router/codel_queue.rs

I have no idea why this started failing in the CI when it previously passed.

Fix 'clippy::unnecessary_map_or' warning

---

src/test/epoll/CMakeLists.txt
src/test/udp/udp.yaml

I was experimenting with enabling `--model-unblocked-syscall-latency` by default in the shadow binary or in our test macro. There's a bit more to do before considering actually doing that, but these fix some test failures we would otherwise get.

Make tests compatible with --model-unblocked-syscall-latency

---

src/main/host/host.rs
src/main/host/process.rs
src/main/host/syscall/handler/mod.rs
src/main/utility/perf_timer.rs

When creating a forked process, initialize with a stopped performance timer instead of a started one.
Fixes #3232

Fix forked timers

---

src/Cargo.lock
src/lib/linux-api/Cargo.toml
src/lib/linux-api/gen-kernel-bindings.sh
src/lib/linux-api/src/bindings.rs
src/lib/linux-api/src/signal.rs
src/lib/linux-api/src/time.rs
src/lib/shadow-shim-helper-rs/src/simulation_time.rs
src/main/host/syscall/handler/time.rs
src/main/host/syscall/type_formatting.rs

Generally useful, and to be potentially used for https://github.com/shadow/shadow/issues/2066

linux-api: add wrappers for getitimer and setitimer

---

ci/container_scripts/install_extra_deps.sh

I expect this to fix the failures in our CI and benchmarks.
```text
This is usually done by running one of the following (note the leading DOT):
. "$HOME/.cargo/env"            # For sh/bash/zsh/ash/dash/pdksh
source "$HOME/.cargo/env.fish"  # For fish
source "$HOME/.cargo/env.nu"    # For nushell
info: default host triple is x86_64-unknown-linux-gnu
info: skipping toolchain installation
error: toolchain '1.85-x86_64-unknown-linux-gnu' is not installed
help: run `rustup toolchain install 1.85-x86_64-unknown-linux-gnu` to install it
```
https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html
> The following improvements might require changes to how you use rustup:
> - rustup will no longer automatically install the active toolchain if it is not installed.

Fix CI failures due to rustup 1.28.0 changes

---

CHANGELOG.md
docs/limitations.md
docs/shadow_config_spec.md
src/lib/linux-api/src/time.rs
src/lib/shadow-shim-helper-rs/src/shim_shmem.rs
src/lib/shim/shim.c
src/lib/shim/src/lib.rs
src/lib/shim/src/preempt.rs
src/lib/shim/src/syscall.rs
src/main/core/configuration.rs
src/main/core/manager.rs
src/main/host/syscall/handler/mod.rs
src/test/Cargo.toml
src/test/cli/help-long-expected
src/test/regression/CMakeLists.txt
src/test/regression/cpu_busy_wait.yaml
src/test/regression/test_busy_wait.rs
src/test/regression/test_cpu_busy_wait.rs

This new feature is off by default, and enabled via the new experimental `--native-preemption-enabled` option.
When enabled, the shim code uses a native timer to interrupt managed code that runs for longer than `--native-preemption-native-interval` (100 ms by default) without returning control to shadow, and moves simulated time forward by `--native-preemption-sim-interval` (10 ms by default).
It is intended to be used to escape CPU-only busy loops.
Fixes #2066

Add preemption to escape pure-cpu busy-loops

---

CHANGELOG.md
src/main/host/descriptor/socket/inet/udp.rs
src/test/socket/getsockname/test_getsockname.rs

Previously a UDP socket that called `sendto()` would be implicitly bound to an address on the same interface. So sending to 127.0.0.1 would cause the socket to be bound to 127.0.0.1. Sending to 1.2.3.4 would cause the socket to be bound to the public IP address of the host.
This PR fixes the behaviour so that regardless of the address used with `sendto()`, the socket will always be bound to 0.0.0.0.
This, along with #3531, should fix #3526.

Fix a bug with UDP implicit bind after `sendto()`

---

src/test/socket/ioctl/test_ioctl.rs
src/test/test_utils.rs

Just outputs some extra info if the test fails.
Related: #3546

Add better error logging to `test_siocgstamp` socket test

---

src/lib/shim/src/reinit_auxvec_random.rs

`AT_MINSIGSTKSZ` is not available for amd64 until Linux 5.14 ([source](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1c33bb0507508af24fd754dd7123bd8e997fab2f)), so this test will fail on earlier kernel versions.
https://github.com/shadow/shadow/blob/c7976835f8cb183de76ede64155d0a3b4009eb68/src/lib/shim/src/reinit_auxvec_random.rs#L99-L104
```
test tls::test::test_multithread_mutate_mixed_alignments ... ok
test tls::test::test_multithread_mutate_small_alignment ... ok
failures:
---- reinit_auxvec_random::test::test_getauxvec stdout ----
thread 'reinit_auxvec_random::test::test_getauxvec' panicked at lib/shim/src/reinit_auxvec_random.rs:101:57:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a …
```

Fix the test for getauxval when the type is not found

---

src/Cargo.lock
src/test/socket/socket/test_socket.rs

This updates the dependencies in our `Cargo.lock` file, but not the `Cargo.toml`. The main reason for this MR is to pull in the crossbeam fix for a double free, which resolves [GHSA-pg9f-39pc-qf8g](https://github.com/advisories/GHSA-pg9f-39pc-qf8g).
**Edit:** This also removes our tests that use `SOCK_PACKET` since it's deprecated in the libc crate. I'm not sure if this indicates that they plan to remove it or not. But I don't think it's a big deal to stop testing this socket type. Otherwise we'd need to hardcode the value, or switch to linux-api instead.

Run 'cargo update'

---

CHANGELOG.md
src/main/host/descriptor/tcp.c
src/test/regression/3100/CMakeLists.txt
src/test/regression/3100/regression-3100.yaml
src/test/regression/CMakeLists.txt

Shadow assigns a priority to packets, and packets with a lower priority will be sent before other packets. Previously, shadow only assigned a priority to non-empty packets (here meaning containing a payload), and a priority of 0 to other packets. But this meant that empty packets like FIN (with a priority of 0) could be sent before other packets, even if the FIN had a higher sequence number. Shadow seems to have discarded these out-of-order FIN packets. See #3100 for an example.
This MR changes the legacy TCP code to always assign a non-zero priority if the packets has a sequence number, so that they won't be sent out of order. This (**edit:** partially; see https://github.com/shadow/shadow/issues/3100#issuecomment-2823009618) fixes (**edit:** \<text to prevent github from closing the …

Fix packet order of FIN from `SHUT_WR`

---

CHANGELOG.md
src/main/host/descriptor/epoll/entry.rs
src/main/host/descriptor/mod.rs
src/main/host/descriptor/tcp.c
src/test/epoll/epoll-rs.yaml
src/test/epoll/test_epoll.rs

While debugging
https://gitlab.torproject.org/tpo/core/arti/-/issues/1972, it became apparent that the tokio runtime seems to rely on EPOLLRDHUP to know when a socket is closed, at least in some circumstances.
This adds tests for this and several variations of EOF behavior.
A second commit adds EPOLLRDHUP support for TCP sockets and enables running the corresponding tests under shadow.

test EOF behavior and fix missing EPOLLRDHUP events for TCP sockets

---

src/main/host/syscall/handler/fileat.c
src/main/host/syscall/handler/fileat.h
src/main/host/syscall/handler/fileat.rs
src/main/host/syscall/handler/mod.rs
src/test/file/CMakeLists.txt
src/test/file/test_file.c

Our `faccessat` handler incorrectly took an extra flags parameter, which was garbage data. This led to a heisenbug in chutney shell scripts, since sometimes the corresponding register would happen to have 0 and work, but sometimes it would have garbage data and cause the syscall to return an error.
This renames the old handler to `faccessat2`, which *does* take the flags parameter, and adds `faccessat`, which doesn't.

Fix faccessat and add faccessat2

---

src/main/host/descriptor/mod.rs
src/main/host/syscall/handler/uio.rs

Based on the discussion in #2181. I think the `debug_assert!` might be helpful in the future to make sure we don't try to block a syscall by waiting for the file to enter a state that it's already in.

Small documentation and `debug_assert` related to `FileState`

---

src/Cargo.lock
src/main/Cargo.toml
src/main/core/configuration.rs

It appears that the merge crate doesn't provide an impl for `Option` anymore, so we need to specify the merge strategy manually. Since all of the struct fields are `Option`, we can thankfully just put the `#[merge(...)]` at the top of each struct rather than on each field.
Supersedes #3561.
Part of #3555.

Upgrade 'merge' to 0.2

---

src/CMakeLists.txt
src/lib/shadow-shim-helper-rs/src/rootedcell/rc.rs

The `setup` script has a `--werror` option to turn warnings into errors for C code. This is useful in the CI to avoid merging changes that have warnings. But this doesn't enable the equivalent option for rust code.
In the clippy CI lint test, we use `cargo clippy --all-targets -- -Dwarnings` to convert clippy and rust warnings into errors. But this only affects debug mode builds. Warnings in release builds will not be caught by this.
I think it's best that the `--werror` setup script option also enables `-Dwarnings` for rust code during the regular build. Then warnings will be caught in the CI, which uses `--werror` in `ci/container_scripts/build_and_install.sh`. This PR makes that change, and also fixes a rust warning in release builds.
Closes #3571.

Change `--werror` to also convert rust warnings to errors

---

CHANGELOG.md
ci/rust-toolchain-nightly.toml
ci/rust-toolchain-stable.toml
src/lib/shmem/src/raw_syscall.rs
src/main/core/sim_stats.rs
src/main/host/descriptor/descriptor_table.rs
src/main/host/process.rs
src/test/random/test_random.rs
src/test/socket/socket/test_socket.rs

Fixes clippy warnings in rust 1.87, and upgrades the rust version in CI.
When running clippy with rust 1.88-beta, we get "'shadow-rs' (lib test) generated 152 warnings", so we have that to look forward to in 6 weeks :)

Fix warnings for rust 1.87 and upgrade CI rust version

---

CHANGELOG.md
setup

Closes #3586.
```text
$ ./setup build
[...]
-- SHADOW_TEST=OFF
-- SHADOW_WERROR=OFF
-- SHADOW_EXTRA_TESTS=OFF
-- SHADOW_USE_PERF_TIMERS=OFF
$ ./setup build --test --werror
[...]
-- SHADOW_TEST=ON
-- SHADOW_WERROR=ON
-- SHADOW_EXTRA_TESTS=OFF
-- SHADOW_USE_PERF_TIMERS=OFF
$ ./setup build
[...]
-- SHADOW_TEST=OFF
-- SHADOW_WERROR=OFF
-- SHADOW_EXTRA_TESTS=OFF
-- SHADOW_USE_PERF_TIMERS=OFF
```

Update 'setup' script to pass "OFF" to cmake

---

.github/workflows/run_tests.yml
CHANGELOG.md
ci/container_scripts/build_and_install.sh
ci/container_scripts/install_extra_deps.sh
docs/supported_platforms.md
shadowtools/pyproject.toml

The CI workflow says Ubuntu 20.04 EOL is April 2025, so just queuing up an MR so that we can drop support in April.
We also had some code for installing 'clang-12' in the container scripts. I don't think we need this anymore, so I also dropped that code.

Drop support for Ubuntu 20.04

---

src/Cargo.lock
src/main/Cargo.toml
src/main/core/configuration.rs
src/main/utility/units.rs

Closes shadow#3625.
There have been some changes to schemars here. The "cli" tests make sure that there are no changes to the final cli help rendering.
One slightly painful change is that schemars has changed how they format the description for a field. So if a field is:
```rust
/// Hello
/// world.
foo: String,
```
It will now have a description of "Hello\nworld." instead of "Hello world" like in the previous schemars version. This causes clap to also format it as two lines. So we need to perform some rudimentary formatting to replace the new lines with spaces. This isn't ideal, but is close to what schemars was doing originally. If we find that this is too limiting, we can add some markdown parser into shadow in the future.
For my own reference, this is where clap-derive does it's …

Upgrade schemars to 1.0.4

---

src/main/host/memory_manager/memory_mapper.rs
src/main/host/memory_manager/mod.rs

This clippy error was added in rust 1.88. In shadow#3632 I added an `#[allow(...)]`, but I think it would be better using a `&mut self` for now.
See https://github.com/shadow/shadow/pull/3632#issuecomment-3111528848 for context.
```text
error: mutable borrow from immutable input(s)
--> main/host/memory_manager/memory_mapper.rs:1079:77
|
1079 |     pub unsafe fn get_mut<T: Pod>(&self, src: ForeignArrayPtr<T>) -> Option<&mut [T]> {
|                                                                             ^^^^^^^^
|
note: immutable borrow here
--> main/host/memory_manager/memory_mapper.rs:1079:35
|
1079 |     pub unsafe fn get_mut<T: Pod>(&self, src: ForeignArrayPtr<T>) -> Option<&mut [T]> {
|                                   ^^^^^
= help: for further information visit …
```

Change `MemoryMapper::get_mut` to take a `&mut self`

---

src/main/host/descriptor/socket/inet/legacy_tcp.rs
src/main/host/descriptor/tcp.c
src/main/utility/utility.h
src/test/socket/accept/test_accept.rs
src/test/socket/bind/test_bind.rs

Once a child socket has been `accept`ed (associated with a file descriptor and moved off of the listening socket's queue), we now remove the parent-child relationship and associate the local:remote address pair directly with the corresponding network interface, instead of continuing to route packets to the listening socket and having the listening socket route them to the child.
This allows a listening socket to be unbound and cleaned up when it's closed instead of keeping it around to route packets to the child sockets, which allows us to reuse the address it had been bound to.
Fixes #3563.
I noticed and filed #3644 while working on this but verified that it was present before this PR as well.

TCP: Un-parent child sockets once they've been accepted

---

CHANGELOG.md
src/main/host/syscall/syscall_condition.c
src/test/regression/3650/CMakeLists.txt
src/test/regression/3650/regression-3650.yaml
src/test/regression/CMakeLists.txt
src/test/socket/bind/test_bind.rs

This fixes the example in #3650 and fixes #3564. It unrefs the `SysCallCondition` before we call `host_continue` in the wakeup task. This allows us to unref its `OpenFile`, otherwise the file cannot be closed until `host_continue()` finishes.
Let me know if there's a nicer way to do this, but I don't see one.
The explanation of what's happening is in https://github.com/shadow/shadow/issues/3650#issuecomment-3263556897. Lmk if that comment isn't very clear.

Unref the `SysCallCondition` before waking the thread
