- src/plugin/shadow-plugin-tgen/shd-tgen-action.c
- src/plugin/shadow-plugin-tgen/shd-tgen-action.h
- src/plugin/shadow-plugin-tgen/shd-tgen-driver.c
- src/plugin/shadow-plugin-tgen/shd-tgen-graph.c
Currently picks an outgoing edge at random.
> Added initial version of new feature: choose

- src/test/epoll/epoll.test.shadow.config.xml
- src/test/file/CMakeLists.txt
- src/test/file/file.test.shadow.config.xml
- src/test/file/shd-test-file.c
- src/test/poll/poll.test.shadow.config.xml
- src/test/pthreads/pthreads.test.shadow.config.xml
- src/test/sleep/sleep.test.shadow.config.xml
- src/test/tcp/tcp-blocking-loopback.test.shadow.config.xml
- src/test/tcp/tcp-blocking-lossless.test.shadow.config.xml
- src/test/tcp/tcp-blocking-lossy.test.shadow.config.xml
- src/test/tcp/tcp-nonblocking-epoll-loopback.test.shadow.config.xml
- src/test/tcp/tcp-nonblocking-epoll-lossless.test.shadow.config.xml
- src/test/tcp/tcp-nonblocking-epoll-lossy.test.shadow.config.xml
- src/test/tcp/tcp-nonblocking-poll-loopback.test.shadow.config.xml
- src/test/tcp/tcp-nonblocking-poll-lossless.test.shadow.config.xml
- src/test/tcp/tcp-nonblocking-poll-lossy.test.shadow.config.xml
- src/test/tcp/tcp-nonblocking-select-loopback.test.shadow.config.xml
- src/test/tcp/tcp-nonblocking-select-lossless.test.shadow.config.xml
- src/test/tcp/tcp-nonblocking-select-lossy.test.shadow.config.xml
- src/test/timerfd/timerfd.test.shadow.config.xml
also fix other test xml files with correct plugin file names
> add readv() and writev() tests

- src/test/epoll/CMakeLists.txt
- src/test/poll/CMakeLists.txt
- src/test/pthreads/CMakeLists.txt
- src/test/sleep/CMakeLists.txt
- src/test/tcp/CMakeLists.txt
- src/test/tcp/shd-test-tcp.c
- src/test/tcp/tcp-iov.test.shadow.config.xml
- src/test/timerfd/CMakeLists.txt
(not creating separate iov test dir)
> re: issue #317: add iov tests into tcp

- src/external/elf-loader/CMakeLists.txt
- src/external/elf-loader/extract-system-config.py
- src/external/elf-loader/libvdl.c
- src/external/elf-loader/test/output/test12.ref
- src/external/elf-loader/vdl-dl-public.c
- src/external/elf-loader/vdl-dl-public.h
- src/external/elf-loader/vdl-dl.c
- src/external/elf-loader/vdl-dl.h
- src/external/elf-loader/vdl-file.h
- src/external/elf-loader/vdl-map.c
Adds a few bug fixes and improvements to elf-loader for better Ubuntu 17.04 support.
Fixes #353
> elf-loader improvements for Ubuntu 17.04

- setup
- src/test/tcp/CMakeLists.txt
add a -j option for running tests in parallel, and set the default to 4 threads
> Parallel testing

- src/external/elf-loader/CMakeLists.txt
Fixes #378 
Turns out it was a gcc bug.
> compile elf-loader with -O3

- src/external/elf-loader/vdl-tls.c
I can't find any documentation that says this, but gcc on solus has started
generating code that assumes the thread pointer is 16 byte aligned, and will
segfault if it is not. This fixes that, and also switches setting some values
from memcpy to direct assignment.
> 16 byte align thread pointer

- src/external/elf-loader/glibc.c
- src/external/elf-loader/vdl-dl.c
- src/external/elf-loader/vdl-dl.h
- src/external/rpth/pth_attr.c
- src/external/rpth/rpth.h.in
- src/main/host/shd-process.c
- src/preload/shd-preload-defs.h
Along with #396, this gets a [simple client/server setup written in rust](https://github.com/dhuseby/shadow-rust-test) working.
Fixes #397
> Rust support

- src/external/elf-loader/vdl-tls.c
> fix off-by-one error in dtv updates

- src/external/elf-loader/vdl-tls.c
This definitely fixes at least one bug, but I was seeing some strange behavior that makes me think there's another.
> remove extra TLS unlock

- src/external/elf-loader/vdl-dl.c
- src/external/elf-loader/vdl-hashmap.c
- src/external/elf-loader/vdl-linkmap.c
- src/external/elf-loader/vdl-reloc.c
this solves the last of the weirdness I was seeing
> fix hashmap insertion in elf-loader

- src/tools/parse-shadow.py
This was causing the sum to be set to the last value in that second.
> fix accumulator initialization in parse-shadow.py

- .github/ISSUE_TEMPLATE/support-template.md
Add a template for support questions so users provide more information up front when reporting problems.
> Update issue templates

- src/external/elf-loader/extract-system-config.py
Added compatibility of the debug file prober for arch/manjaro
>  elf-loader: Added debug file search folder regex for arch/manjaro 

- .github/workflows/build_shadow.yml
- .github/workflows/lint_python.yml
- README.md
- setup
Adds a workflow to build and test shadow on every pull request or commit to master.
> Add Github workflow for continuous integration testing

- src/preload/shd-interposer.c
- src/preload/shd-preload-defs-special.h
- src/preload/shd-preload-defs.h
> Ensure functions declared noreturn will never return.

- src/external/elf-loader/CMakeLists.txt
Mitigates GH-715
Progress on GH-711
> Add -Wno-unneeded-internal-declaration for external/elf-loader/glibc.c

- src/preload/CMakeLists.txt
Issue https://github.com/shadow/shadow/issues/717
> Suppress -Wstatic-in-inline in shd-interposer.c

- .github/workflows/build_shadow.yml
- CMakeLists.txt
- setup
> Enable Werror in continuous integration workflow.

- src/test/pthreads/shd-test-pthreads.c
Allow to run the pthread test with one or more then 6 threads
> Fix pthread test bugs

- docs/2-Getting-Started-Tutorial.md
- resource/examples/shadow.config.xml
- resource/examples/tgen.client.graphml.xml
- resource/examples/tgen.server.graphml.xml
Make sure the example runs correctly with the latest version of TGen.
> Example fixup

- src/main/host/network_interface.c
- src/test/epoll/CMakeLists.txt
- src/test/epoll/test_epoll_writeable.c
Don't schedule events to refill token buckets that are already full.
Fixes GH-756
> Skip unneccesary token bucket refills

- src/test/udp/CMakeLists.txt
- src/test/udp/test_udp.c
- src/test/udp/test_udp_uniprocess.c
- src/test/udp/udp-uniprocess.test.shadow.config.xml
These should be helpful for taking smaller steps while getting this functionality working on the Phantom branch.
> Add more granular UDP tests

- docs/maintainer-playbook.md
Accidentally deleted instead of moving in
efd653a204d28499d02c92a478d0ad75299d17b6
Closes #772
> Reinstate release-tagging instructions

- CMakeLists.txt
- src/main/core/slave.c
- src/main/host/descriptor/tcp.c
- src/main/host/descriptor/tcp_retransmit_tally.h
- src/main/host/descriptor/timer.c
- src/main/host/host.c
- src/main/host/process.c
- src/main/host/process.h
- src/support/logger/logger.c
- src/test/test_glib_helpers.h
- src/test/udp/test_udp.c
- src/test/udp/test_udp_uniprocess.c
- src/test/unistd/test_unistd.c
> Backport Centos 7 fixes

- docs/README.md
- docs/nsf-sponsorship.md
Migrated from:
https://trac.torproject.org/projects/tor/wiki/org/sponsors/Sponsor38
> Add details about NSF sponsorship

- .github/workflows/build_shadow.yml
- src/main/host/syscall/uio.c
- src/main/host/syscall_handler.c
- src/test/test_glib_helpers.h
> Fix CI tests on Ubuntu 16.04 and Clang

- .github/workflows/build_shadow.yml
> Upload coverage to codecov, remove coverage artifact

- src/test/phold/phold.test.shadow.config.xml
- src/test/phold/test_phold.c
> Add cpu load generator in phold benchmark test

- src/test/Cargo.toml
- src/test/socket/CMakeLists.txt
- src/test/socket/bind/test_bind.rs
- src/test/socket/listen/CMakeLists.txt
- src/test/socket/listen/listen.shadow.config.xml
- src/test/socket/listen/test_listen.rs
- src/test/socket/socket/test_socket.rs
Closes #839.
There is some functionality that's duplicated with other tests, but I'm still waiting until I have a few more tests done to have a bigger picture about what functionality to move into a helper library.
> Added tests for the listen() call

- src/test/socket/bind/test_bind.rs
Previously, `Option` in `BindArguments` was overloaded twice, once for using `None` to represent a null pointer, and once for using `None` to represent an auto-configured length. It has now been changed to represent only a null pointer.
> Remove Option on address length in bind() tests

- src/main/host/syscall/socket.c
- src/test/Cargo.toml
- src/test/socket/CMakeLists.txt
- src/test/socket/getsockname/CMakeLists.txt
- src/test/socket/getsockname/getsockname.shadow.config.xml
- src/test/socket/getsockname/test_getsockname.rs
> Added tests for the getsockname() call

- src/main/utility/interval_map.rs
* Switch to half-open intervals
* Replace custom Interval type with Range<usize>
When I first wrote the IntervalMap I somehow had the mistaken idea that /proc/*/maps used closed intervals, so wrote IntervalMap to match. It turns out that it actually uses half-open intervals. Given that, and that half-open intervals are more idiomatic in Rust (including being representable by the built-in Range type), probably makes sense to switch it over, and to do so now before more code uses it.
> Intervalmap halfopen

- src/main/host/thread_ptrace.c
For reasons I haven't been able to completely nail down, when
single-stepping a syscall instruction, ptrace *sometimes* generates a
stop without actually advancing the instruction pointer.
I used to think it always did so exactly once, but it turns out it
definitely sometimes does so 0 times. We must have gotten away with this
happening before either because the rax happened to not be changed by
the instruction after the syscall, or we didn't care about the syscall
return value in the cases where it was happening.
I wish I understood better exactly what was happening here, but it's now
handled in a loop that should be fairly robust.
> threadptrace_nativeSyscall: handle variable number of ptrace stops

- src/shim/shim_logger.c
- src/support/logger/logger.c
- src/support/logger/logger.h
> Don't use heap in base and shim logger

- ci/run.sh
Note: Requires realpath from `brew install coreutils`.
> Fix CI scripts for Mac OS

- src/main/utility/byte_queue.rs
Looked over the code again and it seems okay, but if there are any bugs, they should be caught fairly quickly in debug mode.
> Fix clippy warnings in byte queue code

- src/test/Cargo.toml
- src/test/socket/accept/test_accept.rs
- src/test/socket/bind/test_bind.rs
- src/test/socket/getsockname/test_getsockname.rs
- src/test/socket/listen/test_listen.rs
- src/test/socket/socket/test_socket.rs
- src/test/test_utils.rs
Moved some common code from tests into a 'test_utils' crate. Also modified a few of the functions to make them more flexible.
> Moved some testing code into a new 'test_utils' crate.

- src/test/socket/getsockname/test_getsockname.rs
Checks that the address is `INADDR_ANY` after listening without first binding.
> Added missing getsockname test

- .github/workflows/lint_python.yml
Also makes the test run unconditionally since it's one of our required tests.
> Run only Python 3 lint test in the master branch

- docs/1.1-Shadow.md
Updates to Python 3 dependencies and fixes various other things.
Some of the changes are from #937 on the dev branch.
> Updated install docs in the master branch

- src/test/socket/accept/test_accept.rs
- src/test/socket/bind/test_bind.rs
- src/test/socket/connect/test_connect.rs
- src/test/socket/getsockname/test_getsockname.rs
- src/test/socket/listen/test_listen.rs
- src/test/test_utils.rs
An attempt to simplify and standardize the tests. The functionality should not have changed in this PR, only the way that the tests are structured.
> Restructured part of the socket API tests

- src/test/socket/accept/test_accept.rs
- src/test/socket/bind/test_bind.rs
- src/test/socket/connect/test_connect.rs
- src/test/socket/getpeername/test_getpeername.rs
- src/test/socket/getsockname/test_getsockname.rs
- src/test/socket/listen/test_listen.rs
- src/test/socket/shutdown/test_shutdown.rs
- src/test/socket/socketpair/test_socketpair.rs
- src/test/test_utils.rs
Based on the idea by @sporksmith in shadow/shadow#975.
> Added `set!` macro for tests

- src/test/epoll/CMakeLists.txt
> Specify interpose method for epoll tests

- .github/workflows/lint_python.yml
- src/external/elf-loader/test/junit_xml_output/__init__.py
Part of shadow/shadow#422 for the main branch.
As suggested by https://github.com/shadow/shadow/issues/422#issuecomment-621228607.
> Run Python 3 linter on 'src/external'

- .github/workflows/lint.yml
- .github/workflows/run_tests.yml
> Fix deprecated 'add-path' workflow command

- docs/1.1-Shadow.md
Have run into this problem several times, so worth documenting.
> Added warning about yum/dnf installing 32-bit libraries

- src/main/host/descriptor/epoll.c
On the way to getting tgen working correctly.
> fix epoll bug

- src/main/host/descriptor/mod.rs
- src/main/host/descriptor/pipe.rs
- src/main/host/syscall/mod.rs
- src/main/host/syscall/unistd.rs
This implements some Rust-equivalent types for some C types. There is still more to do in future PRs, but this is a start.
> Added some Rust wrappers around C types

- src/main/shmem/shmem_cleanup.c
- src/shim/shim.c
- src/support/logger/logger.c
> Avoid logging in the shim until we have a set a logger

- src/shim/CMakeLists.txt
- src/shim/preload_libraries.c
- src/shim/preload_syscall.c
- src/shim/preload_syscalls.c
This makes the code easier to read, less prone to type errors, and easier to extend.
> Simplify preloaded function list

- src/main/Cargo.lock
This replaces #1104, #1105, #1106, #1107, #1108.
> Updated Cargo lock file

- src/shim/preload_syscall.c
- src/test/tcp/CMakeLists.txt
- src/test/tcp/test_tcp.c
Fixes errno time of check bugs in the tcp test case. These will be an issue when we start preloading `gettimeofday`.
> Fix tcp test

- src/main/host/thread_ptrace.c
This gives the plugin a chance to run before checking whether it's
stopped again. This prevents deadlock in ptrace's "hybrid spin" when
using --pin-cpus and --sched-fifo together, and helps performance in
other cases.
> Add sched_yield calls in thread_ptrace

- CMakeLists.txt
- src/main/host/thread_ptrace.c
> Ptrace vfork

- src/main/bindings/rust/wrapper.rs
- src/main/host/descriptor/tcp.c
- src/main/host/descriptor/tcp.h
- src/main/host/futex.c
- src/main/host/syscall/clone.c
- src/main/host/syscall/epoll.c
- src/main/host/syscall/futex.c
- src/main/host/syscall/ioctl.c
- src/main/host/syscall/protected.h
> Miscellaneous bugfixes for running tor

- src/main/host/thread_ptrace.c
> thread_ptrace: Use __WNOTHREAD when calling waitpid

- src/test/tcp/test_tcp.c
After this, we can merge it into dev.
> Remove unnecessary string in tcp test

- src/main/host/thread_ptrace.c
This fixes a known bug where we sometimes get to thread_nativeSyscall without already having saved registers. Moving register-fetching to when we need them should help protect against such bugs in the future, and could save us work of fetching them in cases where we *don't* actually need them later.
> ptrace: get registers on-demand

- .github/workflows/run_tor.yml
This includes our placeholder workflow for Tor tests, which we will overwrite later.
> Merge main -> dev

- src/main/core/support/object_counter.c
I used the wrong bitwise operator.
> Fix bug in objectcounter_leakDetected()

- src/main/core/controller.c
- src/main/core/manager.c
- src/main/core/support/options.c
- src/test/CMakeLists.txt
- src/test/config/convert/CMakeLists.txt
> Remove the default value for '--data-template' and stop auto-deleting the data directory

- .github/workflows/lint.yml
- ci/container_scripts/install_extra_deps.sh
- src/main/bindings/rust/wrapper.rs
- src/main/host/descriptor/descriptor_types.h
- src/main/host/syscall/protected.h
- src/main/utility/utility.h
> Fix Rust bindings, and in CI check bindings in both debug and release mode

- src/main/host/memory_manager.rs
I experimentally verified that when mmap'ing anonymous regions, the MemoryManager was effectively pre-allocating the space in /dev/shm. i.e. the allocation showed up in `df` and in the shared section of `free`. It turns out that posix_fallocate and fallocate pre-reserve the requested space. ftruncate OTOH appaars to provide the behavior we want of making the given region accessible, but only actually allocating space for pages that are written to.
> Memory manager usage

- src/test/tor/minimal/CMakeLists.txt
A really small change, but it's been bugging me for a while.
> Quiet output of grep when building tor test

- src/test/futex/test_futex.c
I believe this should address a failure I saw in the GH CI, but have
been unable to reproduce locally.
> test_futex: loop to avoid race conditions when run natively

- src/main/core/controller.c
- src/main/core/support/configuration.c
- src/main/core/support/configuration.h
- src/main/host/host.c
- src/main/host/host.h
- src/main/routing/topology.c
- src/main/routing/topology.h
> Removed deprecated 'geocode' config/topology option

- src/main/core/support/options.c
This option isn't used anywhere.
> Remove unused '--interface-batch' option

- src/main/core/controller.c
- src/main/core/manager.c
- src/main/core/manager.h
- src/main/core/support/configuration.c
- src/main/core/support/configuration.h
Always get the preload path from the rpath. Closes #1215.
> Remove the 'preload' option

- src/main/bindings/c/bindings.h
- src/main/core/controller.c
- src/main/core/main.c
- src/main/core/manager.c
- src/main/core/support/configuration.rs
- src/main/host/cpu.c
- src/main/routing/topology.c
Small miscellaneous changes that were pulled out of the new arg/config parsing changes.
> (Part 2) Command-line parsing and YAML config files in Rust

- src/main/host/memory_manager.rs
This is where argv and environment variables are stored; remapping it
breaks /proc/*/cmdline and /proc/*/environ, which in turn breaks tools
like ps and htop.
Fixes #1268
> MemoryManager: Preserve top page of stack

- .github/workflows/run_tests.yml
- ci/run.sh
- docs/1.1-Shadow.md
- src/main/host/syscall_handler.c
- src/main/shmem/shmem_cleanup.c
> Deprecate ubuntu 16.04

- docs/3.1-Shadow-Config.md
- src/main/Cargo.toml
- src/main/core/support/configuration.rs
Small changes to update the documentation, and set the minimum rust log level in debug mode.
> Update min log level in release mode, and docs

- src/test/futex/test_futex.c
When run natively, we can't guarantee that the futex won't have already
been released by the parent by the time we try to lock it.
> futex_test: fix races for child taking lock

- src/main/routing/topology.c
> Fix shortest path logic for undirected graphs

- src/main/routing/topology.c
> Don't double-count latency when an edge is a self-loop

- src/main/routing/topology.c
> Merge main into dev

- docs/3.2-Network-Config.md
- docs/network_graph_attributes.md
- src/tools/convert_legacy_config.py
- src/tools/convert_legacy_topology.py
Closes #776
(I'm not sure if all of the links are working correctly, so we should double check that before merging.)
> Update network topology file documentation

- src/main/host/descriptor/tcp.c
* tcp_acceptServerPeer: Don't silently ignore NULLs 
* _tcp_logCongestionInfo: Calculate packet loss in floating-point
> Tcp clangtidy

- CMakeLists.txt
- resource/CMakeLists.txt
I don't think we need any of these files to be installed anymore.
> Removed unnecessary files from installation

- docs/network_graph_attributes.md
- src/main/routing/topology.c
- src/test/tor/minimal/tor-minimal.yaml
> Change topology jitter from float to string

- README.md
- docs/ci.md
- docs/coding_style.md
- docs/contributing.md
- docs/developer_guide.md
- docs/install_dependencies.md
- docs/install_shadow_with_docker.md
- docs/maintainer_playbook.md
- docs/migrating_from_1x.md
- docs/network_graph_overview.md
- docs/network_graph_spec.md
- docs/pull_requests.md
- docs/shadow_config_overview.md
- docs/shadow_config_spec.md
- docs/supported_platforms.md
- docs/system_configuration.md
- Fixes a few whitespace issues
- Normalizes the markdown headings to use consistent heading levels
> Formatting changes to docs

- .github/pr_labeler_conf.yml
- .github/workflows/pr_metadata.yml
Adds an action workflow to auto-assign the author and apply component labels when pull requests are opened.
> Auto assign author and labels to pull requests

- docs/shadow_config_spec.md
- src/main/core/support/configuration.rs
Now users can see the graph attributes.
> Copied '1_gbit_switch' graph to docs

- src/lib/shim/shim.c
By default, installing a seccomp filter sets the PR_SPEC_FORCE_DISABLE
bit (see prctl(2)). This results in a significant performance penalty.
Meanwhile Shadow is semi-cooperative with its virtual processes; it
doesn't try to protect itself or the system from malicious code. Hence,
it isn't worth paying this overhead.
Here we use the SECCOMP_FILTER_FLAG_SPEC_ALLOW to override this
behavior.
> seccomp: Disable Speculative Store Bypass mitigation

- src/main/host/syscall/futex.c
- src/main/host/syscall/poll.c
- src/main/host/syscall/protected.c
- src/main/host/syscall/protected.h
- src/main/host/syscall/time.c
- src/main/host/syscall_handler.c
- src/test/futex/test_futex.c
Progress on
https://github.com/shadow/shadow/issues/1262
> Handle FUTEX_BITSET_MATCH_ANY case of futex bitset ops

- src/main/host/syscall/signal.c
The signal handler syscalls accept variable-sized signal sets to support
future expansion. They also use a different struct layout than the
userspace `struct sigaction`, presumably for this reason (it puts the
signal set last).
> signal syscalls: handle variable sized signal sets

- src/main/host/process.c
> Ensure thread is really dead before notifying other threads that it is

- src/main/host/descriptor/file.c
- src/main/host/descriptor/file.h
- src/main/host/syscall/fileat.c
- src/test/file/test_file.c
> Fixed bug when using AT_FDCWD

- src/main/utility/childpid_watcher.rs
epoll_wait doesn't automatically restart when a signal is received (see
signal(7)). We need to check for EINTR and retry.
> childpid watcher: retry on EINTR

- docs/README.md
- docs/SUMMARY.md
- docs/security.md
- docs/sidechannels.md
- src/main/core/main.c
> spec-store-bypass: add a warning and documentation

- src/lib/tsc/tsc.c
In https://github.com/shadow/shadow/issues/1519 we found that the
frequency from the CPU brand string can be substantially off from the
TSC rate (3% in this case), so it's worth implementing more of the cpuid
0x15h method of finding the TSC rate.
> TSC: Use CPU model map to find crystal frequency

- src/lib/logger/logger.c
Fixes bug introduced in d167ccd6ee39bc7bdbe9e0d7020f79ab08aeaf6f
> logger bugfix: Enforce log levels

- src/main/bindings/c/bindings.h
- src/main/core/controller.c
- src/main/core/support/configuration.rs
Fixes https://github.com/shadow/shadow/issues/1522
> Graceful exit when program path doesn't exist

- .github/workflows/run_tests.yml
- ci/run.sh
- docs/ci.md
- docs/install_dependencies.md
- docs/supported_platforms.md
Related: #1254
Blocked by: #1312
> Support Fedora 34 instead of 33

- src/test/CMakeLists.txt
> Added 'G_DEBUG=fatal-criticals' to tests

- src/main/core/main.c
Closes #1534. I don't see any other limits we would want to increase.
> Increase RLIMIT_NPROC to hard limit

- src/main/host/descriptor/epoll.c
Fixes the issue where shadow gets stuck in #1540. The bug occurs with edge-triggered watch objects.
> Fixed bug where epoll ready list contained non-ready items

- src/main/host/descriptor/epoll.c
Fixing a dumb mistake I made in #1548.
> Fixed small bug in 'epoll_getEvents()' in release mode

- src/main/host/affinity.c
Previously, with pinning enabled, Shadow would ignore its initial CPU affinity when assigning threads to CPUs. With this change, it checks the initial affinity, and only considers assigning to CPUs in the initial affinity set.
Progress on https://github.com/shadow/shadow/issues/1565
> Respect shadow's initial CPU affinity

- docs/README.md
- docs/SUMMARY.md
- docs/parallel_sims.md
> Add documentation for working with CPU affinity

- src/main/host/network_interface.c
With the following network, the pcap showed the server 11.0.0.4 sending the SYN/ACK before receiving the SYN. The timestamps are the same for both packets, but the issue was the received packet was recorded only after it had been processed, which involved sending a new packet and recording it.
This PR fixes the order by recording the packets in the pcap earlier.
```yaml
general:
stop_time: 10
network:
graph:
type: gml
inline: |
graph [
node [
id 0
host_bandwidth_down "100 Mbit"
host_bandwidth_up "100 Mbit"
]
edge [
source 0
target 0
latency "500 ms"
]
]
host_defaults:
pcap_directory: 'pcaps'
hosts:
server:
network_node_id: 0
processes:
- path: /usr/bin/python3
args: -m http.server 80
start_time: 3
client:
network_node_id: 0
quantity: 3
processes:
- path: /usr/bin/curl
args: -s server …
```
> Fix order of packets in pcap

- src/test/socket/accept/test_accept.rs
My understanding was that connect() on localhost in Linux never returns EINPROGRESS, but that seems to be wrong, so this test was removed.
> Removed failing accept() test

- src/main/bindings/c/bindings.h
- src/main/bindings/rust/wrapper.rs
- src/main/core/controller.c
- src/main/core/controller.h
- src/main/core/manager.c
- src/main/core/manager.h
- src/main/core/worker.c
- src/main/core/worker.h
- src/main/routing/network_graph.rs
Fixes the three bugs in #1611. This should improve the simulation accuracy, but will probably lead to longer simulation runtimes.
> Fix incorrect controller minimum time jump calculation

- src/main/host/host.c
- src/test/socket/bind/CMakeLists.txt
- src/test/socket/bind/test_bind.rs
> Fixed infinite loop in '_host_getRandomPort()'

- src/main/host/syscall_condition.c
> Re-schedule syscall condition after spurious wakeup

- src/main/Cargo.lock
- src/main/Cargo.toml
- src/main/core/controller.c
- src/main/core/manager.c
- src/main/core/manager.h
- src/main/core/scheduler/scheduler.c
- src/main/core/scheduler/scheduler.h
- src/main/core/support/configuration.rs
- src/test/CMakeLists.txt
- src/test/config/CMakeLists.txt
- src/test/config/parsing/CMakeLists.txt
- src/test/config/parsing/error-on-duplicate-hosts-1.yaml
- src/test/config/parsing/error-on-duplicate-hosts-2.yaml
The previous behaviour was that one host would be "overwritten" by the other with the same name.
> Error if two hosts have the same hostname

- src/main/host/thread_ptrace.c
In ptrace-only mode, it doesn't make sense to use sched_yield + non-blocking calls to waitpid, vs just making a blocking call to waitpid. While spinning is slightly faster in some cases, it hurts substantially in others. e.g. on my machine this PR takes tor-minimal-shadow-ptrace from ~21.6 to ~18.8s.
> thread_ptrace: drop unnecessary spinning

- src/main/bindings/c/bindings-opaque.h
- src/main/bindings/c/bindings.h
- src/main/core/main.rs
- src/main/core/support/configuration.rs
Closes #1652 and closes #1464.
> Fixed '--version' and '--help' parsing

- src/test/pipe/test_pipe.rs
> Re-enable pipe tests

- src/main/host/descriptor/epoll.c
Closes #1101.
I don't see a good way to add an integration test for this, but once we have this in rust, a unit test would be easier.
> Remove file from epoll interest list when closed

- src/main/routing/network_graph.rs
I think this is an improvement.
> Improved error message when assigning IP more than once

- src/main/bindings/c/bindings.h
- src/main/core/controller.c
- src/main/core/manager.c
- src/main/core/support/configuration.rs
- src/main/host/process.c
- src/main/routing/network_graph.rs
Fixes some of the issues from #1275.
> Fix some panics caused by invalid user input

- src/main/core/support/configuration.rs
This should catch more conditions that would later lead to shadow aborting unexpectedly.
For: #1275
> Check that the process path is an executable file

- src/main/core/main.rs
These nix functions were included in the latest nix release.
> Updated 'raise_rlimit()' to use nix functions

- src/main/host/syscall/poll.c
- src/test/poll/test_poll.rs
In particular, curl uses `poll` with nfds=0 but a non-zero timeout to wait in what would otherwise be a busy-loop that doesn't advance time.
Progress on #1549
> poll and epoll: wait for timeout even with no fd's

- src/main/CMakeLists.txt
- src/test/CMakeLists.txt
> Fix coverage tests

- src/main/bindings/c/bindings.h
- src/main/host/descriptor/pipe.rs
- src/main/host/syscall/unistd.rs
- src/main/utility/byte_queue.rs
- src/test/pipe/test_pipe.rs
This is included in the unix socket milestone since these changes are also required to support unix sockets in the future.
> Improve pipes

- .github/workflows/ci_maintenance.yml
> Fix permissions for "CI Maintenance" workflow

- .github/workflows/lint.yml
- .github/workflows/run_tor.yml
- ci/container_scripts/install_extra_deps.sh
> Update versions of tools used in CI

- src/main/bindings/rust/wrapper.rs
- src/main/host/process.c
- src/main/host/process.h
- src/test/regression/CMakeLists.txt
- src/test/regression/small_stop_time.yaml
> Fix shadow hang when plugins start after the sim stop time

- README.md
I think it's good to have a link to the documentation and an example at the top of the README.
> Added documentation and examples links to top of README

- src/main/host/syscall/format.rs
If it's printing a lot of non-graphic bytes, then it's probably not a string. This PR limits the number of non-graphic bytes shown.
Example, rather than printing 40 copies of `\x01`, it now only prints 12.
```
00:00:01.030 [tid 1000] sendto(3, "\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01"..., 65508, (empty), 0x0, 0) = -90 (EMSGSIZE: Message too long)
```
> Print fewer non-graphic characters in strace string

- src/main/host/syscall/format.rs
Followup from discussion in #1903.
> Switch use of reader() with memory_ref_prefix() in strace string logger

- src/main/core/support/configuration.rs
Example config:
```yaml
hosts:
testnode:
network_node_id: 0
processes:
- path: /bin/sleep
args: 4
```
Old error:
```
Could not parse configuration file "/tmp/shadow.yaml"
Caused by:
hosts.testnode.processes[0]: data did not match any variant of untagged enum ProcessArgs at line 5 column 11
```
New error:
```
Could not parse configuration file "/tmp/shadow.yaml"
Caused by:
hosts.testnode.processes[0]: invalid type: integer `4`, expected a string or a sequence of strings at line 5 column 11
```
> Improve error message when parsing yaml process arguments

- src/main/host/syscall/socket.c
- src/test/socket/sockopt/test_sockopt.rs
Shadow doesn't support nagle's algorithm, so shadow always behaves as if `TCP_NODELAY` is enabled. Some programs will fail if `setsockopt(fd, SOL_TCP, TCP_NODELAY, &1, sizeof(int))` returns an error, so we treat this as a no-op for compatibility.
Three examples I can think of that fail when they're unable to set `TCP_NODELAY` are nginx (unless using `tcp_nodelay off`), python's urllib library, and salticidae-based programs.
> Improve behaviour when TCP_NODELAY is set

- src/lib/libc_preload/gen_syscall_wrappers_c.py
- src/lib/libc_preload/interpose.h
- src/lib/libc_preload/syscall_wrappers.c
- src/main/host/syscall/time.c
- src/test/sleep/sleep.yaml
- src/test/sleep/test_sleep.rs
- src/test/test_utils.rs
> Fix and test nanosleep signal interruption

- src/main/host/syscall/socket.c
- src/test/socket/socket/test_socket.rs
Small change to enable a missing test.
> Fix errno for socket() with SOCK_SEQPACKET type

- src/main/host/syscall/handler/socket.rs
The nix documentation for [`sockaddr_storage_to_addr()`](https://docs.rs/nix/latest/nix/sys/socket/fn.sockaddr_storage_to_addr.html) says "[The length] must be *at least as large* as all the useful parts of the structure" (emphasis added), but for unix pathname sockets, it can panic if the length is not exactly equal to `offsetof(addr.path) + strlen(addr.path)` (or that +1). This PR adds a workaround for that issue.
> Fix a bug when converting to a nix 'SockAddr'

- src/main/host/syscall/handler/socket.rs
Made a really dumb mistake in the ptr copy, thankfully we had tests :)
> Fix invalid mem read bug in 'sockaddr_storage_len_workaround()'

- .github/workflows/lint.yml
It appears to be broken at head https://github.com/shadow/shadow/runs/5778366573?check_suite_focus=true
> Pin version of the setup-python action

- src/main/host/syscall_handler.c
I'd dropped this by accident when revising the original PR.
> Increment unblocked count for shadow-side syscalls

- docs/iperf2.md
I assume this is what was meant?
> fix doc typo

- src/lib/shim/patch_vdso.c
Fixes https://github.com/shadow/shadow/issues/2021
> Use precise vdso trampoline size

- src/lib/shim/shim_event.h
- src/lib/shim/shim_syscall.c
- src/main/bindings/rust/wrapper.rs
- src/main/host/descriptor/descriptor.c
- src/main/host/descriptor/descriptor.h
- src/main/host/descriptor/eventfd.rs
- src/main/host/descriptor/mod.rs
- src/main/host/descriptor/pipe.rs
- src/main/host/descriptor/socket/mod.rs
- src/main/host/descriptor/socket/unix.rs
- src/main/host/syscall/epoll.c
- src/main/host/syscall/format.rs
- src/main/host/syscall/futex.c
- src/main/host/syscall/handler/socket.rs
- src/main/host/syscall/handler/unistd.rs
- src/main/host/syscall/mod.rs
- src/main/host/syscall/poll.c
- src/main/host/syscall/socket.c
- src/main/host/syscall/time.c
- src/main/host/syscall/uio.c
- src/main/host/syscall/unistd.c
- src/main/host/syscall_handler.c
- src/main/host/syscall_types.h
- src/main/host/syscall_types.rs
- src/main/host/thread_preload.c
- src/test/signal/test_signals.rs
> Add support for SA_RESTART

- src/test/socket/listen/test_listen.rs
Wanted to check if listening unix sockets with incoming connection queue space available were writable or not, so just made it into a generalized test instead.
> Test if listening sockets are readable/writable

- docs/shadow_config_spec.md
- src/test/Cargo.toml
- src/test/unistd/CMakeLists.txt
- src/test/unistd/pid_assignment.yaml
- src/test/unistd/test_pid_assignment.rs
> Document and test PID assignment order

- docs/shadow_config_spec.md
I think this behaviour is worth documenting.
> Add documentation about host iteration order

- ci/run.sh
Docker's seccomp policy disables the `personality` syscall, which causes shadow to be unable to disable ASLR, which causes some tests to fail.
https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile
> ci/run.sh: Use --security-opt=seccomp=unconfined

- docs/curl.md
- docs/iperf3.md
- docs/shadow_config_spec.md
- src/lib/shim/shim_shmem.c
- src/lib/shim/shim_shmem.h
- src/lib/shim/shim_sys.c
- src/main/bindings/c/bindings.h
- src/main/core/support/configuration.rs
- src/main/host/host.c
- src/main/host/syscall_handler.c
- src/test/examples/basic-file-transfer/CMakeLists.txt
- src/test/examples/basic-file-transfer/basic-file-transfer-example.yaml
- src/test/golang/go_preempt.yaml
- src/test/regression/CMakeLists.txt
- src/test/regression/busy_wait.yaml
> Add option general.model_unblocked_syscall_latency

- src/test/signal/test_signals.rs
Progress on https://github.com/shadow/shadow/issues/2091
> Add test for handling sigsegv

- src/main/bindings/c/bindings.h
- src/main/bindings/c/cbindgen-opaque.toml
- src/main/bindings/c/cbindgen.toml
- src/main/bindings/rust/wrapper.rs
- src/main/core/scheduler/scheduler_policy_host_single.c
- src/main/core/scheduler/scheduler_policy_thread_single.c
- src/main/core/support/configuration.rs
- src/main/core/support/definitions.h
- src/main/core/support/emulated_time.rs
- src/main/core/support/simulation_time.rs
- src/main/core/work/event.c
- src/main/core/worker.c
- src/main/core/worker.h
- src/main/core/worker.rs
- src/main/host/descriptor/epoll.c
- src/main/host/descriptor/tcp.c
- src/main/host/descriptor/timer.c
- src/main/host/network_interface.c
- src/main/host/process.c
- src/main/host/syscall/epoll.c
- src/main/host/syscall/futex.c
- src/main/host/syscall/poll.c
- src/main/host/syscall/time.c
- src/main/host/syscall_condition.c
- src/main/host/syscall_condition.h
- src/main/host/syscall_handler.c
- src/main/host/thread_preload.c
- src/main/host/thread_ptrace.c
- src/main/host/tracker.c
- src/main/routing/router_queue_codel.c
> Reduce usage of SimulationTime in favor of EmulatedTime

- src/main/host/descriptor/eventfd.rs
- src/main/host/descriptor/mod.rs
- src/main/host/descriptor/pipe.rs
- src/main/host/descriptor/socket/abstract_unix_ns.rs
- src/main/host/descriptor/socket/mod.rs
- src/main/host/descriptor/socket/unix.rs
- src/main/host/syscall/handler/eventfd.rs
- src/main/host/syscall/handler/socket.rs
- src/main/host/syscall/handler/unistd.rs
> Rename 'PipeFile', 'UnixSocketFile', and 'EventFdFile'

- src/main/bindings/rust/CMakeLists.txt
- src/main/host/descriptor/compat_socket.c
- src/main/host/descriptor/compat_socket.h
- src/main/host/descriptor/mod.rs
- src/main/host/descriptor/socket.c
- src/main/host/descriptor/socket.h
- src/main/host/descriptor/socket/mod.rs
- src/main/host/descriptor/socket/unix.rs
- src/main/host/descriptor/tcp.c
- src/main/host/descriptor/udp.c
- src/main/host/syscall/handler/socket.rs
- src/main/host/syscall/ioctl.c
- src/main/host/syscall/socket.c
- `Socket` => `LegacySocket`
- `SocketFile` => `Socket`
Part of #2040.
> Rename 'Socket' and 'SocketFile'

- docs/assets/files-and-descriptors.svg
- docs/coding.md
- mdbook/custom.css
> Add file/descriptor diagram in documentation

- docs/assets/files-and-descriptors.svg
- mdbook/custom.css
The diagram now adapts better when changing themes.
> Improve documentation diagram colors when switching themes

- src/main/core/support/configuration.rs
There is currently no way to set a "null" state for cli options with clap, even when that same option supports "null" values in the configuration file. This change allows you to specify "null" for any cli option that uses the `NullableOption` wrapper in the configuration code.
In the shadow configuration, "null" is generally used to mean "disabled". For example, the "template_directory" (`Option<String>`) option is disabled by setting it to "null" (and is set to "null" by default since shadow doesn't use a template directory by default), which corresponds to a `None` value in the rust code.
> Allow "null" values for some cli options

- src/main/utility/proc_maps.rs
I think inodes on Linux should always be [positive](https://docs.rs/libc/latest/libc/type.ino_t.html), and some filesystems support [64-bit inodes](https://www.mjr19.org.uk/sw/inodes64.html).
Probably fixes #2144.
> Change proc map inode from i32 to u64

- src/main/core/work/task.rs
- src/main/utility/mod.rs
We can probably eventually remove this, but during the migration it seems useful for pointers to Rust objects that may be stored in C
> Move MAGIC to a helper

- src/main/host/descriptor/tcp.c
Since Shadow doesn't give SYN packets a sequence number, they aren't retransmitted if the packet gets dropped. This PR gives them a sequence number. This is required to support finite-sized syn/accept queues in the listener.
As an example, here are the pcaps for the following shadow simulation of a client connecting to a server. In both cases, `_tcp_processPacket()` was modified to drop all SYN packets when in the `TCPS_LISTEN` state:
```c
case TCPS_LISTEN: {
/* receive SYN, send SYNACK, move to SYNRECEIVED */
if(header->flags & PTCP_SYN) {
MAGIC_ASSERT(tcp->server);
flags |= TCP_PF_PROCESSED;
packet_addDeliveryStatus(packet, PDS_RCV_SOCKET_DROPPED);
return;
```
Without PR (packet is not retransmitted):
With PR:
```yaml
general:
stop_time: 120s
network:
graph:
type: 1_gbit_switch
hosts: …
```
> Support retransmission of SYN packets

- .github/workflows/coverage.yml
- .github/workflows/docker.yml
- .github/workflows/lint.yml
- .github/workflows/run_tests.yml
- .github/workflows/run_tor.yml
Checkout PR head instead of merge result
Fixes https://github.com/shadow/shadow/issues/2166
> Checkout PR head

- src/main/host/descriptor/tcp.c
- src/main/host/descriptor/tcp.h
- src/main/host/syscall/socket.c
- src/test/socket/connect/test_connect.rs
- src/test/socket/listen/listen.yaml
- src/test/socket/listen/test_listen.rs
Closes #1827. I'll run a tor benchmark before merging to make sure nothing unexpected happens.
> Added finite-sized socket accept queue

- src/test/socket/sendto_recvfrom/test_sendto_recvfrom.rs
Workaround for https://github.com/shadow/shadow/issues/2195
> test_unix_dgram_multiple_senders: tolerate unexplained Linux behavior

- docs/SUMMARY.md
- docs/semver.md
- docs/supported_platforms.md
> Document "stability guarantees" and kernel version requirement

- CHANGELOG
We plan to use this changelog file help track changes for our next release announcements, and will empty this file after each release.
> Added empty CHANGELOG file

- src/main/core/manager.c
- src/main/host/futex.c
- src/main/host/process.c
> Fixed misc memory leaks

- CHANGELOG
- src/main/host/descriptor/epoll.c
- src/main/host/syscall/epoll.c
- src/test/Cargo.toml
- src/test/epoll/CMakeLists.txt
- src/test/epoll/epoll-rs.yaml
- src/test/epoll/test_epoll.c
- src/test/epoll/test_epoll.rs
- src/test/itimer/test_itimer.rs
Fixes https://github.com/shadow/shadow/issues/2260
> epoll_wait: re-block when events were consumed by another thread

- src/main/host/syscall/handler/fcntl.rs
This unbreaks arti's usage of sqlite. Unfortunately this implementation
is incorrect if multiple processes actually access the same file's
locks. See https://github.com/shadow/shadow/issues/2258
> Re-enable fcntl locking for regular files

- src/main/host/descriptor/socket/unix.rs
- src/test/resolver/test_getaddrinfo.c
- src/test/socket/connect/test_connect.rs
- src/test/test_utils.rs
> Return `ENOENT` for unix socket `connect()` with pathname address

- src/main/host/descriptor/socket/unix.rs
Noticed a warning in the unix socket code that was incorrectly being shown.
> Fixed a warning in the unix socket code

- CHANGELOG
Waiting to see if #2286 has actually been fixed.
> Added entries to CHANGELOG

- docs/compatibility_notes.md
- docs/getting_started_tgen.md
Partly addresses https://github.com/shadow/shadow/discussions/2299
> Improve tgen / busy-loop documentation

- .github/workflows/run_tests_incremental.yml
* quote variables in bash
* enable bash command echo
> run_tests_incremental: minor cleanup

- src/main/bindings/c/bindings-opaque.h
- src/main/bindings/c/bindings.h
- src/main/core/scheduler/scheduler_policy_host_single.c
- src/main/core/work/event.rs
- src/main/core/work/event_queue.rs
- src/main/core/work/mod.rs
Will run a performance benchmark before merging.
**Edit:** No noticeable performance change, and the results appear to be the same:
> Move the scheduler's priority queue to rust

- src/main/core/controller.rs
- src/main/core/manager.rs
They still use `SimulationTime` at the ffi to keep the interface simpler, but that will go away as we move more code to rust.
> Use `EmulatedTime` in `Manager` and `Controller`

- src/main/core/work/event.rs
- src/main/core/work/task.rs
- src/main/host/timer.rs
- src/main/utility/mod.rs
I stumbled across TypeId and realized this would be a little nicer
> Magic: use TypeOf instead of an arbitrary integer

- src/main/host/host.rs
We will want the `Host` to be at least `Send`. I want to put a `!Sync` marker on it for now since I think we can write the `Host` to not require a lock. If we feel this is too restrictive we can remove this limitation in the future.
> Add the `Send` marker to `Host`

- docs/debugging.md
Wanted to write this down somewhere before I forget about it.
> Add a note about DWARF error due to incompatible GDB version

- ci/run.sh
In most cases this won't actually do much, since the dependencies will have already been installed when building the image.
In PRs that add a new package dependency, this will allow it to be installed the incremental-build tests to pass without having to rebuild the base images.
> Always (re)-install system dependencies in CI

- src/Cargo.lock
- src/lib/logger/build.rs
- src/lib/shadow-build-common/Cargo.toml
- src/lib/shadow-build-common/src/lib.rs
- src/lib/shadow-shim-helper-rs/Cargo.toml
- src/lib/shadow-shim-helper-rs/build.rs
- src/lib/shadow-shim-helper-rs/shim_shmem.c
- src/lib/shadow-shim-helper-rs/shim_shmem.h
- src/lib/shmem/build.rs
- src/lib/tsc/Cargo.toml
- src/lib/tsc/build.rs
- src/main/Cargo.toml
- src/main/build.rs
Obsoletes https://github.com/shadow/shadow/pull/2436
> Bump system deps

- src/main/build.rs
- src/main/host/syscall/format.rs
- src/main/host/syscall/handler/file.rs
- src/main/host/syscall/handler/mod.rs
- src/main/host/syscall_handler.c
This makes it easier to debug with strace logging.
> Add rust wrappers for open and openat syscalls

- src/main/host/syscall/uio.c
- src/test/tcp/CMakeLists.txt
This fixes more (but not all) issues from #2379.
> Fix more readv/writev bugs and enable lossless+loopback iov tcp tests

- src/lib/libc_preload/gen_syscall_wrappers_c.py
- src/lib/libc_preload/syscall_wrappers.c
- src/main/host/syscall/uio.c
- src/main/host/syscall/unistd.c
- src/main/host/syscall/unistd.h
- src/test/file/test_file.c
Another bunch of fixes for #2379.
> Fix readv/writev for regular files, and support preadv and pwritev

- src/main/Cargo.toml
- src/main/core/support/units.rs
- src/main/host/context.rs
- src/main/host/memory_manager/mod.rs
- src/main/host/syscall_types.rs
- src/main/utility/enum_passthrough.rs
- src/main/utility/interval_map.rs
This adds doc tests in shadow-rs.
> Build an rlib for shadow-rs

- src/main/core/scheduler/mod.rs
- src/main/core/scheduler/pools/bounded.rs
- src/main/core/scheduler/pools/unbounded.rs
- src/main/utility/synchronization/semaphore.rs
This should resolve the review comments from #2448.
> Cleanup scheduler-related code

- .github/workflows/run_tor.yml
- .github/workflows/sanitizers.yml
- ci/container_scripts/install_extra_deps.sh
> Update versions used in the CI workflows

- src/Cargo.lock
- src/main/Cargo.toml
- src/main/core/main.rs
Closes #2188 .
Hi. I am quite new to rust and am trying to learn on the fly. Please do let me know if this PR can be improved.
> Add signal handler to flush logger on SIGINT/SIGTERM

- src/main/core/scheduler/pools/bounded.rs
`gettid()` and `sched_setaffinity()` are not allowed under miri.
> Support the 'bounded' thread pool tests under miri

- src/main/routing/router_queue_codel.c
> Fix order of operations in codel control law

- src/main/host/timer.rs
This may improve performance, but the effect is likely negligible for large sims.
It doesn't appear to have a performance impact on tor sims. The network results also remain the same.
> Align timer events in 1-second increments

- docs/compatibility_notes.md
(BitTorrent example requires #2488 to work)
> Add BitTorrent and Node.js examples to compatibility notes

- src/lib/shadow-shim-helper-rs/src/rootedcell/rc.rs
RootedRcWeak is to RootedRc as std::rc::Weak is to std::rc::Rc.
> add RootedRcWeak

- CHANGELOG
Should have been added in #2479
> Add changelog entry for codel bugfix

- .github/workflows/lint.yml
- src/lib/syscall-logger/src/lib.rs
- src/main/core/manager.rs
- src/main/host/syscall/format.rs
- src/main/host/syscall/handler/sched.rs
- src/main/host/syscall/handler/socket.rs
I don't really think the code needed to change, I just keep forgetting that this exists and wanted to see some places where it would be useful. Might as well merge them I think since it is slightly more readable.
> Add uses of 'let-else' statements

- .github/workflows/run_examples.yml
- docs/compatibility_notes.md
- examples/CMakeLists.txt
- examples/curl/CMakeLists.txt
- examples/curl/install_deps.sh
- examples/curl/run.sh
- examples/curl/shadow.yaml
- examples/http-server/CMakeLists.txt
- examples/http-server/install_deps.sh
- examples/http-server/run.sh
- examples/http-server/shadow.yaml
- examples/iperf-2/CMakeLists.txt
- examples/iperf-2/install_deps.sh
- examples/iperf-2/run.sh
- examples/iperf-2/shadow.yaml
There are still a few remaining examples from "Compatibility Notes" that aren't straightforward to add tests for.
> Add more examples

- src/main/core/support/definitions.h
- src/main/host/host.c
- src/main/host/host.h
- src/main/host/host.rs
This replaces the C implementation `hostc_getRandomFreePort`
> Implement Host::get_random_free_port

- src/test/bindc/test_bind.c
The test was calling connect twice but incorrectly comparing the first accepted socket with the second connect socket (which was already closed). This synchronizes the calls to connect(), accept(), and close() so that we correctly compare the ports of the related tuple of client, listener, and accepted sockets.
> Fix an issue with the `_test_implicit_bind` test

- src/main/build.rs
- src/main/network/packet.rs
> Issue 2619; fixes TCP header sizes in pcap files

- src/tools/plot-shadow.py
Alternates colors and line styles rather than just colors.
> Improve line styles in plotting script

- src/main/host/network_interface.c
> Check for specific socket association before wildcard

- src/main/build.rs
- src/main/core/worker.rs
- src/main/host/host.rs
- src/main/host/process.c
- src/main/host/process.h
- src/main/host/process.rs
- src/main/host/thread.c
Stopped at a fairly arbitrary point just to sync up.
> Convert some Process code to Rust

- src/main/host/descriptor/tcp.c
On slow connections, it is possible that retransmitted packets end up in the input queue multiple times. Before this change, Shadow would stall because it was looking for the `n`th packet to deliver to the plugin, but the next in-order packet in the queue was the `n-1`th packet.
> Don't stall when already delivered packets are queued

- src/main/host/network_interface.c
Previously if the tracker tries to deref the pointer, it would be a use-after-free.
> Fix dangling socket pointer in the network interface

- src/lib/shadow-shim-helper-rs/src/rootedcell/cell.rs
- src/lib/shadow-shim-helper-rs/src/rootedcell/mod.rs
This is the Rooted equivalent of `std::cell::Cell`
> Add RootedCell

- docs/install_dependencies.md
I missed this in #2756. I don't think we need to list these either.
> Remove recommended modules/tools

- src/main/host/descriptor/eventfd.rs
- src/main/host/descriptor/mod.rs
- src/main/host/descriptor/pipe.rs
- src/main/host/descriptor/socket/inet/legacy_tcp.rs
- src/main/host/descriptor/socket/inet/mod.rs
- src/main/host/descriptor/socket/mod.rs
- src/main/host/descriptor/socket/unix.rs
- src/main/host/syscall/handler/unistd.rs
An offset of 0 does not mean no offset.
> Make read/write offsets an `Option`

- .github/workflows/ci_maintenance.yml
- .github/workflows/extra_tests.yml
- .github/workflows/git.yml
- .github/workflows/lint.yml
- .github/workflows/sanitizers.yml
- ci/container_scripts/install_extra_deps.sh
- src/Cargo.lock
- src/lib/shadow-shim-helper-rs/Cargo.toml
- src/lib/shmem/Cargo.toml
- src/lib/syscall-logger/Cargo.toml
- src/lib/vasi-macro/Cargo.toml
- src/lib/vasi-sync/Cargo.toml
- src/main/Cargo.toml
- src/test/Cargo.toml
> Update versions of CI tools and rust dependencies

- src/main/host/syscall/type_formatting.rs
Old:
```
00:00:04.857000000 [tid 1000] sendmsg(-1, 0x7fffffffd548, (empty)) = -9 (EBADF: Bad file number)
```
New:
```
00:00:04.857000000 [tid 1000] sendmsg(-1, msghdr { msg_name: 127.0.0.1:11111 (0x7fffffffdd24), msg_namelen: 16, msg_iov: 0x7fffffffd538, msg_iovlen: 1, msg_control: 0x0, msg_controllen: 0, msg_flags: (empty) } (0x7fffffffd548), (empty)) = -9 (EBADF: Bad file number)
```
> Improve the strace formatting of `msghdr`

- CHANGELOG.md
- docs/shadow_config_complex.md
- docs/shadow_config_overview.md
- docs/shadow_config_spec.md
- src/main/core/main.rs
- src/main/core/support/configuration.rs
This is one of the planned breaking changes for Shadow 3.0. https://github.com/shadow/shadow/discussions/2496
> Always use YAML extended syntax

- docs/shadow_config_spec.md
- src/main/core/manager.rs
- src/main/core/sim_config.rs
- src/main/core/support/configuration.rs
- src/main/host/host.rs
- src/test/determinism/determinism1.test.shadow.config.yaml
- src/test/determinism/determinism2.test.shadow.config.yaml
> Change the `pcap_directory` config option to `pcap_enabled`

- CHANGELOG.md
- docs/getting_started_basic.md
- docs/semver.md
- docs/shadow_config_spec.md
- docs/testing_determinism.md
- examples/curl/run.sh
- examples/etcd/run.sh
- examples/http-server/run.sh
- examples/nginx/run.sh
- src/main/host/network_interface.c
- src/main/host/process.rs
- src/test/determinism/determinism1_compare.cmake
- src/test/determinism/determinism2_compare.cmake
- src/test/signal/CMakeLists.txt
- src/test/tgen/fixed_duration/verify.sh
- src/test/tgen/fixed_size/verify.sh
- src/test/tor/minimal/verify.sh
> Remove hostname prefix from hosts' data files

- src/test/CMakeLists.txt
- src/test/config/CMakeLists.txt
- src/test/examples/CMakeLists.txt
- src/test/regression/CMakeLists.txt
- src/test/socket/CMakeLists.txt
- src/test/tgen/CMakeLists.txt
- src/test/tor/CMakeLists.txt
See discussion at https://github.com/shadow/shadow/pull/2842#discussion_r1160244846.
> Remove unused `ALL_SHADOW_TESTS` from cmake

- src/lib/shim/shim.c
- src/main/core/main.rs
- src/main/core/manager.rs
- src/test/test_common.c
- src/test/test_utils.rs
Progress on https://github.com/shadow/shadow/issues/2848
> Remove SHADOW_SPAWNED env variable

- CHANGELOG.md
- docs/shadow_config_spec.md
- src/main/core/support/configuration.rs
- src/test/config/parsing/CMakeLists.txt
- src/test/config/parsing/hostname-invalid-characters.yaml
> Restrict allowed hostname characters

- examples/curl/run.sh
- examples/etcd/CMakeLists.txt
- examples/etcd/run.sh
- examples/http-server/run.sh
- examples/iperf-2/run.sh
- examples/nginx/run.sh
- examples/wget2/run.sh
The tests would still pass even if shadow failed.
The etcd example still fails: #2858.
> Fix broken example tests

- CHANGELOG.md
- docs/shadow_config_spec.md
- src/main/core/sim_config.rs
- src/test/regression/CMakeLists.txt
This is one of the planned shadow 3.0 breaking changes https://github.com/shadow/shadow/discussions/2496
> Fail if process start or stop time isn't before sim stop time

- CHANGELOG.md
- CMakeLists.txt
- docs/install_dependencies.md
Fixes https://github.com/shadow/shadow/issues/2418
> Bump minimum CMake version

- src/lib/shadow-shim-helper-rs/src/shim_shmem.rs
- src/lib/shim/shim.c
- src/lib/shim/shim_rdtsc.c
- src/main/host/host.rs
- src/main/host/managed_thread.rs
- src/main/host/process.rs
- src/main/host/thread.rs
Progress on https://github.com/shadow/shadow/issues/2848 and on refactoring process initialization and teardown.
> Move more env variables to shared memory

- src/main/utility/synchronization/simple_latch.rs
The latest nightly tor benchmark showed a huge runtime performance change:
@sporksmith found that we were performing futex operations on the `Arc` address rather than its inner `AtomicI32` address, causing the waiter to spin. This was caused by a bug in #2846.
We expect that this PR will increase the runtime back to the original runtime, and we can investigate spinning properly later.
> Futex should operate on the `&AtomicI32`, not the `&Arc`

- docs/compatibility_notes.md
- examples/etcd/CMakeLists.txt
- examples/etcd/shadow.yaml
> Fix the etcd example

- src/main/host/memory_manager/memory_mapper.rs
The MemoryMapper was already creating its backing storage files in tmpfs and unlinking them immediately. Using memfd_create removes a race condition in which the file would be left behind if shadow crashed in between creating the file and unlinking it.
> MemoryMapper: use memfd_create

- src/lib/libc_preload/gen_syscall_wrappers_c.py
- src/lib/libc_preload/syscall_wrappers.c
- src/main/host/memory_manager/mod.rs
- src/main/host/syscall/handler/fcntl.rs
And a couple other miscellaneous changes.
> Skip more shim glibc syscall wrappers

- src/lib/vasi-sync/Cargo.toml
- src/lib/vasi-sync/src/lib.rs
- src/lib/vasi-sync/src/scchannel.rs
- src/lib/vasi-sync/src/scmutex.rs
- src/lib/vasi-sync/src/sync.rs
Progress on https://github.com/shadow/shadow/issues/2919
Note that it still depends on std and libc through dependencies.
> vasi-sync: Make no-std

- src/main/host/syscall/handler/clone.rs
This is mostly a refactor in preparation for supporting fork. https://github.com/shadow/shadow/issues/1987
There are also a couple minor behavioral changes, that shouldn't affect any of our supported thread libraries:
* Some flags that we don't actually care about are no longer required (e.g. CLONE_SYSVEM).
* CLONE_SETTLS *is* now required. Previously we would have tried to go ahead and execute the native clone without it, but the shim would misbehave since it depends on thread local storage.
> clone handler: handle individual flags more explicitly

- CHANGELOG.md
- docs/shadow_config_spec.md
- src/main/core/support/configuration.rs
- src/test/phold/CMakeLists.txt
This is an experimental option.
> Change `interface_qdisc` value `roundrobin` to `round-robin`

- src/lib/shadow-shim-helper-rs/build.rs
- src/lib/shadow-shim-helper-rs/src/shim_shmem.rs
- src/lib/shim/shim.c
- src/main/core/manager.rs
- src/main/host/host.rs
Progress on removing dependencies on environment variables (https://github.com/shadow/shadow/issues/2848) and libc in general (https://github.com/shadow/shadow/issues/2919).
> Move shim logging config into shared memory

- src/main/host/descriptor/socket/inet/legacy_tcp.rs
- src/main/host/descriptor/socket/inet/mod.rs
This is split out of #2959 so that I can try to isolate the performance-related changes in a future smaller PR.
> Fix refcount bug and added `InetSocketWeak`

- src/test/socket/connect/test_connect.rs
I changed this during the rust udp rewrite and added this test to make sure it fixes the udp part of #2592.
> Add udp test for disassociating during `connect()`

- src/lib/shim/shim_seccomp.c
seccomp only supports BPF programs, not eBPF programs.
BPF programs don't support 64-bit operations; only 32-bit operations.
It turns out we were only comparing the 32 least significant bits of the instruction pointer to the 32 least significant bits of the allow-listed code range.
This caused us to incorrectly block syscalls made from the shim in cases where the high and low bounds of the allow-listed range crossed a 2^32 boundary. This was rare, and would have been even rarer when the allow-listed range only contained a couple functions instead of the shim's whole executable section. I only observed it when running relatively large tor simulations under asan. (I don't think asan is special here other than perturbing where things get mapped)
Theoretically this bug would have also caused …
> seccomp filter: properly compare 64-bit addresses

- src/lib/vasi-sync/Cargo.toml
- src/lib/vasi-sync/benches/scchannel.rs
Also makes my rust-analyzer function properly.
> Use rustix in vasi-sync bench, specify correct dev dep

- src/main/host/syscall/type_formatting.rs
A newer bitflags version changed the debug formatting to include the type name (for example `ClockNanosleepFlags(TIMER_ABSTIME)` instead of `TIMER_ABSTIME`) which adds noise to the strace log, so instead we use more explicit formatting.
> Improve formatting of bitflags types in strace logging

- ci/rust-toolchain-nightly.toml
- ci/rust-toolchain-stable.toml
```
channel = "nightly-2023-08-27"
```
and
```
channel = "1.72.0"
```
> Update rust versions in CI to 1.72

- src/lib/tcp/src/buffer.rs
When an application makes many small writes to a tcp socket, the rust tcp socket creates a `Bytes` object for each write. This requires an allocation for each `Bytes` object, which can mean many small allocations. Instead we now pre-allocate a larger `BytesMut` buffer (2 KB) and "break off" new `Bytes` objects from it. So instead of many small allocations, we have fewer large allocations. This does not change the number of `Bytes` objects we have and each write will still have its own `Bytes` object. It's just that these `Bytes` should be allocated more efficiently.
> Reduce the number of allocations needed by rust tcp

- src/lib/linux-api/gen-kernel-bindings.sh
- src/lib/linux-api/src/bindings.rs
- src/lib/linux-api/src/errno.rs
- src/lib/linux-api/src/resource.rs
- src/lib/linux-api/src/signal.rs
- src/lib/linux-api/src/time.rs
- src/main/build.rs
- src/main/host/descriptor/mod.rs
- src/main/host/descriptor/socket/inet/legacy_tcp.rs
- src/main/host/descriptor/socket/inet/tcp.rs
- src/main/host/descriptor/socket/inet/udp.rs
- src/main/host/descriptor/socket/unix.rs
- src/main/host/host.rs
- src/main/host/mod.rs
- src/main/host/process.rs
- src/main/host/status.h
- src/main/host/status_listener.rs
- src/main/host/syscall/handler/mod.rs
- src/main/host/syscall/handler/socket.rs
- src/main/host/syscall/handler/uio.rs
- src/main/host/syscall/handler/wait.rs
- src/main/host/syscall/mod.rs
- src/main/host/syscall_condition.c
- src/main/host/syscall_condition.h
- src/main/host/syscall_handler.c
- src/main/host/syscall_types.rs
- src/test/clone/test_fork.rs
> Implement waitpid and wait4 syscalls

- src/lib/linux-api/src/signal.rs
- src/lib/shadow-shim-helper-rs/src/shim_shmem.rs
- src/lib/shim/src/syscall.rs
- src/main/host/descriptor/descriptor_table.rs
- src/main/host/host.rs
- src/main/host/managed_thread.rs
- src/main/host/memory_manager/mod.rs
- src/main/host/process.rs
- src/main/host/syscall/handler/clone.rs
- src/main/host/syscall/handler/mod.rs
- src/main/host/syscall/handler/unistd.rs
- src/main/host/syscall/handler/wait.rs
- src/main/host/syscall/io.rs
- src/main/host/syscall_handler.c
- src/main/host/thread.rs
- src/main/utility/mod.rs
- src/test/clone/test_fork.rs
- src/test/examples/bash/bash-example.yaml
Fixes #2988 (split `execveat` into #3166)
> Implement execve

- .github/workflows/extra_tests.yml
- docs/getting_started_tgen.md
- examples/docs/CMakeLists.txt
- examples/docs/traffic-generation/CMakeLists.txt
- examples/docs/traffic-generation/install_deps.sh
- examples/docs/traffic-generation/run.sh
- examples/docs/traffic-generation/shadow.yaml
- examples/docs/traffic-generation/show.sh
- examples/docs/traffic-generation/tgen.client.graphml.xml
- examples/docs/traffic-generation/tgen.server.graphml.xml
> Add traffic generation example test in 'examples/docs/'

- CHANGELOG.md
> Update the changelog with missing user-facing changes

- src/lib/vasi-macro/src/lib.rs
- src/lib/vasi-sync/src/scchannel.rs
- src/lib/vasi/src/lib.rs
@stevenengler FYI here's my initial attempt. This doesn't have the `repr` fix from https://github.com/shadow/shadow/pull/3030, so *should* fail to build, but doesn't. I'll try to poke at this some more when I have some cycles, but feel free to also poke if you like :)
> VirtualAddressSpaceIndependent: require FFI safety

- src/main/host/syscall/handler/mman.rs
This restores the pre- 9330318e9 behaviour where we allow mmapping `/etc/localtime`. This fixes #3224.
> Allow mmaping `FILE_TYPE_LOCALTIME` files

- src/Cargo.lock
- src/lib/logger/Cargo.toml
- src/lib/shadow-build-common/Cargo.toml
- src/lib/shadow-build-common/src/lib.rs
- src/lib/shim/Cargo.toml
- src/lib/tsc/Cargo.toml
- src/main/Cargo.toml
Also fixes a deprecation warning.
> Upgrade bindgen to 0.69.1 from 0.68.1

- docs/SUMMARY.md
- docs/contributing.md
- docs/writing_tests.md
Adds more documentation about contributing to shadow and writing tests. This documentation was written collaboratively.
> New documentation for contributing/testing

- ci/rust-toolchain-nightly.toml
- ci/rust-toolchain-stable.toml
- src/main/core/worker.rs
- src/main/host/process.rs
Also some minor nightly clippy fixes.
> Upgrade CI to rust 1.75

- src/main/host/descriptor/socket.c
- src/main/host/descriptor/tcp.c
- src/test/epoll/test_epoll.rs
In the old code when adding or removing data from a socket buffer, a socket.c function would update the file state (called the "status" in the C code), then a tcp.c function might also update the file state. For example `tcp_receiveUserData` would call `legacysocket_removeFromInputBuffer` which would update the state, and then `tcp_receiveUserData` would later also update the state. This would lead to situations where socket.c would remove the READABLE flag, and then tcp.c would immediately add it back. While the end result is that the flag would effectively appear unchanged, this would cause edge-triggered epoll to think that the file's state changed twice even though it effectively didn't, leading to #3274.
Since the TCP code is the only C socket code left, now the socket.c code no …
> Don't update the file state in socket.c

- src/test/clone/test_fork.rs
Fixes https://github.com/shadow/shadow/issues/3275
> test_fork: fix race condition under Linux

- src/lib/shadow-shim-helper-rs/src/explicit_drop.rs
- src/lib/shadow-shim-helper-rs/src/syscall_types.rs
- src/main/host/syscall/handler/clone.rs
- src/main/host/syscall/type_formatting.rs
- src/test/clone/test_clone.rs
Fixes https://github.com/shadow/shadow/issues/3290
> Ensure clone handler drops RootedRc's on early exit

- ci/rust-toolchain-nightly.toml
- ci/rust-toolchain-stable.toml
- src/lib/linux-api/Cargo.toml
- src/lib/log-c2rust/Cargo.toml
- src/lib/shadow-build-common/Cargo.toml
- src/lib/shadow-shim-helper-rs/Cargo.toml
- src/lib/shim/Cargo.toml
- src/lib/tsc/Cargo.toml
- src/lib/vasi-macro/Cargo.toml
- src/main/Cargo.toml
- src/main/host/memory_manager/memory_mapper.rs
- src/test/poll/test_poll.rs
- src/test/random/test_random.rs
- src/test/select/test_select.rs
Also fixes some clippy warnings for rust 1.79-beta.
> Update to rust 1.78 in CI

- src/main/host/syscall/handler/mod.rs
Detect when another thread has raced to warn about a missing syscall number before us, ensuring we really do only warn once about a particular missing syscall number.
This doesn't seem like a substantial problem in practice, but looking at this code again it seems silly not to do this slightly better handling.
> syscall handler mod: fix double-warn race condition

- .github/workflows/extra_tests.yml
- .github/workflows/lint.yml
- ci/rust-toolchain-nightly.toml
> Bump version of some CI tools

- .github/pull_request_template.md
- docs/perf_config_options.md
- docs/system_configuration.md
- src/lib/scheduler/src/lib.rs
- src/lib/scheduler/src/sync/thread_parking.rs
- src/lib/shadow-shim-helper-rs/src/rootedcell/rc.rs
- src/lib/tcp/src/lib.rs
- src/main/host/context.rs
- src/main/host/descriptor/pipe.rs
- src/main/host/descriptor/shared_buf.rs
Some misc documentation and comment changes.
> Small doc/comment improvements

- src/main/host/syscall/handler/mman.rs
The bitflags library `!` (not) operator negates only known bit flags, not all bits. This `open_plugin_file` code should work with all bits, regardless of whether our rust bindings knows about them. The new code should work even with unknown flags.
I always forget that the bitflags negation behaves differently from what I expect it to, and I feel it's a pretty big footgun. For example:
```rust
bitflags::bitflags! {
pub struct Flags: u32 {
const A = 0b00000001;
const B = 0b00000010;
const C = 0b00000100;
}
}
fn main() {
println!("{:#b}", Flags::A.bits());
println!("{:#b}", (!Flags::A).bits());
println!("{:#b}", !Flags::A.bits());
}
```
```text
0b1
0b110
0b11111111111111111111111111111110
```
> Fix minor flag bug in `open_plugin_file`

- src/main/host/syscall/handler/sched.rs
- src/main/utility/macros.rs
Instead of returning `*mut T` like in `field_ptr`, `field_project` returns a `&mut MaybeUninit<T>`. The macro can return mutable references to multiple fields at once, which means the caller doesn't need to worry about writing unsafe code or following stacked borrows rules; the compiler will ensure the macro is being used correctly.
A downside is that the macro needs to uphold a lot of rust's safety guarantees, such as making sure no fields are overlapping and are within bounds.
Example:
```rust
let mut foo: libc::nlmsghdr = shadow_pod::zeroed();
let foo_bytes = unsafe { shadow_pod::as_u8_slice_mut(&mut foo) };
let (foo_nlmsg_type, foo_nlmsg_flags) =
field_project!(foo_bytes, libc::nlmsghdr, (nlmsg_type, nlmsg_flags)).unwrap();
// these are both mutable references to different fields …
```
> Replace 'field_ptr' macro with 'field_project'

- src/main/host/descriptor/descriptor_table.rs
- src/main/host/descriptor/epoll/mod.rs
- src/main/host/descriptor/mod.rs
- src/main/host/descriptor/socket/inet/mod.rs
- src/main/host/descriptor/socket/inet/tcp.rs
- src/main/host/descriptor/socket/inet/udp.rs
- src/main/host/descriptor/socket/netlink.rs
- src/main/host/descriptor/timerfd.rs
- src/main/host/process.rs
- src/main/host/syscall/handler/close_range.rs
- src/main/host/syscall/handler/epoll.rs
- src/main/host/syscall/handler/socket.rs
- src/main/host/syscall/handler/timerfd.rs
- src/main/host/syscall/handler/uio.rs
- src/main/host/syscall/handler/unistd.rs
- src/main/host/thread.rs
- src/main/utility/callback_queue.rs
- src/main/utility/legacy_callback_queue.rs
Follow up from https://github.com/shadow/shadow/pull/3391#discussion_r1720104517. Also some other minor cleanup.
> Reorganized `queue_and_run`/`with_global_cb_queue`

- docs/perf_config_options.md
Adds information about the impact of log messages on simulation performance.
> Add 'log_level' section to 'perf_config_options.md'

- src/main/host/syscall/handler/unistd.rs
- src/test/unistd/unistd.yaml
> Add real-world values for our uname return strings

- CHANGELOG.md
- src/main/core/manager.rs
- src/main/network/dns.rs
> Disallow broadcast and multicast in DNS

- src/main/build.rs
- src/main/core/worker.rs
- src/main/host/descriptor/socket/inet/legacy_tcp.rs
- src/main/host/descriptor/tcp.c
- src/main/host/descriptor/tcp_retransmit_tally.cc
- src/main/host/descriptor/tcp_retransmit_tally.h
- src/main/host/protocol.h
- src/main/network/packet.rs
- src/main/network/router/mod.rs
- src/main/routing/packet.c
- src/main/routing/packet.h
- src/main/routing/packet.minimal.h
Some preparations to simplify migrating the C packet to Rust.
> Prepare to migrate packet to Rust

- src/lib/shim/shim_sys.c
This should have a small performance benefit in busy loops, but is mostly to resolve and remove the "TODO: Once ptrace mode is deprecated ... " comment.
> shim_sys_handle_syscall_locally: remove extra unlock+lock

- src/main/network/graph/mod.rs
> Fix ip addr increment infinite loop

- src/lib/shim/src/reinit_auxvec_random.rs
I had reverted skipping testing `AT_HWCAP2` since it seems to return the same value via glibc as /proc, but looking at the glibc code this might not always hold. Probably better to skip trying to compare it after all.
Also test more precisely whether we expect libc to find a value of 0 vs not find a value at all (in which case it still returns 0 but also sets errno to ENOENT).
Follow-up to #3554; cc @magnified103
> getauxval test: a few robustness tweaks

- src/main/host/descriptor/regular_file.c
Remap /proc/self/* paths to point to the correct native path. Notably this fixes behavior for reading `/proc/self/maps`, which the rust runtime does, and for reading `/proc/self/exe` which asan does.
Log a warning when opening proc files that we haven't specifically tested, thought about, or otherwise vetted.
Progress on #3541
Fixes #3536
Progress on #2790
> Add some /proc handling

- CHANGELOG.md
- src/main/host/descriptor/regular_file.c
- src/test/determinism/test_determinism.c
> Handle /proc/sys/kernel/random/uuid

- src/Cargo.lock
- src/main/Cargo.toml
- src/main/host/descriptor/socket/netlink.rs
- src/test/Cargo.toml
- src/test/epoll/test_epoll_edge.rs
- src/test/netlink/test_ifaddrmsg.rs
- src/test/netlink/test_ifinfomsg.rs
- src/test/netlink/test_send_limit.rs
Closes shadow#3635.
Part of shadow#3555.
> Upgrade neli to 0.7.1
